### ISSUE TITLE
Conditionals: Add Condition CRD and API changes to pipelines to add conditions

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1019]
Tracking issue for API changes for conditional execution + initial implementation based on the design in #27 

ref: https://github.com/tektoncd/pipeline/issues/1137

**Comment by objectiveous** [comment]
I left a comment [here](https://docs.google.com/document/d/1iTb0rDDlgQcPbiYIGJ-atkaML8aCyPCyhfucCPJmNLs/edit#heading=h.isehsedcrq00) but I'm not sure if you'd see it. 

Please consider a "break pointing" condition. For example, imagine you have a GUI w/ an Operations view of running Tekton Pipelines and you discover a PipelineRun that is failing. You might want to rerun the pipeline but pause execution at the beginning of a Task in order to exec into the Pod to inspect the environment.

Does this make sense to model as a Condition?

**Comment by dibyom** [comment]
Hi @objectiveous ! Interesting use case. The initial implementation of conditionals won't have support for this but we do have #233 open for adding support for pausing tasks till a condition is met.

**Comment by m1093782566** [comment]
I think it's really an important feature which is required in my environment.

**Comment by dibyom** [comment]
Closing this since we have added the APIs as well as an implementation that allows running condition containers, along with variable substitution support for parameters.
