### ISSUE TITLE
Proposal: extend taskrun.status.steps to have container name

### ISSUE THREAD

**Issue by hrishin** [tektoncd/pipeline#1027]
Recently while introducing some minor [changes](https://github.com/tektoncd/pipeline/issues/815) in steps status details, it broked some functionality across `CLI`, `Dashboard` and other projects integration.
Maybe because those integration tries to extract some attributes related to the `pod` base on `TaskRun.Status` fields i.e extracting the container name from step's name for fetching the logs for `TaskRun.Status.Steps`.

 It would be nice to extend `TaskRun.Status.Step` attribute to include sufficient information, so that integrations do not need to worry about the change in API internals.

Or

An alternative is to keep the container and step name same.

**Comment by houshengbo** [comment]
@hrishin Could you give more details on the `sufficient information`? With what kind of information do we mean having sufficient?
Per `keep the container and step name same`, it may resolve this issue in a straightforward way, but what if we want to retrieve information other than just container name?
To me, it is better to have a list of the fields or objects we can access the get the necessary information, instead of forcing the step name.

**Comment by hrishin** [comment]
@houshengbo at this moment `container.name` is missing as part of `taskrun.status.step` in our experience.

 > Per keep the container and step name same, it may resolve this issue in a straightforward way

That's what ideally we can do it now unless there is a need to keep container name different from a step name. 
However, changing this would require some form of consensus because it could break the existing integration which leverages step-prefix in order to derive container name.

> but what if we want to retrieve information other than just container name?

I'm not sure if we need other fields at the moment. One such requirement is getting addressed in #1025.

@bobcatfish @vdemeester @andrew-su  @skaegi

**Comment by bobcatfish** [comment]
> Per keep the container and step name same, it may resolve this issue in a straightforward way

I think the only reason these are different right now is to try to make it obvious which containers are steps and which are added by the tekton controller. I wouldn't mind changing this so that the container names and step names are the same (and maybe it would make more sense to preface the names of the containers tekton adds instead? e.g. `tekton-`)

But I think adding the container names to the statuses is the most future proof solution - that way we can make changes like this later with minimal impact to users :D

**Comment by hrishin** [comment]
> But I think adding the container names to the statuses is the most future proof solution - that way we can make changes like this later with minimal impact to users :D

Agreed!
