### ISSUE TITLE
params should support valueFrom

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#1197]
All `params` value fields (e.g. pipelinerun, taskrun, pipelineresource) should support valueFrom similar to container env support -- see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#envvar-v1-core and https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#envvarsource-v1-core

To start with we should support `configMapKeyRef` and `secretKeyRef` to avoid having to add extra fields like `secrets` to some of our PipelineResources and to let us parameterize PipelineResources from a PipelineRun.

**Comment by bobcatfish** [comment]
Sounds reasonable to me! @skaegi any chance you could provide an example of what this syntax would look like?

**Comment by skaegi** [comment]
Yes and I'm also signing up for doing this.

**Comment by fraenkel** [comment]
I started to look at this closer. The question to answer is how the data should be reflected back.
If one uses a Value, its just as its done today.
1. If we support a valueFrom, should it be an envVar or volume?
1. We can't verify the type unless we pull the value which seems odd.
1. The current Secrets can be deprecated and replaced with Secrets via `valueFrom` hence the question above regarding env vars vs volumes.
1. I am also assuming we wouldn't carry over the optional behavior and just fail if set.

**Comment by skaegi** [comment]
We might also want to figure out how to support "fieldref" https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#envvarsource-v1-core

I've had a couple of cases where I wanted the metadata.name to be injected via param

**Comment by skaegi** [comment]
I think in retrospect this might be a mis-feature. I've yet to have a case where I can't get at the data I need every bit as cleanly in an individual step using `env` or by 'volume/volumeMount' and a param for reference name.

**Comment by skaegi** [comment]
Ok. So my statement above still holds so closing.

**Comment by hWorblehat** [comment]
> I've yet to have a case where I can't get at the data I need every bit as cleanly in an individual step using env or by 'volume/volumeMount' and a param for reference name

The use case would be reusing existing task definitions that may only be setup to accept string params. Altering the task definition may not be a desirable approach, particularly if using OCI bundles.

For instance, I would like to use the [githu-app-token](https://github.com/tektoncd/catalog/tree/main/task/github-app-token/0.2) from the catalog as an OCI bundle, but I'd rather not put my installation ID in the pipeline run definition (associated with my source code). Since the application ID will be the same for every repository I build (as they're all from one organization), it would be really helpful if I could put it in a ConfigMap on my build cluster and just reference that from the PipelineRun.

Is that a fair use case, or am I missing an obvious alternative way of doing things?
