### ISSUE TITLE
Error not help

### ISSUE THREAD

**Issue by daixiang0** [tektoncd/pipeline#1241]
# Expected Behavior

Print **true** error.

# Actual Behavior

Print helpless info.

# Steps to Reproduce the Problem

1. Use below content as `Dockerfile`
```
From CentOS
```
2. Run build task
3. view log
```
kubectl logs build-push-run-pod-b2dbef step-build-and-push 
INFO[0000] Downloading base image CentOS                
error building image: getting stage builder for stage 0: could not parse reference
```

# Additional Info
If build with docker, it print really useful info
```
docker build .
Sending build context to Docker daemon  94.21kB
Step 1/1 : From CentOS
invalid reference format: repository name must be lowercase
```

**Comment by vdemeester** [comment]
@daixiang0 Thanks for the issue. Few things though:
- First a question: which `build` task did you use ? (aka is it using `buildah`, `kaniko`, `buildkit`, …)
- The error is from the command(s) running inside the container, thus `tektoncd/pipeline` doesn't have anything to do with it. Depending on the answer of the first point, you may want to create an issue on the related repository.
- The error is not that `helpless`, it's just *less* detailed than the one `docker` says : one says "I can't parse the reference" (aka the image reference format is wrong), the other say "invalid referenc format: repository name must be lowercase" (aka the image reference format is wrong, and how it is wrong).

Anyway, the issue is not related to `tektoncd/pipeline` itself, so I'm gonna go ahead and close ; but feel free to continue the discussion here if you feel I am wrong about it :wink: 

/close
