### ISSUE TITLE
Example request: Fluxcd example?

### ISSUE THREAD

**Issue by StevenACoffman** [tektoncd/pipeline#1259]
So this is probably the wrong place, but I'm not sure to where's a better place to ask. Is there an example combining both tekton pipelines and [fluxcd](https://github.com/fluxcd/flux) for gitops? 

Flux is most useful when used as a deployment tool at the end of a Continuous Delivery pipeline (like Tekton!!!) . Flux will make sure that your new container images and config changes are propagated to the cluster.

[Flux](https://github.com/fluxcd/flux) is really three things, which are munged together for those historical reasons we're always hearing about.
1. something that applies kubernetes manifests in git to a cluster, with some embellishments (like being able to ignore resources)
2. something which automates the update of image refs in manifests, with an API and command-line tooling
3. an image metadata database which you can query

I would ideally like to have a github pull request trigger a tekton pipeline which will build an image, and push it to a docker registry, and then have flux update my manifest image refs in git, and apply them to a kubernetes cluster. However, I could avoid polling a docker registry if a tekton pipeline were to use the flux api or command line tooling to update the manifest image refs.. 

Is that something that someone has already got working?

**Comment by sbwsg** [comment]
This was the first I'd heard of Flux, so thanks for the heads-up. I'm not aware of anyone already getting these two tools running together but I don't see anything immediately problematic in the description of how Flux operates.

Running specific containers and command line tools as part of a Tekton Task is eminently doable - in fact it's how they fundamentally work. See the `steps` field in the Task spec here: https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#syntax

Calling an API is likewise easy to do given the right Secrets and container / CLI tools to make the requests.

I'm going to close this issue since it's not really an issue with Tekton Pipelines per se and instead suggest that you join us on Slack to try and find people interested in a similar use case to your own: https://github.com/tektoncd/community/blob/master/contact.md#slack

**Comment by sbwsg** [comment]
Chatted with @bobcatfish about this a bit more who thought this would be an excellent opportunity to develop a [Catalog entry](https://github.com/tektoncd/catalog) that shows how to tie the two systems together.  I'm going to reopen this issue for anyone who is interested in working on this further!

**Comment by medkbadri** [comment]
Hi @sbwsg ,

I'm new to tekton, I think this issue is a good opportunity to start contributing,
Can I work on it?

Thanks :)

**Comment by sbwsg** [comment]
sure thing, have at it @medkbadri !

**Comment by dibyom** [comment]
@medkbadri are you still working on (or planning to work on) this issue?

**Comment by medkbadri** [comment]
@dibyom 
Hey, I will update asap (already working with tetkton and flux combined in a project for my company)
will just clean files

**Comment by StevenACoffman** [comment]
@medkbadri I don't suppose you have the unclean files lying around anywhere, do you?

**Comment by antonioberben** [comment]
Also interested on this. How is the progress going? Can I help? @medkbadri

**Comment by eddycharly** [comment]
Tekton can build and publish images, Flux should be able to detect the new images and update the cluster accordingly.

They should operate quite separately, is there something needed at all ?
