### ISSUE TITLE
Create git output that updates git

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1280]
# Expected Behavior

As discussed in #1076, if a git PipelineResource is used as an output, this should cause a change in the outside world, i.e. for git the most appropriate action would be to create a new git commit. And in #1279 we want to make PipelineResoruces immutable, i.e. using a resource as a output would create a new PipelineResource.

This would mean that any Task that has a git PipelineResource output should:

1. Create a new PipelineResource instance
2. Create a commit in the backing git repo (it would have to have permission to push to that repo)

# Actual Behavior

At the moment a git PipelineResource basically acts like a PVC only when used as an output (i.e. a way to share files). In #1109 we'll remove that functionality.

# Additional Info

Blocked on design decisions in #1279

**Comment by sbwsg** [comment]
The pipeline resources revamp described by #1673 proposes a solution to this issue by allowing customisation of a resource's behaviour when in rw/create mode. So, for example, the catalog's hypothetical Git resource could include an RW mode that `git push`es back to the remote repo, writes out the SHA that was pushed, and allows other tasks in a pipeline to rely on those resources.

I'm going to link to this from that epic so that we can track support of this feature as part of that work.
