### ISSUE TITLE
Design to keep PullRequest PipelineResource in sync with reality

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#1286]
# Expected Behavior

If a Task uses a PullRequest Pipeline resource, as the Task progresses, if comments are added (or other changes represented in the filesystem) to the Pull Request, it should be possible:

- For the executing Task to see these changes <-- this is kind of a stretch goal really
- For the executing Task to use the PullRequest resource as an output and make _additive_ changes to the PullRequest

# Actual Behavior

When a Task is executing, the representation on the file system of the pull request is _not_ updated. Even worse, the side effect is that when the PullRequestResource is used as an output, the data is treated as the source of truth and so any changes made between when the Task started and when it completed can be lost (e.g. comments made in the meantime will be deleted!!!)

# Steps to Reproduce the Problem

1. Create a Task that uses [a PullRequest Resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource) as an output, e.g.:
  a. Task could sleep for a minute or something (to give you time for step 3)
  b. Task could also add a comment to the output (i.e. write to /workspace/<resource>/comments/<comment>)
2. Execute the Task, providing an existing PR as input
3. Add a comment to the PR manually while the Task executes!
4. After the task finishes, observe that the PR has the comment added by the Task, but the one you added manually has vanished :(

# Additional Info

We should at _least_ make it so changes are additive, but also we could be ambitious and do something really cool e.g. create our own fs? (@dlorenc had some cool ideas here)

**Comment by bobcatfish** [comment]
One way to work around this (reduce the risk) would be to use this with a Notification type (#49 )

**Comment by bobcatfish** [comment]
Also: for our beta release, maybe more realistic to view PR outputs as additive only.

**Comment by dibyom** [comment]
might be useful: https://developer.github.com/v4/mutation/

**Comment by wlynch** [comment]
I don't think notification types would solve this problem. The race condition exists even in that case, since a new comment could come in from when the PR is initialized on disk.

I think what we want here is a comment manifest. This would let us detect whether or not a comment was explicitly deleted, or just one we don't know about yet.

e.g. When we download the pull request resource, also create a file called `/workspace/<resource>/comments/MANIFEST` containing the comments pulled in the download:

```
1.json
2.json
```

When we upload the PR, if we see that 2.json is missing from the local filesystem, we know this was a deletion from the Task because it was originally listed in the manifest. If we see that 3.json is missing from the local filesystem, we shouldn't make any modifications to it because the task was not aware of it when the PR resource was initialized since it was not in the manifest.
