### ISSUE TITLE
Proposal: Add a default "image" for script mode

### ISSUE THREAD

**Issue by dlorenc** [tektoncd/pipeline#1676]
This would allow users to simplify yaml even further with script mode. Right now we require them to specify an image, but Tekton could default to something reasonable.

**Comment by ImJasonH** [comment]
Questions we'd need to answer:
- what shells or scripting environments should be included?
- if platform providers can change the default image, what tools (at what versions) must be included to be considered compliant?
- what's the base OS we should use by default and what traits of it should we require of other non-default platform provided overrides?
- what's the versioning story for upgrading the version of whatever tools are available in the image?

**Comment by bobcatfish** [comment]
Marking this for triage to get a sense from other OWNERS if we want this or not

**Comment by ImJasonH** [comment]
This sounds tempting, but the questions in https://github.com/tektoncd/pipeline/issues/1676#issuecomment-561627587 (and likely more we'd uncover) make me think it's not worth jumping in to. Allowing operators or providers to configure their own defaults might also harm portability (`script` on platform A works because its default script image has `ls` with some flag, but breaks on platform B because its `ls` doesn't support that flag or something)

So ultimately I'm mildly -1 on it.

**Comment by sbwsg** [comment]
/close

Given the open questions above, and a general feeling that we'd need to provide lots of tools baked in to the image which we can't really predict in advance, I'm going to close this for now unless a really strong use case rears its head in future.
