### ISSUE TITLE
Cannot update Task with `outputImageDir`

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#1717]
# Expected Behavior
An old version of a Task includes `outputImageDir`, which is not supported by Tekton anymore.
It should be possible to update the task with a new version that does not include `outputImageDir`.

# Actual Behavior
Cannot update the Task:
```
for: "tekton/publish.yaml": Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming old object: json: unknown field "outputImageDir"
```

# Steps to Reproduce the Problem

1. On an old version of Tekton v0.8.0, create a Task that uses with `outputImageDir`
2. Upgrade Tekton to v0.9.0 
3. Try to update the Task 

# Additional Info
Support for `outputImageDir` has been dropped in https://github.com/tektoncd/pipeline/pull/1467. We skipped the usual deprecation cycle - I updated now v0.9.0 release notes to include a note that `outputImageDir` has been removed.

We should make a v0.9.2 that provides a valid upgrade path, or else document that old Tasks will have to be deleted and recreated if they use `outputImageDir`.

**Comment by bobcatfish** [comment]
@afrittoli I moved this to the 0.10 milestone since 0.9.2 happened - or should we make a 0.9.3 release?

**Comment by vdemeester** [comment]
@afrittoli given the new timeline for 0.10 we may want to do a 0.9.3 if the fix did not get in yet

**Comment by afrittoli** [comment]
Do we need to bring the field back or is it enough to tweak validation to accept it and then ignore it?

**Comment by rakhbari** [comment]
Just FYI... I just hit this issue while attempting to apply the latest 0.3.0 dashboard release YAML.
👍  for @afrittoli 's suggestion to bring the field back & just ignore it for now until this can be resolved. As of right now I'm not entirely sure if my attempt to upgrade to latest dashboard release YAML worked or not because of this error.

**Comment by bobcatfish** [comment]
After discussing this a bit with @sbwsg @dibyom @vdemeester we're not sure if it's worth making the 0.9.3 release at this point since our 0.10 release is in ~2 weeks. If we do the 0.9.3 release, folks would have to migrate to it in order to get this field back, then we'd be asking them to switch to 0.10 almost immediately.

For your issue with the dashboard @rakhbari I _think_ the dashboard project would also have to migrate to 0.9.3 in order for it to help you - and then they'd probably migrate to 0.10 right after that so I'm not sure it's worth it :S

If we'd done this 27 days ago it would have made more sense 🙇‍♀  I'm going to close this for now but if folks feel strongly please comment/re-open.

**Comment by dibyom** [comment]
Ran into this today while doing the Triggers release :upside_down_face:
