### ISSUE TITLE
binary injection

### ISSUE THREAD

**Issue by kfox1111** [tektoncd/pipeline#1754]
I was watching the kubecon presentation and it was mentioned an init container was used to populate a volume which is mounted in containers as the entrypoint.

I've been working on an ephemeral csi driver that lets you use a container as a volume directly. Its available here:
https://github.com/kubernetes-csi/csi-driver-image-populator
No extra copies of the binary would be needed.

Could tekton be modified to support using the driver?

**Comment by ImJasonH** [comment]
Thanks for watching the talk! 😄

It's possible, but it's likely we'd still need the existing impl as a fallback for users who can't or don't want to run that driver.

Since we'll have to support any user for the time being it's probably going to be a low priority to adopt the driver. But it definitely sounds interesting and I'll look into it more.
