### ISSUE TITLE
PVC associated with pipelinerun stuck in terminating state

### ISSUE THREAD

**Issue by kvijai82** [tektoncd/pipeline#1784]
# Expected Behavior
After a pipelinerun is completed, the PVC associated with the run used to be deleted once the run completed.  This was the behavior in Tekton 0.5.2.

# Actual Behavior
After a pipelinerun is completed, the PVC associated with the run are stuck in terminating state.  Once the pods associated with the tasks are deleted the claim and PV also get deleted in Tekton 0.7+.  Is this change of behavior expected?

# Steps to Reproduce the Problem

1. Run any pipeline and check the list of PVCs.

# Additional Info

We're noticing PVCs lingering around (with pods and PipelineRuns) on OpenShift 4.2 and Tekton 0.7 and 0.8. We've seen PVCs not lingering about with Tekton 0.5.2 though, so we're trying to make sense of this.

1) should they be stuck in "Terminating", because the pod's still there?
2) is this desirable behavior?
3) Have we uncovered a bug (is anyone else seeing this)?

**Comment by guillaumebreton** [comment]
@kvijai82 I've noticed the same behaviour and cleaned up manually the pod. I'd be interested to know if this is an expected behaviour too

**Comment by vtereso** [comment]
The K8s versioning between the releases doesn't seem like it would be an issue?
v0.5.2 K8s Version: `kubernetes-1.12.6`
v0.7.0 K8s Version: `kubernetes-1.12.9`'

I'll try to take a look at the controller code.

**Comment by vtereso** [comment]
Between v0.5.2 and v0.7.0, the git record appears to show little/no change between the reconciler and the artifact packages. Does anyone have an idea what to look for?

**Comment by mnuttall** [comment]
Hi Vincent, thanks for picking this up. Some things to try: 
- Can you reproduce the problem on 0.7+ ?
- If so does the problem go away under 0.5.2 as per the description?
- Is CleanupArtifactStorage() in https://github.com/tektoncd/pipeline/blame/master/pkg/artifacts/artifacts_storage.go behaving as expected? Most of the code in there has been stable since https://github.com/tektoncd/pipeline/commit/3832251a54b5684514db3688cb7efb6c14e9c632 which went into 0.4, but it still might be worth instrumenting that method and checking it's working as expected. 
- Re-reading https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection raises a few questions: if you can reproduce the problem, do you see `Finalizers:      [kubernetes.io/pv-protection]` on the volumes? And what `Reclaim Policy` is being picked up by the pvcs? I was a bit surprised to see that we don't set a Reclaim Policy, so we're getting environmental defaults.

**Comment by vtereso** [comment]
I tried to use v0.5.2 as a baseline, but the Tekton controller failed to list ClusterTask during initialization where the controller never processes `PipelineRun`s.

I was able to reproduce the issue on v0.7.0+ (specifically `v0.7.0` and `v0.8.0`). The PVC and PV have `kubernetes.io/pvc-protection` and `kubernetes.io/pv-protection`as their corresponding finalizers.

**Comment by vtereso** [comment]
I didn't find an issue with deletion (https://github.com/tektoncd/pipeline/blob/v0.7.0/pkg/reconciler/pipelinerun/pipelinerun.go#L151) within the logs of the above.

**Comment by vtereso** [comment]
Using D4D, I installed v0.5.2 Pipeline and ran the corresponding example as above, but was also getting the PVC stuck in terminating state. This seems to have always been the case? I will add this to the community call agenda.

**Comment by vtereso** [comment]
The documentation has been updated: https://github.com/tektoncd/pipeline/commit/11ca9e615ad21cf8a38af304ce111a37aaf9a7a0.  Should this issue stay open?
