### ISSUE TITLE
Measure taskRun/pipelineRun aggregate by task/pipeline template

### ISSUE THREAD

**Issue by cccfeng** [tektoncd/pipeline#1786]
# Expected Behavior
From v0.8.0, Tekton Pipeline supports the Metrics feature. We can't wait to deploy the prometheus server and grafana dashboard service to make statistics on the operation of the tekton pipeline. 

**We want to query pipeline metrics quickly and stably always.** 

# Actual Behavior
With the increase in the number of historical taskrun/pipelineruns, we find that the `tekton-pipelines-controller.tekton-pipelines:9090/metrics`  is getting slower and slower, and prometheus queries sometimes timeout.

Aggregation in the dimension of task / pipeline is sufficient, instead of detailed data for each taskrun / pipelinerun which should be recorded in somewhere like [Result Metadata Api Service](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit#)

# Steps to Reproduce the Problem

1.  Deploy tektoncd / pipeline of version no less than v0.8.0.
2. Taskruns / pipelineruns with different names (online services will introduce an uuid as isolation) are continuously submitted to run and released after they finish.
3. `curl -s tekton-pipelines-controller.tekton-pipelines:9090/metrics` , you will find a large number of tekton_pipelinerun_duration_seconds_bucket and tekton_pipelinerun_taskrun_duration_seconds_bucket indicators.  The metrics interface will slow linearly over time.

# Additional Info

-  In prometheus now , the P50 / P90 time of pipelinerun 
`
histogram_quantile(0.5, sum(tekton_pipelinerun_duration_seconds_bucket{job="tektoncd_metrics",status="success"}) 
by (le,pipeline))
`
or average time
`
avg(tekton_pipelinerun_duration_seconds_sum{job="tektoncd_metrics",status="success"} / tekton_pipelinerun_duration_seconds_count{job="tektoncd_metrics",status="success"}) by (pipeline)
`
will slow down as the amount of data increases.

- If the taskrun / pipelinerun tag is removed, we can use
`
histogram_quantile(0.5, 
  sum(rate(tekton_pipelinerun_duration_seconds_bucket{job="tektoncd_metrics",status="success"}[10m])) by (le,pipeline)
) 
`
which keep query efficiency forever.

**Comment by ImJasonH** [comment]
cc @hrishin 

/area metrics
/kind feature

**Comment by hrishin** [comment]
Hi @cccfeng 

Thank you for opening this issue and apologize for not able to merge existing PR.
To summarize the PR discussion,
The current state of metrics could quickly overload metrics aggregator systems with the volume of metrics data. Thus a possible solution is to aggregate the `PipelineRun/TaskRun` metrics instead of maintaining all `Runs` history.
However, these metrics could be consumed by existing users; Hence it may not be possible to deprecate the detailed metrics right away.

So a possible solution is to produce either of aggregate or detailed metrics depends on [observability configuration](https://github.com/tektoncd/pipeline/blob/master/config/config-observability.yaml) as suggested by @vdemeester.

**Comment by cccfeng** [comment]
Never mind. It's really better to support different uses through configuration items and it needs to be designed. I'll turn off this issue and PR first.
