### ISSUE TITLE
Deployed pod is not updated after pipeline is re-built in Tutorial, while the deployed pod is kept on running

### ISSUE THREAD

**Issue by xiaojias** [tektoncd/pipeline#1794]
# Expected Behavior
In tutorial, while the source code is updated, the deployed pod should be updated accordingly after Pipeline re-runs, even though the deployed pod keeps on running.

# Actual Behavior
The image for the deployed pod is not updated to the latest.

# Steps to Reproduce the Problem
In Tutorial for leeroy-web Pipeline:
1. Run the tutorial, leeroy-web* pod is created and working;

2. Update source code to change the message in web.go;

3. Delete all Tekton elements, e.g tasks, pipeline, resources, etc. And keep leeroy-web deployment (and leeroy-web* pod) RUNNING without any modification;

4. Apply the PipelineRun, tasks, resources, etc again;

5. The logs for leeroy-web* pod is still OLD one, not the updated message.

# Additional Info
It is indicated that the image for the pod is not re-pull from Docker repository after the Pipeline is re-applied.

**Comment by vdemeester** [comment]
I think this is because the image (resource) doesn't change, hence the image reference doesn't change either, and so `kubectl apply` command doesn't change anything, making kubernetes not re-schedule a new pod. We need to enhance the tutorial for this I think. 

/kind documentation
/kind enhancement
