### ISSUE TITLE
images.caching.internal.knative.dev CRD

### ISSUE THREAD

**Issue by poy** [tektoncd/pipeline#1803]
# Expected Behavior
Applying the Tekton release only adds Tekton CRDs.

# Actual Behavior
Apply the release adds a knative.dev CRD: `images.caching.internal.knative.dev`. 

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
I don't know a TON about the `images.caching.internal.knative.dev` concept, but my understanding is its an idea from Knative Serving to use DaeomSets to cache images and speed stuff up.

Does Tekton really need to duplicate this CRD from Knative? Its not really *required* by anything in Tekton is it?

**Comment by bobcatfish** [comment]
I don't know the answer here either!

Quick glance at knative serving, it looks like you have to actually DO something with this CRD for it to be useful (e.g. https://github.com/knative/serving/blob/1c782d95c918f3b8b410fbac68849c494fd74b0c/pkg/reconciler/revision/resources/imagecache.go#L29-L55) 

Looking at our code it looks like we instantiate the client https://github.com/tektoncd/pipeline/blob/7962731ab7c50ebc6ca465190db9e1191ffd7fc2/pkg/reconciler/reconciler.go#L42 but don't do anything else with it.

My suggestion for a next step here would be to try removing it and see what happens.

(maybe @mattmoor will be generous and just tell us if we need it 🙏 )

**Comment by mattmoor** [comment]
Serving just creates them too.  These are a hint to integrators that these images should be cached.  You can run a controller to key off of them, or do nothing (nothing is a valid caching strategy).

The DaemonSet approach is one used here github.com/mattmoor/warm-image, but that's not scalable enough for us to bundle it with Serving.
Another that we've talked to Azure a bit about is integrating with their "Teleport" technology where images are mounted into containerd instead of pulled (but which images are indexed and where?).

I think that's public and that I know of, at least.

**Comment by chasewalden** [comment]
This might cause a possible bug as well. It appears that "uninstalling" Tekton from a cluster with an existing Knative installation will cause `images.caching.internal.knative.dev` to be removed as well. Required just reinstalling the knative serving crds bundle again, but it was a strange issue to diagnose.

**Comment by jcatana** [comment]
Could the knative CRD you install be renamed, an external dependency, or removed? Seems problematic to have both tekton and knative installed in the same cluster with tekton doing this.

**Comment by bobcatfish** [comment]
I think this was removed in https://github.com/tektoncd/pipeline/pull/3850
