### ISSUE TITLE
Is there some cached snapshot image?

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#1809]
From this [example](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs)

This example works, but I when I try to use custom github repo I end up with:
`error building image: error building stage: lstat /workspace/docker-source/go.sum: no such file or directory`

Even the file is there?

Dockerfile:
```
FROM golang:1.12
WORKDIR /src/server
COPY go.mod go.sum ./
RUN go mod download
COPY . ./

RUN go build -o ./app -v ./src/server
```

Docker build works, but not when using it with Tekton. 
```
docker run -it tektonbuild bash
root@00260a237688:/src/server# ls
Dockerfile  README.md  app  go.mod  go.sum  pipres_gcr.yaml  pipres_github.yaml  sa.json  sa.yaml  src  task_build.yaml  taskrun_build.yaml
```

The full test project:
https://github.com/JCzz/tektonbuild

It is as there is some kind of snapshot image.

**Comment by vdemeester** [comment]
I am not sure what you mean by "some kind of snapshot image."…
Usually, to debug those things, I am adding a previous step similar to the one that fails but instead of doing what it does (here a `kaniko …`), I do a `bash -c "pwd; ls -la"` and other things to see if the current directory and all are the correct one. Looking at you project, nothing jumps on why it would fail though…

/kind question

**Comment by JCzz** [comment]
Thanks @vdemeester I got it working
