### ISSUE TITLE
Two quick questions: Github Webhook tutorial & how to rerun pipelines and TaskRuns?

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#1832]
1. Do you have any examples showing how to use Github WebHooks to start the/a pipelinerun for CI/CD flow?

2. I am looking at this tutorial:
https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#task-inputs-and-outputs
but how do you restart taskruns and pipelineruns - it would be nice to be able do something like:
`tkn pipelinerun <already kubectl apply -f file.yaml>`
How do you test and re-run taskrun/pipelinerun - do you `kubectl apply/delete -f filename`

**Comment by a-roberts** [comment]
Hey @JCzz, if you're looking for UIs there's our Tekton Webhooks Extension that's built for 1., see https://github.com/tektoncd/experimental/tree/master/webhooks-extension - you could also use Jenkins X. With the webhooks extension we're using Tekton Triggers the EventListener component, backed by an Ingress or Route as the thing that is pinged from GitHub.

For 2. you can use https://github.com/tektoncd/dashboard (we have rerun that basically copies an existing PipelineRun spec and kicks it off again)

@vdemeester for tkn and general rerun guidance otherwise 😸

**Comment by chmouel** [comment]
For `tkn` you can just use the -L option to rerun the last task or pipeline


```shell
chmouel@TheBatman 🦇 ~% tkn task start --help|grep last
                                                 BOOTSTRAP
  -L, --last                     re-run the task using last taskrun values
chmouel@TheBatman 🦇 ~% tkn pipeline start --help|grep last
                                                 BOOTSTRAP
  -L, --last                          re-run the pipeline using last
pipelinerun values
chmouel@TheBatman 🦇 ~%
                                                 BOOTSTRAP
```

**Comment by JCzz** [comment]
Thanks @a-roberts and @chmouel
