### ISSUE TITLE
git-init ssh symlink is failing

### ISSUE THREAD

**Issue by chmouel** [tektoncd/pipeline#1843]
# Expected Behavior

Create the SSH file properly

# Actual Behavior

git-init step is failing when trying to symlink `/root/.ssh` to `/tekton/home/.ssh`

```
[git-source-tektoncd-pipeline-git-qlcdk] {"level":"warn","ts":1578650329.4586325,"logger":"fallback-logger","caller":"git/git.go:149","msg":"Unexpected error: creating symlink: symlink /tekton/home/.ssh /root/.ssh: file exists"}
```
# Steps to Reproduce the Problem

I am not so sure yet how to reproduce this but the image has definitively no /root/.ssh already and has no volume mount on /root/

# Additional Info

Just capturing it before I forget and will investigate a bit further and update this issue later on..

/kind bug

**Comment by vincent-pli** [comment]
@chmouel 
The  https://github.com/tektoncd/pipeline/blob/3ae789c25831b3240721437d6570b58097cd55d9/pkg/git/git.go#L134
is invoked twice in 
https://github.com/tektoncd/pipeline/blob/3ae789c25831b3240721437d6570b58097cd55d9/pkg/git/git.go#L57
and 
https://github.com/tektoncd/pipeline/blob/3ae789c25831b3240721437d6570b58097cd55d9/pkg/git/git.go#L114

That's why we get `file exists` in second invoke.

**Comment by ad22** [comment]
fyi, #2320 performs a refactor of the fetch+submodule fetch and combines it into a single call. Subsequently, this can be fixed w/o much change.

**Comment by sbwsg** [comment]
This issue should be resolved now that we're only making the `ensureHomeEnv` call once in `git-init`. Closing as fixed but we can reopen if the problem rears its head again.
