### ISSUE TITLE
Failed to create a taskrun

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#1979]
# Expected Behavior
Throw an exception or show an error message that states secret name or service account name is very large.
# Actual Behavior
Error message:
Missing or invalid Task default/app-builder1: translating Build to Pod: multiple volumes with same name "tekton-internal-secret-volume-XXX-south-te" 

/kind bug

**Comment by afrittoli** [comment]
Thank you for your bug report. 
The error message is also wrong, since we don't rely anymore on `Build`, it should say `translating TaskSpec to Pod` instead.  For the actual error, it would be useful if you could share the relevant Tekton resource you're using, and also which version of Tekton you're running them on.

**Comment by vincent-pli** [comment]
I think the issue is caused when mount `secret`,  the length of the `volumn` name is more than 63, so it trim, cut the different part, the remain part are same, then raise the error.

**Comment by vdemeester** [comment]
I think this can be close as #2048 got fixed
/close
