### ISSUE TITLE
Introduce Workspaces to Conditions

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/pipeline#2010]
# Expected Behavior

The conditions I write should be able to leverage the workspaces that are threaded through my pipeline.  This would allow a condition to make decisions based on files I've written out in previous tasks.

# Actual Behavior

At the moment ConditionSpec does not have support for workspaces.

**Comment by cten** [comment]
This would be great. I am trying to create Conditions for Sonar Scanning that would use the workspace of the build task. By making Sonar scan a Condition instead of a Task we can make sure all the libraries are present during scan.

**Comment by deepio-oc** [comment]
/reopen

I was moving away from PipelineResources to Workspaces since PipelineResources is alpha and may not be supported in future. I had a "Condition" which was using PipelineResource earlier and now I wanted it replaced  with workspace but realized that this is not supported. 

If PipelineResources are going to be deprecated, Conditions should support workspaces.

**Comment by bobcatfish** [comment]
Since we're [re-doing conditions and deprecating the existing CRD](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md) i think we could probably close this one - lemme know if you disagree @vdemeester @jerop  (also @jerop the TEP does mention deprecating the existing CRD but i wonder if it would make sense to make that more prominent?)

**Comment by jerop** [comment]
> also @jerop the TEP does mention deprecating the existing CRD but i wonder if it would make sense to make that more prominent?

sure, highlighted it here: https://github.com/tektoncd/community/pull/193
