### ISSUE TITLE
Caching for git resource

### ISSUE THREAD

**Issue by shiyu-dong** [tektoncd/pipeline#2021]
Hello,

According to the [Git Resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#git-resource) document, seems that a `git clone` is needed every time this resource is used.

We have monorepos with hundreds of services in each, and the commit volume is high. It will be an expensive operation to clone every time (both for load to git server and the time for git clone itself).

Does Tekton support caching the git repo and reuse it for future task runs natively? If not, is it recommended for us to host our own git cache using [Storage Resource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#storage-resource) or something similar?

Thanks,
Shiyu

/kind question

**Comment by vdemeester** [comment]
Hey @shiyu-dong, thanks for the issue.
This is a shortcoming of the current PipelineResource design, hence our redesign work (see [here](https://github.com/tektoncd/pipeline/issues/1673)) in progress. As the beta will not include PipelineResource (still usable but not *supported* per-se), we will tell the user to prefer using re-usable tasks (like the [git](https://github.com/tektoncd/catalog/pull/123) one) with `workspace` instead of using `PipelineResource`. 

We need to start documenting that better (and quicker), see https://github.com/tektoncd/pipeline/issues/1369 :angel:

**Comment by shiyu-dong** [comment]
@vdemeester Thanks for the update. I will look into the re-usable git task!
