### ISSUE TITLE
Remove "volumes" from Task

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#2058]
# Expected Behavior

`Task` authors should declare when they need files (workspaces) + block devices (#2057 ) but they should leave it to the TaskRun to provide these.

# Actual Behavior

Having `volumes` as a field in `Tasks` means that `Task` authors are dictating at `Task` authoring time what volumes will be provided to a `Task`.

# Additional Info

We should remove [Volumes from the TaskSpec](https://github.com/tektoncd/pipeline/blob/7cdd92316d781e602a05749fa8ba5c2c505ffa30/pkg/apis/pipeline/v1alpha2/task_types.go#L74-L76) before beta (if we can) to indicate it is behavior we don't want to support going forward.

We could also prevent people from using the `volumeMounts` and `volumeDevices` fields in a `step` as well but that feels like it's not the worst thing to leave in since it's not yet runtime information? Open to other thoughts tho.

**Comment by vdemeester** [comment]
I like that idea, I wonder if we should do this for `v1alpha2` directly (hence having this in 0.11) :wink:

**Comment by vdemeester** [comment]
Putting it in the milestone to make sure we discuss it quickly :angel:

**Comment by skaegi** [comment]
Apart from the block device case the only other case I can think of is volume as a task implementation detail that we don't allow customization of... but that sort of weak.

**Comment by bobcatfish** [comment]
That's a good point @kav ! Do you have a sense for whether you'd rather declare that kind of information at Task authoring time, or at runtime?

**Comment by sbwsg** [comment]
> various relatively static configuration (.netrc, repositories.yaml) from secrets into specific directories in specific task steps so tools find them seamlessly?

This is a usecase for workspaces that I've been thinking about a lot recently!  It would be cool if you could define workspaces in a TaskRun that are not mentioned at all in a Task and then Tekton would include those workspaces in the step containers as well.  Static configs from secrets are a great use case of where this could be useful.  I was thinking about it in terms of the .ssh directory but it's great to see some other examples where this might also be useful.

**Comment by bobcatfish** [comment]
Another use case maybe is sharing data between sidecars and steps, ala the docker in docker example https://github.com/tektoncd/pipeline/blob/master/examples/taskruns/dind-sidecar.yaml

**Comment by kav** [comment]
> That's a good point @kav ! Do you have a sense for whether you'd rather declare that kind of information at Task authoring time, or at runtime?

Some of it is authoring related information around configuring this task for this environment and some falls under runtime. My taskruns are generated via triggers so I could put "configuration" info there? 

Not sure that addresses step volume mount location being task side info. In essence the Task, by virtue of owning the container, is really the only one that can decide the "right" place for an ssh key or a netrc file. 

Might be worth defining some things, and apologies that I'm bringing Helm to the party so might muddle things. You all might have different terms. Taking a stab, feel free to stab back ;):

There is __static context__ which is just the fixed content authored into the task; i.e. build a container, run a jenkinsfile, run a gitlab build file.

There is __environment context__ which is all the stuff the task needs to play nice with the servers it touches, this is fixed across all runs but multiple installs of the same task could vary here. It tends to be very specific to the static context. For example repositories.yaml needs to go to in one directory if the step uses helm2 and another for helm3. Each of these environment objects is needed only by some steps based on what those steps do. I don't really mind them hanging about but I could see not wanting all steps to have helm push permissions for example. I drive all this via Secrets linked to authored volumes since it's almost all credentials. So it's a bit "half at authoring, half at install/run time". Most end up in very specifically placed file or another on a per step basis so steps can seamlessly rely on them.

There is __build context__ which would include source and run name, pr url , author, and all the stuff that varies by taskrun. Today for me this all comes through the TriggerTemplates.

I could use TaskRun config to push environment context I suppose, it feels like mount points would still need to be in the task. I like it in the Task since it corresponds to step specific info. Locality of change is the same. To take the helm case; imagine I have a Task that was using Helm 2 and I'm switching to Helm 3. Today, with secrets and volumes, I open the Task object and change the mount for the volume as well as the container image for that step and boom I'm done.

I also don't have any Pipelines or PipelineRuns; haven't needed them as yet but I suspect the same applies.

**Comment by sbwsg** [comment]
From WG it sounds like we should mark this as deprecated before we wholesale remove.  If we are going to do this then I will add a notice to the 0.11 release.

**Comment by bobcatfish** [comment]
Decided not to remove it, closing this for now, can open more issues to continue to look into volumes in future.

**Comment by lbernick** [comment]
/reopen
/assign

We want to revisit the decision not to remove volumes from Task spec before releasing our v1 api and committing to supporting it for at least a year (following our compatibility policy), especially since there's not much detail on why the decision was made not to do this for beta.

I'll look into this and either open a TEP proposing this change, or update this issue with a summary of why we don't want to do this.

**Comment by kav** [comment]
Let me know if you'd like a deeper dive on the example above. It's been a few years and I'm not working on that at the moment but happy to discuss the conceptual framework at a deeper level at the least.

**Comment by kav** [comment]
Looking at the details and the docs I think so. I might be repeating myself a bit to warm my thinking up so apologies if this is a repeat of the above. My biggest worry was maintaining a boundary between

1. The config that needs to be provided to build an app of X type
2. The config that needs to be provided to build this specific app Y that is of type X
3. The config that relates to this specific build run Z of app Y that is of type X

To dig in a bit on why the distinction above:
1. As an expert in building (go, node, helm, etc) apps I can create Tekton resources that describe how to optimally build test and publish those apps. Everyone can contribute and share best practices.
2. As someone building a Tekton pipeline I can leverage 1 and provide my organizations specific details (e.g. registry push credentials) without deeply understanding the ins and outs of 1. Workspaces
3. As someone building a Tekton pipeline I want to encode run details into my build process, track my runs in kubernetes, report on run details etc.

Workspace is potentially the interface boundary between 1 and 2 which means as a author of 1 I'd need to provide a template Workspace to a consumer for them to fill out with sensible defaults they could match for their pvcs and secrets and whatnot. Or they could override as needed if they used different names, that's probably reasonable and not an uncommon pattern in the space.

Note: It might be interesting to add a slice of "on a platform" to the above taxonomy as it sounds like that's what the factorization is about.

**Comment by lbernick** [comment]
I still think this is the right long term direction for volumes and workspaces, but there are a few [use cases](https://github.com/tektoncd/community/blob/main/teps/0112-replace-volumes-with-workspaces.md#volume-use-cases-not-currently-supported-by-workspaces) for volumes not currently being met by workspaces. We should try to address these gaps (or think more about what we want our api for volume/volumemount-like things to look like as a whole), but I think this requires a bit more thought and I don't want to rush through it just so we can remove volumes before v1. So I think volumes can stay in our v1 api, although of course I'm open to discussion here.
