### ISSUE TITLE
Support for standalone Pipelines using standalone TaskRuns

### ISSUE THREAD

**Issue by mustafaakin** [tektoncd/pipeline#2185]
Since we can now create TaskRun's without creating the respective Tasks, by specifiying taskSpec instead of taskRef, it would be great if we could use them in PipelineRuns.

It would help when you create pipelines out of the Tekton, dynamically, with another configuration language such as Jsonnet. What do you think?

**Comment by vdemeester** [comment]
@mustafaakin thanks for the issue. You should be able to do that with `PipelineRun`. You can use `PipelineSpec` to [embedded a `Pipeline` spec](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#specifying-a-pipeline), and in `Pipeline` Spec you can use `TaskSpec` (instead of `TaskRef`) to embedded a `Task` spec (looks like something is missing in the doc).

/kind question

**Comment by mustafaakin** [comment]
@vdemeester oh, good to know, I missed it! Really glad to hear that. Thanks.
