### ISSUE TITLE
The newly created pipeline shows the status of the deleted pipeline if the name of the pipeline is same

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/pipeline#2201]
# Expected Behavior
The newly created pipeline should not show the status of the deleted pipeline if the name of the pipeline is same

# Actual Behavior
The newly created pipeline shows the status of the deleted pipeline if the name of the pipeline is same

# Steps to Reproduce the Problem

1. Create a pipeline
2. Start the pipeline run using the command `tkn pipeline start`
3. Wait till the pipeline run gets completed
4. Delete the pipeline
5. Create a new pipeline with same name as the pipeline in step 1
6. List the pipeline using the command `tkn pipeline ls`

# Additional Info
Below are the command logs
```

[varadhya@localhost testing]$ kubectl apply -f script-pipeline.yaml 
pipeline.tekton.dev/pipeline-test created
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline ls
NAME            AGE             LAST RUN   STARTED   DURATION   STATUS
pipeline-test   4 seconds ago   ---        ---       ---        ---
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline start
Error: missing pipeline name
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline ls
NAME            AGE              LAST RUN   STARTED   DURATION   STATUS
pipeline-test   11 seconds ago   ---        ---       ---        ---
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline start pipeline-test 
Pipelinerun started: pipeline-test-run-2twsx

In order to track the pipelinerun progress run:
tkn pipelinerun logs pipeline-test-run-2twsx -f -n test-tekton
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline ls
NAME            AGE              LAST RUN                  STARTED         DURATION   STATUS
pipeline-test   20 seconds ago   pipeline-test-run-2twsx   2 seconds ago   ---        Running
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline ls
NAME            AGE             LAST RUN                  STARTED         DURATION    STATUS
pipeline-test   2 minutes ago   pipeline-test-run-2twsx   2 minutes ago   2 minutes   Succeeded
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline delete pipeline-test 
Are you sure you want to delete pipeline "pipeline-test" (y/n): y
Pipelines deleted: "pipeline-test"
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ kubectl apply -f script-pipeline-2.yaml 
pipeline.tekton.dev/pipeline-test created
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ 
[varadhya@localhost testing]$ tkn pipeline ls
NAME            AGE             LAST RUN                  STARTED         DURATION    STATUS
pipeline-test   3 seconds ago   pipeline-test-run-2twsx   2 minutes ago   2 minutes   Succeeded
[varadhya@localhost testing]$

**Comment by vdemeester** [comment]
Hey @VeereshAradhya, there is a few things:

- I think this could have been an issue on `tektoncd/cli` instead, as it's about the `tkn` cli — but as this is because of a design choice on `tektoncd/pipeline`, I'll let it here.
- (but) this is indeed happening by design (from the `tektoncd/cli` and `tektoncd/pipeline` point of view) : the way we can get the `Pipeline` used for a `PipelineRun` is using it's named, and it is by using the labels the pipeline controllers set on the `PipelineRun` (e.g. `tekton.dev/pipeline: dashboard-release`).

On the cli side, as of today, there is nothing we can do really to change this. On the pipeline side, we *could* add a `tekton.dev/pipeline-uuid: …` label to hold the `uuid` of the `Pipeline` used for the `PipelineRun` and thus, let the client handle the case where a `Pipeline` with the same name but a different `uuid` exists.

This is also a little bit related to the "versionning" discussions (see #1839)

> I think the main question is, is this in scope for tektoncd/pipeline or some higher level component (from Tekton or not) ? versionning could be done using different name and labels, … and managed by an higher level component, keeping the tekton api as simple (relatively speaking) as possible.

/kind design
