### ISSUE TITLE
Documentation: Security/authorization model for Tekton users in a multi-tenant cluster

### ISSUE THREAD

**Issue by jcmcken** [tektoncd/pipeline#2257]
I'm not sure this is the appropriate avenue to ask this question, but I'm wondering about Tekton and multi-tenancy.

We have some general purpose clusters with RBAC enabled and customer workloads completely namespaced, using OPA policy and some other mechanisms to prevent customers from executing privileged operations in the cluster (e.g. accessing the host, accessing other customers' workloads, etc.)

In such a set up, how does Tekton come into the picture? For example, can we deloy Tekton as a "cluster-wide service" while still maintaining namespace separation for cluster tenants? Can we prevent cluster tenants from using Tekton to escalate privileges within the cluster (e.g. use privileged Linux capabilities, run privileged containers, etc.)?

Based on the history of the project (Knative Build + kaniko for unprivileged image builds), I'm thinking Tekton does fit into this picture. But I'm looking for specifics or documentation that explains it in more depth. I took a look at the Kubernetes objects in the Tekton installation files, and I see Tekton receives some elevated privileges. But it's not particularly clear what the workflow looks like.

**Comment by sbwsg** [comment]
I think it's fair to say that support for multi-tenant scenarios is somewhat nascent in Tekton Pipelines.

We've started by creating separate roles for the Pipelines controller:
- [`tekton-pipelines-controller-cluster-access`](https://github.com/tektoncd/pipeline/blob/master/config/200-clusterrole.yaml#L15-L41) accounts for cluster-scope access that the controller currently requires.
- [`tekton-pipelines-controller-tenant-access`](https://github.com/tektoncd/pipeline/blob/master/config/200-clusterrole.yaml#L43-L59) accounts for namespace-scope access that the controller requires.

Notice that currently both of these are bound using [`ClusterRoleBindings`](https://github.com/tektoncd/pipeline/blob/master/config/201-clusterrolebinding.yaml#L15-L43).  This is intentional for backwards-compatibility with Tekton's existing behaviour.  However, in a multi-tenant scenario you could modify `tekton-pipelines-controller-tenant-access` to be a `RoleBinding` instead, assigning the role to only those namespaces where tenant CI/CD workloads live.

I think there's still a fair amount of work to be done both on the Tekton side as well as the Knative side to fully support locked down multi-tenant situations.  But to be honest I'm also not an expert on this stuff.  Help would be very much appreciated if anyone wants to tackle this.
