### ISSUE TITLE
Tekton Managed Images

### ISSUE THREAD

**Issue by josephlewis42** [tektoncd/pipeline#2380]
# Expected Behavior

When I install and use Tekton, I'd expect all images Tekton relies on to:

* Come from Tekton's GCR repositories
* Be covered by the same software license as Tekton
* Reference images by SHA256 to allow caching in Kubernetes and ensure that the images aren't tampered with

# Actual Behavior

Instead, there are two (that I've found) additional images used that are not referenced by SHA or included in Tekton. They are:

* `tianon/true:latest` (MIT licensed)
* `busybox` (GPL licensed)

# Steps to Reproduce the Problem

1. Create a Tekton TaskRun
2. Run `kubectl get pods <taskrunpods> -o json | jq '.spec.containers[] | {image:.image, pull:.imagePullPolicy}'`
3. See additional images Tekton injected that aren't coming from Tekton's repos

**Comment by vdemeester** [comment]
> # Expected Behavior
> 
> When I install and use Tekton, I'd expect all images Tekton relies on to:
> 
>     * Come from Tekton's GCR repositories
> 
>     * Be covered by the same software license as Tekton
> 
>     * Reference images by SHA256 to allow caching in Kubernetes and ensure that the images aren't tampered with

I do agree with the latest point (aka using the `digest` of the image). But I don't except all the image to come from Tekton GCR repositories, neither to be covered by the same software license. `busybox` and `tianon/true` are both images that fit our need.

We need to use `digest` for those two when we release so that it inject those image wit hdigest too.
