### ISSUE TITLE
Pipeline vs TaskRun

### ISSUE THREAD

**Issue by JCzz** [tektoncd/pipeline#2404]
Question:

What is the purpose of [TaskRun](https://tekton.dev/docs/pipelines/) when you can use Pipeline to run Tasks?

Connection between concept and implementation:
My brain got to rest by thinking; a TaksRun is for testing a(one) Task and Pipeline is for many tasks potentially waiting on each other etc. railway scenario?

But the I came across this IBM intro, that [says](https://developer.ibm.com/technologies/devops/articles/introduction-to-tekton-architecture-and-design/):
_(Under the covers, a PipelineRun creates one or more TaskRuns, each of which manages its associated Pod.)_

I get it, Tasks maps to pods running tasks in containers -  but my brain begins to hurt again if TaskRun is part of that game :-) 

This [tutorial](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md) has a TaskRun, but it is not used in the Pipeline - can you elaborate on the usage of TaskRun?

Thanks in advance

**Comment by vincent-pli** [comment]
@JCzz 
`Task` and `Pipeline` are the template,  `Pipeline` is for multiple `Task` combination.
`Taskrun` and `Pipelinerun` are one time execution for `Task` and `Pipeline`, and they will supply some runtime parameters.

So, that's means when you create `Task` or `Pipeline`, just a CR created, no pod, no container until a `Pipelinerun` or `Taskrun` which refer to them were created.

**Comment by bobcatfish** [comment]
@JCzz sometimes we go back and forth on whether the TaskRun concept really is useful to users or not, since you can always have a Pipeline with just one Task and you get the same thing. It's definitely useful as an implementation detail of PipelineRuns - but even in our own dogfooding we use TaskRuns fairly often when we just want to run one Task so it seems useful.

I'm gonna close this but please reopen if this doesn't adequately answer your question @JCzz !
