### ISSUE TITLE
git-init depth is not working as expected

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2436]
# Expected Behavior

`git-init` (gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest) from https://github.com/tektoncd/catalog/blob/v1beta1/git/git-clone.yaml depth parameter works as expected.

# Actual Behavior

`git-init` is not working as expected, always set depth to 1.

# Steps to Reproduce the Problem

```
/ko-app/git-init -url https://github.com/example/test-repo.git -revision master -path /workspace/output/ -sslVerify true -submodules true -depth 100
```
```
# git rev-list --count master
1
```
(There are more that 1 commit in this repo)

No matter how many commits there are in the test-repo `git-init` always checkout with 1 commit.

For comparison, regular git clone command:
```
git clone git@github.com:example/test-repo.git --depth 10
```
```
$ git rev-list --count master
10
```
In this case depth parameter work fine.

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.8.0
Pipeline version: v0.11.1
```

**Comment by sbwsg** [comment]
Thanks for the issue!  Two thoughts:

1. The reason your git-init code snippet doesn't work is because your boolean flags (-sslVerify, -submodules) **must** use an `=` to set their value.  If they do not then golang's flag package ignores them as well as any flags after them.  So since you have `-sslVerify true -submodules true -depth 100` and the `-sslVerify` flag doesn't have the `=` then `-depth` is ignored.

2. We very recently fixed this issue in the `git-clone` Task in the catalog.  See [the relevant lines](https://github.com/tektoncd/catalog/blob/v1beta1/git/git-clone.yaml#L69-L71) from the current version in the `v1beta1` branch.

I'm going to close this issue but if this didn't answer the question or you have further questions feel free to re-open.  Thanks!

**Comment by r0bj** [comment]
Thanks @sbwsg, use `=` fixed it for me.
