### ISSUE TITLE
Add global stepTemplate config

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/pipeline#2600]
Currently a global `podTemplate` can be specified in the default Tekton configuration (`config-defaults` configmap). Similar global config would be desirable for `stepTemplate` to apply to all taskruns. The use-case is to be able to for example constrain the amount of cpu and mem resources that taskrun containers can consume.

**Comment by ImJasonH** [comment]
> The use-case is to be able to for example constrain the amount of cpu and mem resources that taskrun containers can consume.

Isn't this something you can accomplish with [limit ranges](https://kubernetes.io/docs/concepts/policy/limit-range/) ?

**Comment by siamaksade** [comment]
Limit range would apply to everything in the namespace, including the application pods. TaskRun pods are terminating pods so admin might allow higher limits for those pods since they stop after a usually short while, in contrast to application pods are non-terminating and keep running.

**Comment by ImJasonH** [comment]
That makes sense. `stepTemplate` doesn't let you enforce any kind of maximum/minimum resource request, just a _default_.

Another option would be to use [OPA's Gatekeeper](https://github.com/open-policy-agent/gatekeeper) to enforce a policy that TaskRuns run as part of a PipelineRun have a default/max resource request, or maybe even max total resource usage across the run.

**Comment by danielhelfand** [comment]
One thing I am noticing here that seems related is there are no docs on `stepTemplates` as far as what properties are available that could've helped inform this a little better. Most examples just include specifying environment variables. Beyond just resource constraints, there could be other use cases that may make sense here, but it's hard to tell since not a lot of info is available.
