### ISSUE TITLE
Proposal : separate conversion webhook

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/pipeline#2696]
In the context of multi tenancy, it would be handy to separate the conversion webhook from the single webhook we have now.

This is because CRDs and conversion webhook should be deployed once per cluster, and each tenant should have its own dedicated contoller and webhook (for validating resources/configmaps and defaulting).

The conversion webhook would only need to take care of conversion and validating the configmaps it uses.

Currently, such a setup is not possible.
At least we need to provide a defaults config map to have the conversion webhook even if it's not needed for the conversion itself.
If we deploy the webhook multiple times each webhook would fight other ones to set the conversion webhook on the CRDs.

It seems to me that separating the conversion webhook is a natural approach, what do you think ?
Is there another solution to make multi tenancy work that i missed ?

**Comment by eddycharly** [comment]
/cc @vdemeester @afrittoli 

Does it make sense to you ? Shall I open a PR ?

**Comment by vdemeester** [comment]
Overall I think that make sense. As we are using the [`knative/pkg`](https://github.com/knative/pkg) code there, I am going to invoke @mattmoor to have his opinion on this (and how knative handle that too :angel: )

**Comment by mattmoor** [comment]
> This is because CRDs and conversion webhook should be deployed once per cluster, and each tenant should have its own dedicated contoller and webhook (for validating resources/configmaps and defaulting).

This isn't really tenable right now because of how K8s webhooks work.  They are cluster-scoped resources, which in the best of cases can apply to a subset of namespaces via namespace selector.  So two problems:
1. There isn't any good way to scope a tenant's webhook configuration to just their namespace (it'd have to get called and manually filter).
2. The webhooks self-register, and allowing tenants to due this is an escalation vector (we've talked about putting this into an operator, but it has to live somewhere)

So I think my expectation would be that the webhooks (at least) are shared across tenants.


I would love to better understand the isolation you are after with per-tenant controllers and webhooks?  Is it QoS?  Security? Chargeback?

**Comment by eddycharly** [comment]
@mattmoor thanks for your feedback.

The main point is kind of for security, this would allow isolating each team in its own namespace.

The conversion webhook is a bit different than other webhooks in the sense that it is part of the CRD definition, that's why i thought it would make sense to have it separated from other webhooks.

**Comment by mattmoor** [comment]
My point is that if you peel the onion a little bit the implications for the webhook are really not that different.  TBH, the webhook scares me a lot more than the CRD details.

Would it make sense to set up a quick call?  sometimes issues are a hard medium for discussing :D

**Comment by eddycharly** [comment]
@mattmoor sure, let's discuss this tomorrow, on slack or something else, up to you

**Comment by mattmoor** [comment]
Sure, hit me on tekton slack.  I'm usually online after about 8am PST

**Comment by chhsia0** [comment]
We're hitting the same multi-tenancy problem at D2iQ. I was wondering that if there's no consensus on whether webhook services should be separated, is it possible to add a flag to launch the webhook in "conversion-only" mode, as an exercise to see how it could work in a multi-tenant setting?
