### ISSUE TITLE
Tekton and GitOps

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2758]
Hi,
Could anyone let me know whether GitOps can be enabled using Tekton?
Basically, is the below possible using Tekton. 

 "If I have my source code in github and when I make a github commit or PR , I want my Tekton pipeline to kickoff automatically which will perform my application build, create image , push to docker repo. and deploys the image in Kubernetes pod".

If above is possible, could anyone provide me information on how it can be done?

Thanks in advance!

**Comment by eddycharly** [comment]
Not out of the box.

Tekton pipelines is for running pipelines, what a pipeline does is up to you. You can create a pipeline to checkout your code, build your image, push it in a docker repo and deploy a pod if you want.

Tekton triggers can trigger your pipelines when a commit is pushed or a pr is opened in your code repository.

You can use both tools to create a sort of continuous integration/delivery/deployment solution.

GitOps is something else, you describe the full state of your cluster in a git repository and the cluster syncs with the repository continuously. When the state of the state is not the same as the state declared in the repository, the cluster evolves to new state.

With GitOps you don’t deploy anything yourself in the cluster, you just push changes to a git repository and the cluster reacts to these changes, the git repository is the only source of truth.

**Comment by 2020testuser** [comment]
eddycharly - Thanks ! This helps. Could you please clarify on the below?
>`Tekton triggers can trigger your pipelines when a commit is pushed or a pr is opened in your code repository.`
Does tekton triggers use Github webhooks to trigger the pipelines? 

>`You can use both tools to create a sort of continuous integration/delivery/deployment solution.`
Could you please clarify how by using Tekton pipeline (without triggers), I can achieve continuous integration/deployment solution? Is this achieved using Tekton and argoCD together? 

>`GitOps is something else, you describe the full state of your cluster in a git repository and the cluster syncs with the repository continuously. `
I'm new to GitOps. Could you let me know what components can be used with Tekton to enable GitOps? I came across JenkinsX which can enable GitOps. I want to know whether  Tekton can enable GitOps? If so, how this can be achieved?

Thanks!

**Comment by eddycharly** [comment]
> Does tekton triggers use Github webhooks to trigger the pipelines?

Yes

> Could you please clarify how by using Tekton pipeline (without triggers), I can achieve continuous integration/deployment solution? Is this achieved using Tekton and argoCD together?

You will need Tekton triggers to automate pipeline execution on git events (push or pr).

> I'm new to GitOps. Could you let me know what components can be used with Tekton to enable GitOps ?

Yeah i believe jenkinsx has something close to gitops, ArgoCD or Flux are gitops solutions too.
You could use Tekton for continuous integration/delivery and Flux or ArgoCD for the deployment part.

I never used Flux or ArgoCD myself, i developed an in-house solution for several reasons. GitOps proves to be challenging in some areas, managing passwords and sensitive data is not easy to store safely in a git repository for example.

As git is the only source of truth, deploying something boils down to pushing some changes on a git repo. Because of that GitOps is often implemented with several components, one component is responsible of updating the cluster when the git repository changes, another component tracks available artifacts and pushes changes to the git repo when new versions are published.

Generally, GitOps approach does not care much about the source code of an application, it only needs to know when a new version of the application is published.

**Comment by 2020testuser** [comment]
@eddycharly - Thanks Much! 
So, to confirm... Is the below correct? 

Tekton is for enabling continuous integration/continuous delivery  and GitOops is for continuous integration/deployment. For continuous integration/deployment, here are the options I have.
1. Tekton plus Flux or ArgoCD
2. JenkinsX with Tekton 
3. Weaveworks 
4. Flux
5. Others (if any)

It would be good if we have all these components pros/cons (or challenges) in one place. 
Thanks again!

**Comment by eddycharly** [comment]
> GitOops is for continuous integration/deployment

GitOps is not related to continuous integration
GitOps can be used to implement continuous deployment but not necessarily, you can stick with manual deployment and have a GitOps approach. As long as you automate the pushes to the git repo when new artifacts are available it becomes continuous deployment.

There are probably a lot of GitOps tools comparison available, last time i checked ArgoCD and Flux decided to join forces but i don't know what came out of it.

**Comment by 2020testuser** [comment]
@eddycharly  - Thanks much for the clarification!
Will checkout the links.
