### ISSUE TITLE
Tekton Upgrade

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/pipeline#2763]
Hi,
I want to upgrade my current tekton pipeline? Could anyone please let me know whether I need to uninstall the existing tekton and install the latest version? Or, can I simply run 'kubectl apply <latest-version-install.yaml> file?

Want to make sure as need to upgrade tekton. Thanks!

**Comment by bobcatfish** [comment]
As long as you are upgrading from a 0.11+ version you should only need to apply the latest version. Since the beta release we are being very careful about breaking changes but before that things could be a bit wild. Also always take a look at the release notes to see what has changed in a release and if there are any deprecation warnings: https://github.com/tektoncd/pipeline/releases

We also have this open issue to provide better guidance on how to upgrade: https://github.com/tektoncd/pipeline/issues/1222

**Comment by vdemeester** [comment]
This is also one of the goal of [`tektoncd/operator`](https://github.com/tektoncd/operator), to embedding any knowledge required for upgrading (like migration of CRD version from one version to another, etc…)

/cc @sthaha @nikhil-thomas

**Comment by 2020testuser** [comment]
@bobcatfish - Thanks !

@vdemeester  - Thanks! Will look at tektoncd/operator as I end up manually deleting the old version pods/deployments. operator would be useful.
