### ISSUE TITLE
Task with more than one workspace waiting forever to start

### ISSUE THREAD

**Issue by r0bj** [tektoncd/pipeline#2829]
# Expected Behavior

Task with more than one workspace starts.

# Actual Behavior

Task with more than one workspace waiting forever to start because it cannot attach volumes.

# Steps to Reproduce the Problem

1. There is a task (taskA) in pipeline which uses 2 workspaces
2. Pipelinerun starts, creates 2 different affinity-assistants
3. Because affinity-assistants use anti-affinity they are started on 2 different nodes
4. Each affinity-assistant mount volume on node where it runs, so volumes are mounted on different nodes
4. Task (taskA) cannot start because it uses affinity to one of the affinity-assistants and tries to attach 2 volumes which is impossible with `ReadWriteOnce` volumes
5. Task (taskA) waits forever to start

Is it possible to handle this situation with affinity-assistant enabled?

# Additional Info

- Tekton Pipeline version:
```
Client version: 0.10.0
Pipeline version: v0.13.2
Triggers version: v0.5.0
```

**Comment by jlpettersson** [comment]
>Is it possible to handle this situation with affinity-assistant enabled?

No - by intention. When the Affinity Assistant was introduced, the docs was also updated so that we recommend _at most one_ writeable workspace per Task.

>Each affinity-assistant mount volume on node where it runs, so volumes are mounted on different nodes

And this will happen if e.g. a pipeline starts with two parallel tasks - even without the Affinity Assistant.

In the worst case - these two volumes are located in two different Availability Zones - and your Pipeline is deadlocked - with or without the Affinity Assistant. For this reason I had to remove an end-to-end-test using two volumes - that _sometimes_ ended up in to different Availability Zones in a Regional cluster: https://github.com/tektoncd/pipeline/pull/2546

If you really want to use two volumes in a single Task - you must disable the Affinity Assistant, but you will must likely run into problems in regional clusters - but it depends on how your storage work.

**Comment by jlpettersson** [comment]
We should probably validate and emit an Event or use the Admission Webhook to validate these situation to inform the user in a better way.

**Comment by jlpettersson** [comment]
@r0bj is there any specific reason to why you need two workspaces in the same Task?

It is possible to have a single workspace volume but mount different parts of it using `subPath`, there is an example of that: https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/pipelinerun-using-different-subpaths-of-workspace.yaml

Is that a way to solve your use case?

**Comment by r0bj** [comment]
@jlpettersson thanks for explanation. In my case using `subPath` resolves issue. Using two workspaces is not a strong requirement, just an option I was considering.

**Comment by sbwsg** [comment]
Now that we have https://github.com/tektoncd/pipeline/pull/2885 merged, should we close this issue?

**Comment by vdemeester** [comment]
I would think so yes. If anyone feels it should be re-open, please comment :angel: 
/close
