### ISSUE TITLE
pipelineRun pvc best practice

### ISSUE THREAD

**Issue by GwonsooLee** [tektoncd/pipeline#2862]
I am triggering pipelineRun via triggerTemplate and the volume is used for cloning a github repository and doing some jobs in it. I want to use volumeClaim and delete it after pipelineRun finishes. 

Is there any other way to delete pvc after pipelinerun?? 

If not, then what is the best practice to build docker image and deploy in tekton pipelines? 

Thanks in advance!

**Comment by jlpettersson** [comment]
It is easiest to delete the PipelineRun - then the PVC created by volumeClaimTemplate is also deleted.

**Comment by wlynch** [comment]
/kind feature

The suggestion by @jlpettersson is likely the best short term answer.

@sbwsg Any thoughts on if/how we will do automatic volume cleanup for volumeClaimTemplates?

**Comment by GwonsooLee** [comment]
Thanks for answering. @jlpettersson @wlynch 
We actually considered deleting pipelineRun.. But if I wanted to keep the build/deploy log, do I have to store them to other place like s3 or elasticsearch, etc? 

We are trying to keep all logs of pipelineRuns at least a week...  Actually I changed to use NFS not to create pvc every time for every build. This is kind of a temporary solution for us (We just adopt to use tekton for CI/CD pipeline).

@wlynch If deleting pipelineRuns when completed  is the best short term solution, then, is it common to store pod logs to somewhere?? I am just wondering what is the best practice (if exists) of tekton pipeline~ I want to use it as efficient as possible :)

**Comment by vdemeester** [comment]
@GwonsooLee there is an [`experimental` project](https://github.com/tektoncd/experimental/tree/master/results) around this (and a [design doc](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit)).

**Comment by GwonsooLee** [comment]
@vdemeester  Thank you so much for introducing experimental project. `result api` seems perfect if applied. I will look it over! And, I requested access to the design doc, but not yet granted. Is there  anything I have to do for getting access or just wait? I just wanted to know if there is something I have to request but I didn't yet. Thanks again

**Comment by vdemeester** [comment]
> @vdemeester Thank you so much for introducing experimental project. `result api` seems perfect if applied. I will look it over! And, I requested access to the design doc, but not yet granted. Is there anything I have to do for getting access or just wait? I just wanted to know if there is something I have to request but I didn't yet. Thanks again

You should automatically have access to it if you are part of the `tekton-dev` google group, see [here](https://github.com/tektoncd/community/blob/master/contact.md#mailing-list)

**Comment by zhouhaibing089** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale

This is still relevant.

**Comment by sbwsg** [comment]
@zhouhaibing089 could you go into a bit more detail about why it's still relevant?

On one hand, when you use `volumeClaimTemplate` Tekton will introduce an owner reference so that the volume is cleaned up when the PipelineRun gets cleaned up. I believe it is possible to go in and delete that underlying volume by forcefully removing the `finalizer` attached by the owner reference but that's very much a hacky solution.

So, the ideal solution is to clean up the PipelineRun that owns the volume and have kubernetes follow the owner reference. This seems like a totally natural relationship to establish with k8s objects. The problem is capturing the log outputs from PipelineRuns. For that, there are lots of tools available such as `fluentd` or platform-specific ones like stackdriver. Tekton Results might add support for this at some point as well but I don't believe it does currently. Either way there is lots of machinery out in the Kubernetes ecosystem for capturing logs.

So I'm not really clear what the expectations should be here for Tekton Pipelines specifically. Could you give a bit more detail about the specific feature you'd want to see implemented to address this?

/remove-lifecycle rotten

**Comment by zhouhaibing089** [comment]
@sbwsg: Sorry about not adding enough detail in my previous comment.

That's right - when pipelinerun is deleted, the taskrun/pod/pvc will all be deleted. That's what we are doing as well.

But I doubt that's the best practice. As you mentioned, the log is a problem, if we delete the pipelinerun, we also lose the history records(I mean we lost the entrypoint to view logs). We need to have a place to view the pipelineruns, and then depending on whether the pipelinerun is running, we can choose to see logs from either pod directory or from log store.

Even if we stick with deleting pipelienruns, that doesn't mean we are going to delete the pipelineruns right away(I assume so), so what we are doing is, we keep histories for last N pipelineruns. The problem of it is, we are going to waste N PVC quotas which isn't ideal in my opinion.

I don't know, probably we should look into kubernetes community, and see whether PVC should be cleaned up when pod becomes Completed/Failed.

**Comment by zhouhaibing089** [comment]
This probably isn't related with kubernetes primitives.

What we need is probably just a simple controller which looks at all the PVC(s), if it has an ownerReference which points to PipelineRun or TaskRun, and also the PipelineRun/TaskRun is in Completed/Failed phase, we can offer an option to delete this PVC.

**Comment by mike-serchenia** [comment]
workaround 
```
for i in $(kubectl get pipelinerun -n tekton | grep 'Failed\|Succeeded' | cut -f 1 -d ' '); do
echo $(kubectl get pvc -n tekton -o json | jq --arg i "$i" '.items[].metadata | select(.ownerReferences[0].name==$i)|.name') | xargs -n1 kubectl delete pvc -n tekton
done
```
