### ISSUE TITLE
Tutorial: enhance "running this tutorial locally"

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/pipeline#2971]
As of today, in the [tutorial](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md#running-this-tutorial-locally), we assume the user is either running Windows or Mac OS(X) as we are only documenting the use of "Docker for Desktop" (which is only available on those).

We should enhance that part by having support for different tools and more Operating Systems (like GNU/Linux). We should at least document how to run the tutorial using a tool that is available on all platforms, aka [`minikube`](https://minikube.sigs.k8s.io/docs/) (and maybe [`kind`](https://kind.sigs.k8s.io/docs/) too).

/kind documentation

**Comment by psschwei** [comment]
So I ran into a bit of a blocker here, trying to keep the minikube as close as possible to the Docker for Desktop one...

I created a local insecure registry that I can push to locally:

```bash
docker run -d -p 5000:5000 --name registry-srv -e REGISTRY_STORAGE_DELETE_ENABLED=true registry:2
```

In order to be able to access this registry in minikube, I added the following to `/etc/hosts` on local:

```
127.0.0.1 docker.local
```

And then added the following to `/etc/hosts` on minikube (assume my local IP is `123.45.6.789`):

```
123.45.6.789 docker.local
```

I verified that after doing `minikube ssh` I can push/pull from `docker.local:5000/`.

Where I run into an issue is the Kaniko build, which gives me the following error:

```
[build-and-push] error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated 
correctly, and try again: checking push permission for "docker.local:5000/leeroy-web": creating push check transport for 
docker.local:5000 failed: Get "http://docker.local:5000/v2/": dial tcp: lookup docker.local on 10.96.0.10:53: no such host
```

To get around this, while still using this type of registry, I think we'd need to add `HostAliases` (see #1750). 

That said, there are also other registry options (I've seen [this one](https://hasura.io/blog/sharing-a-local-registry-for-minikube-37c7240d0615/) referenced somewhat frequently). 

@vdemeester Any preference for which direction to go? If you think it'd be better to add `HostAliases`, I can look into getting that added. (I may also be missing something obvious, so let me know if that's the case...)

**Comment by kameshsampath** [comment]
@vdemeester  @psschwei  check this add-on https://github.com/kubernetes/minikube/tree/master/deploy/addons/registry-aliases, this should help doing all the required setup for pushing and pulling from minikube internal container registry. 

HTH

**Comment by psschwei** [comment]
Thanks @kameshsampath ! will check that out
