### ISSUE TITLE
Look at constraining Controller ClusterRole

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#3035]
The /config/200-clusterrole.yaml really lets the controller have RBAC super-powers that in many cases it simply does not need (or at least strongly suspect this:)). We should look to constrain the privileges as much as we can.

**Comment by jbg** [comment]
Was this ever looked at? We're considering Tekton for CI/CD but with the permissions granted to the controller in the deployment YAML, we'd need to dedicate a k8s cluster just for Tekton, since it gets really wide access.

**Comment by imjasonh** [comment]
We've looked into scoping down what Tekton has permissions for at the cluster-scope (see [history](https://github.com/tektoncd/pipeline/commits/main/config/200-clusterrole.yaml)), but I don't think anybody's looked into constraining what namespaces it has access to. For that you'd need to tell Tekton which namespace(s) you expect to be able to run workloads in, which necessarily can't be configured ahead of time by Tekton. What namespaces should Tekton be configured to run workloads in by default?

You could definitely manually replace the default ClusterRole with namespaced Roles for each namespace you expect to run in, but that does get tedious. Maybe this is something the [Operator](https://github.com/tektoncd/operator) could be responsible for? If you tell the Controller what namespaces the controller should run workloads in it could grant it access to only those namespaces. But in order to do that, the Operator would need pretty expansive superpowers, so it might just be moving the problem around. 🤔 

Either way, let's reopen to continue this discussion.
