### ISSUE TITLE
Noisy test failures

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/pipeline#3075]
# Expected Behavior

When tests fail, the only error logs you see should be either intentionally caused by the test or representative of the problem.

# Actual Behavior

When reconciler tests fail, there are often many misleading error logs that look like this:

```
2020-08-07T12:29:16.923-0400	ERROR	TestReconcileWithWorkspacesIncompatibleWithAffinityAssistant	taskrun/controller.go:58	Failed to create taskrun metrics recorder running_taskruns_count: cannot register view "running_taskruns_count"; a different view with the same name is already registered
taskruns_pod_latency: cannot register view "taskruns_pod_latency"; a different view with the same name is already registered
github.com/tektoncd/pipeline/pkg/reconciler/taskrun.NewController.func1
	/Users/christiewilson/Code/go/src/github.com/tektoncd/pipeline/pkg/reconciler/taskrun/controller.go:58
github.com/tektoncd/pipeline/pkg/reconciler/taskrun.getTaskRunController
	/Users/christiewilson/Code/go/src/github.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun_test.go:271
github.com/tektoncd/pipeline/pkg/reconciler/taskrun.TestReconcileWithWorkspacesIncompatibleWithAffinityAssistant
	/Users/christiewilson/Code/go/src/github.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun_test.go:2955
testing.tRunner
	/usr/local/Cellar/go/1.14.2_1/libexec/src/testing/testing.go:991
```

Apparently `cannot register view "running_taskruns_count"; a different view with the same name is already registered` isn't actually a bug, but it sure does clog up the logs when there is a failure.

# Steps to Reproduce the Problem

Either look at the logs in our [recent flakey test bugs](https://github.com/tektoncd/pipeline/labels/kind%2Fflake) or cause a reconciler to fail on purpose (e.g. call t.Errorf).

**Comment by pritidesai** [comment]
It is very annoying indeed and same happens with pipelinerun reconciler.

**Comment by afrittoli** [comment]
I tried adding metrics view cleanup to tests in the past but I ran into data races. I'll see if I can find the code change again, perhaps someone has insights in what's going wrong.

**Comment by GregDritschler** [comment]
> I tried adding metrics view cleanup to tests in the past but I ran into data races. I'll see if I can find the code change again, perhaps someone has insights in what's going wrong.

@afrittoli I think I found your attempt to fix it here:
https://github.com/tektoncd/pipeline/commit/6b1579c89d75ec4e58c5630819429709e21f7332#diff-54a597aad65d997daf41843ebfe53533

It's a commented-out call to unregisterMetrics() in getTaskRunController().  Similar thing in getPipelineRunController().

I tried un-commenting both statements and running both the pipelinerun and taskrun unit tests a number of times.  It fixed the duplicate view registration noise and it did not break the tests.  I'm curious about the race condition you saw.  I'd be happy to help if I knew more about it.  As far as I can tell:
- the unit tests are run sequentially and not in parallel
- view unregistration is run by a worker but the function waits for it so that's synchronous.
If that's true, I'm not sure where the problem lies.

**Comment by bobcatfish** [comment]
Just echoing what @GregDritschler said, it seems like uncommenting those lines removes the noise! And I ran the tests with race detection and it was all good. It's a bit unfortunate that this means the tests will leave the global state dirty - basically we're unregistering any previously registered metrics immediately before re-registering them. It'd be nicer if there was a reliable way to get the tests to clean up after themselves (or if we weren't using global state but I guess that's how the opencensus libs work) - so this seems okay in the meantime?
