### ISSUE TITLE
Tekton installation link is not working? 

### ISSUE THREAD

**Issue by zeromsi** [tektoncd/pipeline#3083]
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for the owning project is disabled in state delinquent
</Details>
</Error>

**Comment by zeromsi** [comment]
@dibyom  I need your help bro!

**Comment by sbwsg** [comment]
Thanks for the issue report.  We're currently experiencing problems with our hosting of the YAML and docker image resources.  If you're in urgent need and you have access to the necessary resources, I suggest building from the tagged version in the git repo and pushing the images to a private registry.

Apologies, we're reaching out to the CDF to get help with this issue and hope to resolve ASAP!

**Comment by zeromsi** [comment]
@sbwsg  Thanks for your kind reply. yeah, It's really very urgent. can you please give a link of the release.yaml.

**Comment by sbwsg** [comment]
Sorry, I should've been more clear: there's currently no way to access a public release.yaml that I'm aware of.

The only option right now is to build the images locally and push them to a registry, which your cluster would need to have access to. We have a guide to doing so here: https://github.com/tektoncd/pipeline/blob/v0.15.1/DEVELOPMENT.md but it requires you to have a registry set up and it's very developer-focused.  If you do decide to go ahead with building and using your own images then I recommend building from the latest tagged release, which is `v0.15.1`.

I'll update this issue with any other workarounds as they present themselves but right now this is the only option I'm aware of.

**Comment by chmouel** [comment]
another option if it's really urgent, red hat produce a midstream release if you need, the nightly is located here https://raw.githubusercontent.com/openshift/tektoncd-pipeline/release-next-ci/openshift/release/tektoncd-pipeline-nightly.yaml 


We unfortunately had some issues and our latest non nightly is 0.14.3 which should work since the images are hosted on `quay.io`  

https://raw.githubusercontent.com/openshift/tektoncd-pipeline/v0.14.3/openshift/release/tektoncd-pipeline-v0.14.3.yaml

(it should on pure k8s  and non openshift but bear in mind that's completely unsupported)

**Comment by ghfalcon7** [comment]
Our pipelines are failing because of this as well: 

Failed to pull image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.12.0@sha256:b3cf4f912c58115e1ba9eb44a1e2d7a61445337e83117eeaec0eddbaf04ecf03": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

**Comment by daviddyball** [comment]
Perhaps an idea to add more public image mirrors in future just in case?

I know we'll be mirroring the images ourselves in future to avoid this.

**Comment by sbwsg** [comment]
Hi all, this issue with the public release yaml and images should now be resolved. Please try installing again if you hit this issue previously.

**Comment by sbwsg** [comment]
I'm going to close this issue as it now appears to be resolved. If you hit a similar error please open a new bug report.
