### ISSUE TITLE
Tekton fails to get image manifest from private docker registry 

### ISSUE THREAD

**Issue by dianqihanwangzi** [tektoncd/pipeline#3105]
### Feature request

Some ways to allow insecure access to private docker registry.

### Use case

If command not set,tekton will find the origin entrypoint from registry,it may raise error like this
```
failed to create task run pod "test-task1": translating TaskSpec to Pod: error getting image manifest: Get https://{private-repo}/v2/: x509: certificate signed by unknown authority. Maybe missing or invalid Task default/task
```
 Now i add insecure flag and rebuild controller to avoid  this,i hope there is an offical way to do this.

**Comment by bioball** [comment]
+1 this would be a nice addition.

A nicer way to work around this issue for now without having to change the insecure flag is to rebuild the controller using a base image that has your certs baked into it. You can do that by adjusting the values set in the [ko.yaml](https://github.com/tektoncd/pipeline/blob/master/.ko.yaml)

FWIW golang will look up certs from the following system paths: https://golang.org/src/crypto/x509/root_linux.go

**Comment by dianqihanwangzi** [comment]
> +1 this would be a nice addition.
> 
> A nicer way to work around this issue for now without having to change the insecure flag is to rebuild the controller using a base image that has your certs baked into it. You can do that by adjusting the values set in the [ko.yaml](https://github.com/tektoncd/pipeline/blob/master/.ko.yaml)
> 
> FWIW golang will look up certs from the following system paths: https://golang.org/src/crypto/x509/root_linux.go

Thanks!Add self signed certifacate seems less invasive.I'll try.

**Comment by nsoubelet** [comment]
I am facing exactly the same issue. Surprisingly, there are not too many people complaining about it although, from my point of view, this bug is pretty core. 
Access is not insecure because, for example in my case, the certificate is actually present in the node, problem is that tekton apparently does not pull task's images using the standard way as the regular pod controller but a container.

Is that correct?
If it was correct, a possible good solution should be mounting a configmap in deployment tekton-pipelines-controller pointing to container's /etc/ssl, assuming that it is an alpine-based image. That way rebuild can be avoided.

I will try and let you know.

**Comment by vdemeester** [comment]
> Access is not insecure because, for example in my case, the certificate is actually present in the node, problem is that tekton apparently does not pull task's images using the standard way as the regular pod controller but a container.
> 
> Is that correct?
> If it was correct, a possible good solution should be mounting a configmap in deployment tekton-pipelines-controller pointing to container's /etc/ssl, assuming that it is an alpine-based image. That way rebuild can be avoided.

It is correct *in a way*. This error happens **before** pulling the image. Tekton is doing some *entrypoint* magic (cc @bobcatfish @ImJasonH for their talk link :grin:) : in case no `command` is specified, the controller will try to fetch the image configuration to get the command (`entrypoint` is the "docker" sense)… And this is where it fails, because the tekton controller might not have the certificates available.

**Comment by nsoubelet** [comment]
Hi @vdemeester, it does make much more sense now.
However the design decision sounds a bit weird to me. That means that one cannot use an image with an already-defined CMD within as a tekton task. That is, one can't instruct controller to not do that _entrypoint magic_ since the very _entrypoint_ was already defined in a Dockerfile. Am I right?

If I am, that detail leads me to think that reusability of previously existing images, not originally meant to be used in tekton, might be hard or even impossible.

For now as I see it, best solution is dianqihanwangzi's

**Comment by vdemeester** [comment]
> Hi @vdemeester, it does make much more sense now.
> However the design decision sounds a bit weird to me. That means that one cannot use an image with an already-defined CMD within as a tekton task. That is, one can't instruct controller to not do that _entrypoint magic_ since the very _entrypoint_ was already defined in a Dockerfile. Am I right?

So the entrypoint *magic* is required for tekton to function properly. But it only happens when `command` is not present. 

> If I am, that detail leads me to think that reusability of previously existing images, not originally meant to be used in tekton, might be hard or even impossible.

This is *only* true for images pushed on a registry that is either not using tls, or using tls with a self-made certificate and or a certificate that is not signed by a known CA (from standards CA that are shipped in Tekton), not for anything else. If you have a private image on gcri.o or docker.io or quay.io, it shouldn't be a problem if the imagePullSecret that are attached to the `TaskRun` serviceAccount (specified by `serviceAccountName`).

To fix this, we need a way to let the user (or at least the operator of a tekton instance) to configure additionnal CA that tekton would have available when querying registries.

**Comment by nsoubelet** [comment]
> So the entrypoint _magic_ is required for tekton to function properly. But it only happens when `command` is not present.
>
Yes, understood. The thing is that it isn't uncommon to find images with the CMD already defined, so in those cases _command_ must not be present.
 
> This is _only_ true for images pushed on a registry that is either not using tls, or using tls with a self-made certificate and or a certificate that is not signed by a known CA (from standards CA that are shipped in Tekton), not for anything else. If you have a private image on gcri.o or docker.io or quay.io, it shouldn't be a problem if the imagePullSecret that are attached to the `TaskRun` serviceAccount (specified by `serviceAccountName`).
>
Yes but, for example, in my case I have a private registry behind an URL whose certificate was issued by sectigo and it is perfectly valid from the CA stand point of view. I am not saying this is the most frequent use case but only trusting by default a bunch of certificates and CA's might be a bit limited in terms of flexibility.

> To fix this, we need a way to let the user (or at least the operator of a tekton instance) to configure additionnal CA that tekton would have available when querying registries.
>
Sounds really good. Then we keep this as feature request.
