### ISSUE TITLE
PipelineRun Status bloat and excessive updates

### ISSUE THREAD

**Issue by skaegi** [tektoncd/pipeline#3140]
In our production systems we are seeing large PR objects frequently over 1MB in size when serialized as JSON with nearly all the information in status pipelineSpec and taskruns. This might seem big now but I would bet this is really just the beginning and as we see more Tekton usage things are going to get a lot larger. In addition as a pipeline runs the PRs get updated along with changes to status.taskruns. This is triggering a huge amount of traffic for listening systems like the dashboard and our other systems that react to events in cluster. We're already hitting internal cluster limitations and have had to trim the PRs significantly to avoid overwhelming our messaging systems. 

Looking at how the core Kubernetes API use status, it seems limited to very basic information and avoiding redundant information already captured in child or related objects. How painful would it be to re-work status to be lightweight?

**Comment by ImJasonH** [comment]
To me this seems to be closely related to https://github.com/tektoncd/pipeline/issues/454 -- if we had an off-cluster system to store *Run statuses, we wouldn't be bound by etcd's storage and performance issues around l arge objects. (That being said, we _would_ be bound by whatever _that system's_ limitations are 😄 )

As an alternative, we could phase out reporting all of each sub-*Runs' statuses in the PipelineRun, and just require clients to look up all the constituent *Runs' statuses in order to display all that information. Or we could only report sub-Runs' `.status.conditions` to signal success/failure/ongoing, and stop reporting per-step information, timing, etc. These would need to be carefully communicated and staged slowly to avoid breaking clients that may rely on this information today.

**Comment by bobcatfish** [comment]
i believe the chains folks will have some thoughts here as well @dlorenc

**Comment by bobcatfish** [comment]
Also more info in https://github.com/tektoncd/pipeline/issues/279

The PRs that made these changes are https://github.com/tektoncd/pipeline/pull/2444 and https://github.com/tektoncd/pipeline/pull/2489

> In our production systems we are seeing large PR objects frequently over 1MB in size when serialized as JSON with nearly all the information in status pipelineSpec and taskruns.

one thought: maybe dereferencing all the taskruns into the pipelinerun is too far?

**Comment by ImJasonH** [comment]
> one thought: maybe dereferencing all the taskruns into the pipelinerun is too far?

I think it makes sense to report each TaskRun's `.status.conditions` (success/failure) and results, and maybe a few more things, but per-step information might be overkill, and probably contributes the most to storage bloat. Updating the PipelineRun each time a step starts/finishes also means a lot more updates.

If Chains needs some complete record of each internal state I assume they could do the TaskRun lookups themselves, or consult a Results API which has done all the lookups, when that exists.

**Comment by sbwsg** [comment]
/reopen

This still seems worth discussing, even if we end up deciding that keeping a copy of the exact pipeline + tasks in the PipelineRun's status is indeed what we want to do.

**Comment by sbwsg** [comment]
Freezing for future review.

**Comment by lbernick** [comment]
/assign abayer

Feel free to remove your assignment if you no longer want to work on this!
