### ISSUE TITLE
Storing and updating PipelineSpec

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#3145]
"I was having trouble seeing unresolved when expressions in `status.pipelineSpec.tasks[]` and was trying to troubleshoot and discovered we actually store the `pipelineSpec` as is even before resolving params and it's never updated for auditing purpose. But wouldn't it be clearer if its updated once after resolving all params (and pipeline resources)?" ~ @pritidesai 

_Originally posted by @pritidesai in https://github.com/tektoncd/pipeline/pull/3135#discussion_r478184590_

**Comment by bobcatfish** [comment]
Some context:

- https://github.com/tektoncd/pipeline/issues/279 was the original issue about this
- in https://github.com/tektoncd/pipeline/issues/3140 we're getting feedback that we might be storing too much
- the functionality was added in https://github.com/tektoncd/pipeline/pull/2444 and https://github.com/tektoncd/pipeline/pull/2489

I think the motivation for storing this at all is to be able to tell exactly what spec the pipeline was run with, since pipelines can be modified later

>  But wouldn't it be clearer if its updated once after resolving all params (and pipeline resources)?

probably depends on why we're storing this information - i think it's less about being easy to see what happened and more about a historical record. if we mutated it before storing it, then the spec in this section would differ between runs

**Comment by pritidesai** [comment]
Yup agree, it depends on how it's being consumed. The spec is populated right after reading it during the first reconciler cycle and not updated based on the informer's copy. But if there is no objection, the spec can be populated after resolving all params and pipeline resources during the first reconciler cycle so that it does not differ between runs. This also means that spec will not be available or populated if it fails any of the validation check (invalid DAG, invalid syntax, invalid resource bindings, invalid params, etc) unlike today.

**Comment by jerop** [comment]
Duplicate in: https://github.com/tektoncd/pipeline/issues/3140
/close
