### ISSUE TITLE
Two PVCs (RWO storage) needed for a pipeline that uses Workspace and Buildah

### ISSUE THREAD

**Issue by abudavis** [tektoncd/pipeline#3219]
I am running Tekton OpenShift Pipeline Operator (beta channel) on Openshift 4.5 and have observed that for every Pipeline that uses Workspace and Buildah (for baking images), requires atleast 2 PVCs (if using a RWO storage/block storage). 

Because the task that runs the Workspace is a separate pod from the task that uses Buildah, block storage as expected prevents 2 pods from accessing the same PVC, therefore requiring 2 PVCs. Now you may suggest to use a RWX storage access type to workaround this problem which may even allow multiple pipelines to share the PVC, but this storage access type is not convenient for us.

Therefore, is there anyway to workaround this problem by means of 1) an ephemeral storage for shared workspaces and for buildah to hold temporary images? 2) A mechanism to ensure that the 2 PVCs are deleted/released after the task pods have attained "Completed" status? 3) any other means?

**Comment by jlpettersson** [comment]
Hi @abudavis 

Are you using the [Buildah Task](https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml) as from the Catalog? It is using one workspace "source" - but this can be shared with other Tasks.

I'm not sure I understand your problem.

>block storage as expected prevents 2 pods from accessing the same PVC, therefore requiring 2 PVCs

I also had this understanding in the beginning. But the RWO of volumes means that the volume can only be mounted on a single **node** at the time. Containers are not much more than processes, and can typically access the same volume concurrently.

I typically only use one PVC workspace for my PipelineRuns, but that workspace is used by many Tasks, sequentially or parallel.

> A mechanism to ensure that the 2 PVCs are deleted/released after the task pods have attained "Completed" status?

Yes, there is typically a need for cleaning up completed PipelineRuns/PVCs. There is currently no such things installed with Tekton, but it is possible to have CronJobs for that, e.g. https://gist.github.com/ctron/4764c0c4c4ea0b22353f2a23941928ad

**Comment by abudavis** [comment]
> Hi @jlpettersson 
> 
> Are you using the [Buildah Task](https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml) as from the Catalog? It is using one workspace "source" - but this can be shared with other Tasks.
**_Yes I am using the one from the Catalog. Basically I have 1 PVC for the git-clone clusterTask and 1 PVC for the task that uses Buildah, so was wondering if it is possible to have a common PVC for both these tasks?_**

> I'm not sure I understand your problem.
> 
> > block storage as expected prevents 2 pods from accessing the same PVC, therefore requiring 2 PVCs
> 
> I also had this understanding in the beginning. But the RWO of volumes means that the volume can only be mounted on a single **node** at the time. Containers are not much more than processes, and can typically access the same volume concurrently.
_**Well - the idea here was to enable several pipelines to use the same PVC when PipelineRuns are triggered concurrently (for example two developers starting 2 different pipelines referencing a common PVC at the same time), which did not work in my case.**_

> I typically only use one PVC workspace for my PipelineRuns, but that workspace is used by many Tasks, sequentially or parallel.
> 
> > A mechanism to ensure that the 2 PVCs are deleted/released after the task pods have attained "Completed" status?
> 
> Yes, there is typically a need for cleaning up completed PipelineRuns/PVCs. There is currently no such things installed with Tekton, but it is possible to have CronJobs for that, e.g. https://gist.github.com/ctron/4764c0c4c4ea0b22353f2a23941928ad
**_Thank you, this is helpful._**

**Comment by jlpettersson** [comment]
>Basically I have 1 PVC for the git-clone clusterTask and 1 PVC for the task that uses Buildah, so was wondering if it is possible to have a common PVC for both these tasks?

Yes, it is common that tasks share a workspace, and that that workspace is backed by a single PVC. The [Buildah Task](https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/tests/run.yaml) has an example of a `Pipeline`  with two `Tasks`, first _git-clone_ and then _buildah_, both using the same workspace. The volume for the shared workspace is declared in the `PipelineRun`. I would consider to use [volumeClaimTemplate](https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/workspace-from-volumeclaimtemplate.yaml) in the `PipelineRun` so that you get a new unique PVC for each PipelineRun.

>Well - the idea here was to enable several pipelines to use the same PVC when PipelineRuns are triggered concurrently (for example two developers starting 2 different pipelines referencing a common PVC at the same time), which did not work in my case.

It might work if the Pipelines only reads, or may be possible by using different parts of the volume using the `subPath`, but it sounds like a difficult setup and if the Pipelines writes to the volume they may overwrite contents for eachother? I think it is easiest to use a new PVC for each PipelineRun so that the PipelineRuns are isolated from eachother. But the Tasks in a PipelineRun should be able to share the PVC.

**Comment by abudavis** [comment]
Thanks again for the answers.
I did try to use a common PVC for git-clone (Workspace) and buildah tasks, the buildah pod reports this error, this is never a problem if I allocate separate PVCs for git-clone (and other tasks) and for buildah task. Could it be coz if the same workspace names for all tasks? 

```
Normal   Scheduled    <unknown>  default-scheduler                         Successfully assigned ace/timer-pipelinerun-mg67m-bake-image-mvbgd-pod-fwd4n to worker-4hgu4-norwayeast-sn6zv
  Warning  FailedMount  33s        kubelet, worker-4hgu4-norwayeast-sn6zv  Unable to attach or mount volumes: unmounted volumes=[varlibcontainers], unattached volumes=[tekton-internal-secret-volume-pipeline-dockercfg-v2w68-k4rb2 tekton-internal-secret-volume-gitrepousersecret-rn4gl tekton-internal-scripts varlibcontainers tekton-internal-home tekton-internal-tools tekton-internal-downward tekton-internal-results pipeline-token-jf5dh ws-p7tcq tekton-internal-workspace tekton-internal-secret-volume-entitlement-key-s7dmj]: timed out waiting for the condition
```

**Comment by jlpettersson** [comment]
>Unable to attach or mount volumes: ... timed out waiting for the condition

This is a problem that should be avoided by [enabling the Affinity Assistant](https://github.com/tektoncd/pipeline/blob/master/config/config-feature-flags.yaml#L32)

@abudavis since you are using Tekton from OpenShift 4.5, the Affinity Assitant is _disabled_ by default.

Personally, I would only recommend to disable the Affinity Assistant if you use a storage system or cluster that is not compatible with it, or if you have a storage system where it is not needed.

When using RWO storage (the most common) it is in most cases beneficial to _enable_ the Affinity Assistant. It makes so that the volume is only mounted **once** during a `PipelineRun`. If disabled, the volume need to be mounted on different nodes for every `TaskRun` in this typically takes 25-35 seconds on each `TaskRun`.

Also make sure to use `runAfter:[<taskname>]` for tasks that depend on data from previous tasks.

It would also be good to know what kind of storage you use, something that is located on the nodes or is accessed over the network within the AZ?

**Comment by abudavis** [comment]
Thanks again.
Enabled Affinity Assistant, but when the PipelineRun is started, the Affinity container tends to crash, dont know why.

``
  Events:
  Type     Reason                  Age                From                                      Message
  ----     ------                  ----               ----                                      -------
  Normal   Scheduled               <unknown>          default-scheduler                         Successfully assigned ace/affinity-assistant-36fe8c4afa-0 to worker-2fhdp-eueast-sn6zh
  Normal   AddedInterface          85s                multus                                    Add eth0 [10.128.3.79/23]
  Normal   Pulling                 83s                kubelet, worker-2fhdp-eueast-sn6zh  Pulling image "nginx@sha256:c870bf53de0357813af37b9500cb1c2ff9fb4c00120d5fe1d75c21591293c34d"
  Normal   SuccessfulAttachVolume  74s                attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-2286f4d2-b810-4c04-a165-04f9acb3ccaf"
  Normal   Pulled                  72s                kubelet, worker-2fhdp-eueast-sn6zh  Successfully pulled image "nginx@sha256:c870bf53de0357813af37b9500cb1c2ff9fb4c00120d5fe1d75c21591293c34d"
  Normal   Pulled                  21s (x3 over 69s)  kubelet, worker-2fhdp-eueast-sn6zh  Container image "nginx@sha256:c870bf53de0357813af37b9500cb1c2ff9fb4c00120d5fe1d75c21591293c34d" already present on machine
  Normal   Created                 19s (x4 over 70s)  kubelet, worker-2fhdp-eueast-sn6zh  Created container affinity-assistant
  Normal   Started                 19s (x4 over 70s)  kubelet, worker-2fhdp-eueast-sn6zh  Started container affinity-assistant
  Warning  BackOff                 3s (x6 over 66s)   kubelet, worker-2fhdp-eueast-sn6zh  Back-off restarting failed container
```

```
NAME                                                              READY   STATUS             RESTARTS   AGE
affinity-assistant-36fe8c4afa-0                                   0/1     CrashLoopBackOff   5          4m40s
timer-pipelinerun-7qf8d-bake-image-zfs4k-pod-szdcv    0/1     Init:0/3           0          3m34s
timer-pipelinerun-7qf8d-clone-repo-hpnt2-pod-k8h9l    0/1     Completed          0          4m40s
timer-pipelinerun-7qf8d-import-repos-kxlkz-po-wfkdx   0/2     Completed          0          4m2s
```

**Comment by jlpettersson** [comment]
Right, this is because OpenShift runs the container with more limited permissions, not compabtible with the `nginx`-image. It is possible to change the image for the Affinity Assistant in the `Deployment` manifest for the Tekton Pipelines controller. In newer versions of Tekton, the nginx image is now changed to [nop-image](https://github.com/tektoncd/pipeline/blob/master/config/controller.yaml#L65) but I don't know how you can get the image from that `ko://` url, hmm.

**Comment by coryrc** [comment]
I just bit the bullet and setup nfs to get RWX.

But, I noticed the Buildah Task does not mount its source workspace read-only; maybe that would help?

**Comment by abudavis** [comment]
@bharathvenkatrajan @jlpettersson I raised a support case with Redhat who have raised a bugzilla case - https://bugzilla.redhat.com/show_bug.cgi?id=1878998
