### ISSUE TITLE
Deprecate Conditions CRD

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#3377]
With the implementation of [Conditions Beta](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md), specifically `WhenExpressions`, we want to deprecate the `Conditions` CRD because:

- _Efficiency_: `Conditions` have to spin up new `Pods` for every check, even simple ones. `WhenExpressions` enable guarding `Tasks` with simple checks without spinning up new `Pods`. [Read more](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#efficiency-1).
- _Simplicity_: `Conditions` actually manifested themselves as `Tasks`. In more complex use cases, we can use `Tasks` themselves to produce `Results` that can be used to specify `WhenExpressions` in subsequent `Tasks`. [Read more](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#simplicity-1).
- _Flexibility_: When `Conditions` evaluated to False and the associated `Task` was skipped, the subsequent `Tasks` were skipped as well. `Tasks` guarded by `WhenExpressions` support passing in a field -`continueAfterSkip` - that enables ordering-dependent `Tasks` to execute when it is set to True. [Read more](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#skipping-1).
- _Status_: It is difficult to distinguish `Conditions` causing a `Task` to be skipped or the `Task` failing for other reasons. When `WhenExpressions` evaluate to false, the associated `Task` is listed in a `Skipped Tasks` section of the status alongside the resolved `WhenExpressions`. If they evaluate to True, the resolved `WhenExpressions` are listed alongside the `TaskRun` status. [Read more](https://github.com/tektoncd/community/blob/master/teps/0007-conditions-beta.md#status-1).

`Conditions` CRD has been listed in the [deprecations table](https://github.com/tektoncd/pipeline/blob/release-v0.16.x/docs/deprecations.md) since the release of [v0.16.0](https://github.com/tektoncd/pipeline/releases/tag/v0.16.0).

This is a milestone for release of Pipelines v1beta2. 

 cc @bobcatfish

**Comment by afrittoli** [comment]
@jerop @vdemeester @bobcatfish Do we need a `v1beta2` to remove `Conditions`? 
They have been deprecated since v0.16.0 and we Nov 2020 was the first time we could have removed them according to the policy.

**Comment by jerop** [comment]
I don't think it's worth the effort to create `v1beta2` just to remove `Conditions`, especially given that we're already working towards `v1` which won't have `Conditions` - [TEP-0096](https://github.com/tektoncd/community/blob/main/teps/0096-pipelines-v1-api.md#deprecations)

**Comment by afrittoli** [comment]
We could stop simply stop serving `Conditions` in `v1alpha1` - the problem is however that `Conditions` can be included in `v1beta1/Pipeline`.  Once we release the `v1` version of `Pipeline`, even if we deprecate `v1beta1` right away, we will need to serve `v1beta1` for 9 months, which includes support for references of `Conditions`.

I think there are three possible ways forward:

1. we stop serving `Conditions` even if we still serve CRDs that may refer to them
2. we deprecate `v1beta1` as soon as possible, and make a `v1beta2` which does not allow for references to Conditions. In nine months from now, we can drop `v1beta1` and remove `Conditions`
3. we deprecate `v1beta` when we release `v1` and nine months later we can drop `v1beta1` and remove `Conditions`

Option (1) feels a bit ugly, and option (2) feels like a lot of work for a `v1beta2` which no-one will ever use. Option (3) seems like a long time we'll need to keep `Conditions` around, but perhaps it's still the best way forward.

As a side note, all of the above applies to `PipelineResources` too.

@tektoncd/core-maintainers @lbernick

**Comment by vdemeester** [comment]
I think we don't really have any other decent choice than (2) or (3), and I would lean more on (3)

**Comment by lbernick** [comment]
I agree with Vincent that option 3 is best. Option 2 would follow the letter of our compatibility policy but as you said, not provide much benefit to users in exchange for a large amount of work on our part.

**Comment by lbernick** [comment]
Discussed in API WG this week and [on slack](https://tektoncd.slack.com/archives/CLCCEBUMU/p1649701811062659): we plan to remove Conditions from v1beta1 CRDs in v0.37.0.
