### ISSUE TITLE
Start affinity-assistant lazily

### ISSUE THREAD

**Issue by JPEWdev** [tektoncd/pipeline#3540]
### Feature request

Only start the affinity assistance before parallel tasks start executing in a Pipeline

### Use case

My understanding is that the purpose affinity assistant is to make tasks running in parallel execute on the same node so that they can share a PV, however I've noticed that it can prevent optimal scheduling of pipelines runs, particularly when the number of pipelines running greatly exceeds the cluster capacity. The affinity assistance gets created and effectively pins all the pipelines to a specific cluster node because it has such a small resource request that it can basically run anywhere. However, this means that every pipeline/task has it's node chosen before it executes. If that particular node is less capable than other nodes, this may result in non-optimal scheduling. If the affinity assistant was only created at the point where parallel tasks were detected in the pipeline DAG, A) it would never run for linear pipelines, and B) it would better allow the natural scheduling of tasks to free nodes during overload

**Comment by jlpettersson** [comment]
>The affinity assistance gets created and effectively pins all the pipelines to a specific cluster node because it has such a small resource request that it can basically run anywhere.

This should not be the case. The Affinity Assistant is configured with **PodAntiAffinity** to other Affinity Assistants - such that they should _repel_ - in a best-effort fashion.

>However, this means that every pipeline/task has it's node chosen before it executes. If that particular node is less capable than other nodes, this may result in non-optimal scheduling.

Yes, the point with the Affinity Assistant is to schedule tasks that use the same volume to the node were the volume is mounted.

>If that particular node is less capable than other nodes, this may result in non-optimal scheduling.

Yes. The scheduling can indeed be non-optimal with the Affinity Assistant. But it can not be improved much as it is improved now. By implementing this feature as a [Custom Scheduler](https://github.com/tektoncd/pipeline/issues/3052) instead of a Pod can hopefully improve on this - but scheduling is not so easy problem, especially not for Tekton Tasks that share a volume.

>If the affinity assistant was only created at the point where parallel tasks were detected in the pipeline DAG, A) it would never run for linear pipelines

There are actually several benefits with the Affinity Assistant in a linear pipeline - as is:
* It makes the Pipeline much faster - as it commonly takes 25-35 seconds to mount a volume - without the Affinity Assistant this will add (30 seconds x number of tasks), while with the Affinity Assistant - the volume is only mounted once at one node.
* In a _regional cluster_ - it prevents **deadlocks** since the tasks _must_ be scheduled to the same Availabilty Zone as the volume - since volumes typically is a _zonal resource_.
