### ISSUE TITLE
Default Podtemplate getting overriden with the pipelinerun and taskrun level podtemplate

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/pipeline#3569]
Right, now when you specify a default pod template and also specify pod template at pipelinerun/taskrun level. The default pod template is getting overridden by the one at the pipelinerun/taskrun level.

Is there any specific reason for it?

Is not doing the merge of both templates with giving precedence to one at taskrun/pipelinerun level be better so the user can reuse the default with some changes that can be specified at pipelinerun/taskrun level?

cc @vdemeester 

/kind question

**Comment by dibyom** [comment]
I'm not aware of the reason behind the current behavior

> Is not doing the merge of both templates with giving precedence to one at taskrun/pipelinerun level be better so the user can reuse the default with some changes that can be specified at pipelinerun/taskrun level?

This sounds reasonable to me!

**Comment by vdemeester** [comment]
There is actually 2 ways of merging : 
1. A default `PodTemplate` and a `PodTemplate` on a Run object with different field(s) set — e.g `NodeSelector` on the default, and `Volumes`on the Run `PodTemplate` to give a final `PodTemplate` with both `NodeSelector` and `Volumes` set
2. A default `PodTemplate` and a `PodTemplate` on a Run object with the same field(s) set — e.g. `NodeSelector` on both, what should it do ?

I think 1. is safe to implement and would be a net positive without any problems.

To tackle 2. it gets a bit more complicated, if we "merge" both, we may want to look at how the merge behavior should be for each existing field (and potential now ones like `Env`).

```
type Template struct {
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
	SecurityContext *corev1.PodSecurityContext `json:"securityContext,omitempty"`
	Volumes []corev1.Volume `json:"volumes,omitempty" patchStrategy:"merge,retainKeys" patchMergeKey:"name" protobuf:"bytes,1,rep,name=volumes"`
	RuntimeClassName *string `json:"runtimeClassName,omitempty" protobuf:"bytes,2,opt,name=runtimeClassName"`
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty" protobuf:"varint,3,opt,name=automountServiceAccountToken"`
	DNSPolicy *corev1.DNSPolicy `json:"dnsPolicy,omitempty" protobuf:"bytes,4,opt,name=dnsPolicy,casttype=k8s.io/api/core/v1.DNSPolicy"`
	DNSConfig *corev1.PodDNSConfig `json:"dnsConfig,omitempty" protobuf:"bytes,5,opt,name=dnsConfig"`
	EnableServiceLinks *bool `json:"enableServiceLinks,omitempty" protobuf:"varint,6,opt,name=enableServiceLinks"`
	PriorityClassName *string `json:"priorityClassName,omitempty" protobuf:"bytes,7,opt,name=priorityClassName"`
	SchedulerName string `json:"schedulerName,omitempty"`
	ImagePullSecrets []corev1.LocalObjectReference `json:"imagePullSecrets,omitempty"`
	HostNetwork bool `json:"hostNetwork,omitempty"`
}
```

Some are easy to "merge", all `boolean`, `string` and simple types (pointer to a type) : it's more or less a replace of the field.
*But* for the others, I wonder when it make sense to merge and when it make sense to replace. 

The `NodeSelector` is a relative good example. A cluster admin can some defaults so that the `Pod`s are created on a specific set of `Node`. *If* the user provide a `PodTemplate` with some `NodeSelector`, should it be additive to the defaults provided or should it replace them (as of today) ? Replacing means we do not respect the cluster admin wishes, merging might be confusing for the user, maybe ?

For each of those field (NodeSelector, Tolerations, Volumes, …, ImagePullSecrets), we need to ask ourselves the same question and implement the merge part corresponding to the behavior we want for each :wink: 

Finally, there will be "the precedence" :upside_down_face:. In case of two entry in `NodeSelector` with the same key but a different value, which ones takes precedence over the other ? the defaults or the one set at runtime ?

/cc @bobcatfish @sbwsg @pritidesai @afrittoli

**Comment by sbwsg** [comment]
Sorry to be a pain but...

- Why do we want to do this?
- For whom is this a problem, and why?
- If a user is relying on the current behaviour where one template entirely overrides the template of another, are we now breaking them?  (And do we care?)

**Comment by vdemeester** [comment]
> - Why do we want to do this?
> - For whom is this a problem, and why?

@sbwsg there is a bunch of use cases. Support for proxy is one of them, but others like allowing the cluster admin to set some `NodeSelector` that should be taken into account even when the user uses `podTemplate` (to add a volume for example or an imagePullRequest).

I think the main problem I see (aside from proxy env support) is a use-case similar to the following:

The cluster admin (responsible for installing and configuring the tektoncd/pipeline instance) sets up some default `NodeSelector` on the default `podTemplate` configmap, so that *all* pods are schedule on a given set of nodes (optimized for CI, …). *As of today*, if a user create adds a `podTemplate` to a `PipelineRun` to, let's say, pass an `imagePullSecret` (to be able to get a private image), then those `NodeSelector` are empty for that given run (and thus for all Pods that will come out of it). This can be a problem if the cluster admin wants to enforce the use of a certain set of nodes, no matter what the user wants.

The current behavior is a bit confusing for the cluster-admin as some of it's "default" may not be taken into account even though the user did not override them.

> If a user is relying on the current behaviour where one template entirely overrides the template of another, are we now breaking them? (And do we care?)

It shouldn't be that hard to handle / document. If we go on the *merge* route, then, to override, e.g. `NodeSelector`, you would need to set the field on the `PipelineRun` object (so that it is empty). It has few benefits:
- It makes it explicit
- It can be disallowed by rules enforcer like OPA, …

**Comment by sbwsg** [comment]
Nice, thanks @vdemeester your example makes sense to me.  So would we want this to be feature-flagged initially with a view to making it the default behaviour for v1?

**Comment by vdemeester** [comment]
> Nice, thanks @vdemeester your example makes sense to me. So would we want this to be feature-flagged initially with a view to making it the default behaviour for v1?

This is something to discuss, but naively I would say yes :upside_down_face:

**Comment by skaegi** [comment]
Yikes. This is real and some internal issues now make more sense. It turns out we actually do a lot of things that @vdemeester mention here https://github.com/tektoncd/pipeline/issues/3569#issuecomment-738060560

We frequently see:
```
podTemplate:
        imagePullSecrets:
        - name: pipeline-pullsecret
```
injected into PipelineRuns and we also in our service inject `affinity` into the same PR podTemplate for workspace volumes... had no idea we were overriding the Task podTemplate.
