### ISSUE TITLE
Duplicate 'pipelinerun.successful' cloudevent in v0.18.1

### ISSUE THREAD

**Issue by wwu-cx** [tektoncd/pipeline#3617]
# Expected Behavior

A single 'dev.tekton.event.pipelinerun.successful.v1' event after a successfull pipelinerun.

# Actual Behavior

Sometimes, duplicate events are being sent out:

```
Context Attributes,
  specversion: 1.0
  type: dev.tekton.event.taskrun.successful.v1
  source: /apis/tekton.dev/v1beta1/namespaces/tekton-builds/taskruns/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2
  subject: argo-eps-it082-49-f2nwc-rocket-ok-rx6j2
  id: dfef49ac-acad-4318-b80f-b5bb81a83e62
  time: 2020-12-09T06:33:25.200085402Z
  datacontenttype: application/json
```
```
Context Attributes,
  specversion: 1.0
  type: dev.tekton.event.taskrun.successful.v1
  source: /apis/tekton.dev/v1beta1/namespaces/tekton-builds/taskruns/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2
  subject: argo-eps-it082-49-f2nwc-rocket-ok-rx6j2
  id: acd39363-b1d2-4560-8a4f-80bf196b48ea
  time: 2020-12-09T06:33:25.600481682Z
  datacontenttype: application/json
```

in the logs of tekton-pipelines-controller, I see:

```
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.196Z","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:360","msg":"Cloud Events: []","commit":"2fbd24b","knative.dev/traceid":"cef46284-648e-4fe3-81a6-eb26af580cfe","knative.dev/key":"tekton-builds/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.199Z","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:449","msg":"Successfully reconciled taskrun argo-eps-it082-49-f2nwc-rocket-ok-rx6j2/tekton-builds with status: &apis.Condition{Type:\"Succeeded\", Status:\"True\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfec39cd4be8a261, ext:1796522079629127, loc:(*time.Location)(0x3159020)}}}, Reason:\"Succeeded\", Message:\"All Steps have completed executing\"}","commit":"2fbd24b","knative.dev/traceid":"cef46284-648e-4fe3-81a6-eb26af580cfe","knative.dev/key":"tekton-builds/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.200Z","logger":"tekton.event-broadcaster","caller":"record/event.go:278","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"tekton-builds\", Name:\"argo-eps-it082-49-f2nwc-rocket-ok-rx6j2\", UID:\"1d7bcac6-7830-4374-bbc6-b15fbc9380e6\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"145297629\", FieldPath:\"\"}): type: 'Normal' reason: 'Succeeded' All Steps have completed executing","commit":"2fbd24b"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.408Z","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"controller/controller.go:522","msg":"Reconcile succeeded. Time taken: 359.460275ms","commit":"2fbd24b","knative.dev/traceid":"cef46284-648e-4fe3-81a6-eb26af580cfe","knative.dev/key":"tekton-builds/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.596Z","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:360","msg":"Cloud Events: []","commit":"2fbd24b","knative.dev/traceid":"ad45fced-149f-4873-907f-e46b8298fc55","knative.dev/key":"tekton-builds/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.600Z","logger":"tekton.github.com-tektoncd-pipeline-pkg-reconciler-taskrun.Reconciler","caller":"taskrun/taskrun.go:449","msg":"Successfully reconciled taskrun argo-eps-it082-49-f2nwc-rocket-ok-rx6j2/tekton-builds with status: &apis.Condition{Type:\"Succeeded\", Status:\"True\", Severity:\"\", LastTransitionTime:apis.VolatileTime{Inner:v1.Time{Time:time.Time{wall:0xbfec39cd63c6003d, ext:1796522480012567, loc:(*time.Location)(0x3159020)}}}, Reason:\"Succeeded\", Message:\"All Steps have completed executing\"}","commit":"2fbd24b","knative.dev/traceid":"ad45fced-149f-4873-907f-e46b8298fc55","knative.dev/key":"tekton-builds/argo-eps-it082-49-f2nwc-rocket-ok-rx6j2"}
09/12/2020 07:33:25 {"level":"info","ts":"2020-12-09T06:33:25.602Z","logger":"tekton.event-broadcaster","caller":"record/event.go:278","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"tekton-builds\", Name:\"argo-eps-it082-49-f2nwc-rocket-ok-rx6j2\", UID:\"1d7bcac6-7830-4374-bbc6-b15fbc9380e6\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"145297629\", FieldPath:\"\"}): type: 'Normal' reason: 'Succeeded' All Steps have completed executing","commit":"2fbd24b"}
```

# Steps to Reproduce the Problem

1. Create a Listener for the CloudEvents
2. Filter for header.match('ce-type', 'dev.tekton.event.pipelinerun.successful.v1')
3. Log the invocations

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}  
```

- Tekton Pipeline version:

```
Client version: 0.14.0
Pipeline version: v0.18.1
Triggers version: v0.10.1
Dashboard version: v0.11.1
```

**Comment by afrittoli** [comment]
Hello @wwu-cx , thank you for your report.

We do not guarantee unique events in Tekton - because of how the reconcile logic works and of the use of informers, it may be that events are sent twice. 

For instance, if the last two task runs complete execution at a similar time, both will trigger a reconcile on the pipeline run. 
Both reconcile cycles will run one shortly after the other, so the second one may have a stale pipelinerun informer cache, and reset the completion time, the succeeded condition and send associated events.

We had similar issues with duplicate `TaskRun` which @GregDritschler has been fixing, but because `TaskRun` are stored in etcd, it is possible to avoid duplication. Events are not stored in `etcd` though.

One way to ensure unique events would be to keep track of sent events and drop duplicated ones; one way to solve this is to make the reaction to the event idempotent; for instance if you're updating the status on GitHub, it won't matter (much) if you update it twice, it will be just a wasted pod. If this is not applicable to your use case, you may try filtering events on the receiving side.

If you have a good use case for unique events in Tekton, it would be great if you could share it. It is something that is not necessarily easy to achieve, but if needed we may decide to provide or recommend some extra component that could do filtering (and re-ordering?) of events. 

There's a new Tekton project called "results" where we plan to provide long term storage for pipelineruns, taskruns, events and other "things" that happen in Tekton; it is meant however as an eventually consistent system, so it may not be of help for event filtering.

We're also working with the CDF interoperability SIG (https://github.com/cdfoundation/sig-interoperability/tree/master/workstreams/events_in_cicd) and use cases would be interesting in that context too.

One thing that I would do for sure is to amend the documentation to clarify that we do not guarantee uniqueness of events.

**Comment by wwu-cx** [comment]
Thank you, @afrittoli for your explanation. 

My use case is simple.. To trigger a postprocessing Pipeline after the Build.

 The Reason I was not using a finally task for that was that our build contains a lot of optional steps and determining the success or failure of the PipelineRun was not easy (there is no status field, but that's another story..)

Our Plan B to guarantee uniqueness involves using an external Service (DynamoDB) to filter duplicate Events so that is not a real problem.

I find it a little unfortunate that multiple success events are sent out. I'm not a go programmer so my expertise is limited... If events are not stored in etcd and the PipelineRun is, how about storing them as part of the PipelineRun ? (status.completionEventSent or status.conditions[].eventSent)

**Comment by afrittoli** [comment]
> Thank you, @afrittoli for your explanation.
> 
> My use case is simple.. To trigger a postprocessing Pipeline after the Build.
> 
> The Reason I was not using a finally task for that was that our build contains a lot of optional steps and determining the success or failure of the PipelineRun was not easy (there is no status field, but that's another story..)

[TEP-0028](https://github.com/tektoncd/community/blob/master/teps/0028-task-execution-status-at-runtime.md) should help once it's implemented (@pritidesai ).

> 
> Our Plan B to guarantee uniqueness involves using an external Service (DynamoDB) to filter duplicate Events so that is not a real problem.
> 
> I find it a little unfortunate that multiple success events are sent out. I'm not a go programmer so my expertise is limited... If events are not stored in etcd and the PipelineRun is, how about storing them as part of the PipelineRun ? (status.completionEventSent or status.conditions[].eventSent)

Thanks for your suggestion. Unfortunately storing them in the pipeline run status would suffer from the same stale informer cache issue. One way could be to send the event on the next reconcile cycle, and at the same time write the info about the sent event in the status. However:
- We'd have no control on how much later the reconcile cycle might happen
- We'd still not 100% guarantee uniqueness probably, but likelihood would be lower

I can add this issue to the backlog if you want, so we keep this option open for the future.
We plan eventually to move the cloud event generation to a dedicated controller, so it may be something that we tackle then?

**Comment by pritidesai** [comment]
> TEP-0028 should help once it's implemented (@pritidesai ).

on that note, the implementation PR is ready for review https://github.com/tektoncd/pipeline/pull/3390 😉 

@wwu-cx please give it a try to accessing execution status in finally and feel free share its limitations if you find any. Also, would love to hear your use cases or expectations from pipeline.

**Comment by julienje** [comment]
Hi @afrittoli 
I found this ticket and on my project we also use tekton cloudevent notification to do some business after a build.
We don’t see duplicate for successful event but we (almost always) have 2 events for failed pipeline.
If I understood your answer correctly it’s not possible to grantee uniqueness of events, it’s still the case? You also mention that is possible that this issue is coming in backlog, was it the case?
I’m also interested to know how long it is possible to become 2 cloudevent notifications. We are going to build a deduplication system and it’s good to know how long we need to keep events.
Thanks
Julien
