### ISSUE TITLE
Moving image entrypoint lookup to the TaskRun pod rather than Tekton Controller

### ISSUE THREAD

**Issue by NavidZ** [tektoncd/pipeline#3626]
Currently Tekton controller pod has access to all service accounts and will do entry point lookup using [containerregistry](https://github.com/google/go-containerregistry) for the images that don't have any command specified for them. This potentially might cause issues (e.g. [1](https://groups.google.com/a/google.com/g/tekton-discuss/c/Sg8wHi8-BNM/m/mvNDqG6iAwAJ), [2](https://github.com/tektoncd/pipeline/issues/2316))) on some of the cloud providers due to the restricted access to the images and how the requests coming from different pods are authenticated. 

I propose to move the image entry point lookup logic altogether to the entry point binary on the TaskRun pod.

This approach move the related logic to a particular task to its own computing unit and will make things more clear. This solution might also enable us to restrict access of Tekton controller pod to have access to all service accounts (although it always needs to have access to create other pods with those service account so it probably never completely goes away). At the same time it has some caveat that if there is any failure in entry point fetching we would only find out when the whole TaskRun pod is scheduled and started running as oppose to today that Tekton Controller will find out about that and return error right away.

**Comment by NavidZ** [comment]
@mattmoor @ImJasonH

**Comment by vdemeester** [comment]
@NavidZ I wonder if " if there is any failure in entry. point fetching we would only find out when the whole TaskRun pod is scheduled and started running as oppose to today that Tekton Controller will find out about that and return error right away" is such a caveat but indeed, it would fail the pipeline or task later on, *but*, might be easier to understand why.

Doing this from the entrypoint, means we are already *in* the image we want to gather the config from. I wonder if there would be a way to do this directly from the cluster (without requiring to query the registry) — I doubt there is a standard way to do that, but it would be nice (it would simplify our work)

**Comment by NavidZ** [comment]
> Doing this from the entrypoint, means we are already in the image we want to gather the config from. I wonder if there would be a way to do this directly from the cluster (without requiring to query the registry) — I doubt there is a standard way to do that, but it would be nice (it would simplify our work)

This certainly was something I had in mind as well. Although I couldn't find any API in K8s exposing it right now but we can either find a hacky way (or maybe future API) to just query K8s instead of the registry.

**Comment by mattmoor** [comment]
Yeah, I've debated something similar for our digest resolution logic, but I worry that this will add prohibitive cost to task startup latency in the common case.  One option I've been considering is creating a CRD abstraction to handle this resolution built around the `foo.class` extensibility model.

The basic idea would be to have a CRD like:

```yaml
apiVersion: img.dev/v1
kind: ExtractMetadata
metadata:
  name: blah
spec:
  <stuff> # likely similar to what we have with the image cache resource today in Knative
status:
  <the metadata of the image> 
```

The schema would be the same across implementations, but then this abstraction may be implemented with:
```yaml
  annotations:
     img.dev/resolver.class: ggcr.resolvers.img.dev
```

This enables multiple implementations to live side-by-side, and only the appropriate one acts on resources.  This would mean you could ship a ~fast ggcr version, and a ~slow pod-based version.  Users could even implement their own if they really wanted to.

**Comment by NavidZ** [comment]
> Yeah, I've debated something similar for our digest resolution logic, but I worry that this will add prohibitive cost to task startup latency in the common case. 

Why is this? I mean if there is something to be done (say when the command is not mentioned and Tekton Controller needs to do that) the action is being done and the time is consumed before TaskRun startup. So we are just moving it from Tekton Controller to right before running the actual TaskRun steps. So I don't see how it would affect the startup latency time (if you refer to the time between when the task is submitted and when the first step starts running).

**Comment by mattmoor** [comment]
> I propose to move the image entry point lookup logic altogether to the entry point binary on the TaskRun pod.

I actually misread this (my brain plugged in the alternative I was really considering) as booting a pod to let the kubelet fetch the image, and extract the digest we need from status.  I'll also blame it on not having enough ☕  yet 😉 

For performing the lookup in the entrypoint itself, the container running as the SA doesn't necessarily have the same access as the kubelet (`imagePullSecrets` vs. `secrets`), so this could be a point of confusion.  This also shifts it from an operator problem (configure workload identity properly) to a user problem.

This would also mean no more digests, which bugs me a little, but not as much as in contexts that are long lived with horizontal scaling (e.g. knative serving) where you end up with inconsistent replication 😉   Although I do wonder how you plan to ensure consistency between the image that the kubelet runs and the image whose metadata you are fetching?  If you aren't using `imagePullPolicy: Always` with tags you could get some very interesting results due to inconsistencies.

Apologies again for misreading above!

**Comment by NavidZ** [comment]
> I actually misread this (my brain plugged in the alternative I was really considering) as booting a pod to let the kubelet fetch the image, and extract the digest we need from status. I'll also blame it on not having enough ☕ yet 😉

This is kind of along the same idea that @vdemeester mentioned earlier. So if we can indeed get all the information from the fetched image by kubelet we are all set and no need to do another round trip to the registry and that would be fantastic. But this needs more investigation of what's available and what we can do.

> For performing the lookup in the entrypoint itself, the container running as the SA doesn't necessarily have the same access as the kubelet (`imagePullSecrets` vs. `secrets`), so this could be a point of confusion. This also shifts it from an operator problem (configure workload identity properly) to a user problem.
> 
> This would also mean no more digests, which bugs me a little, but not as much as in contexts that are long lived with horizontal scaling (e.g. knative serving) where you end up with inconsistent replication 😉 Although I do wonder how you plan to ensure consistency between the image that the kubelet runs and the image whose metadata you are fetching? If you aren't using `imagePullPolicy: Always` with tags you could get some very interesting results due to inconsistencies.

I remember @ImJasonH brought up this point regarding user specified images with no digest and the possible inconsistencies but we did come into some result in our verbal discussions around this. I'm having a hard time recalling what it was.

**Comment by ImJasonH** [comment]
> I remember @ImJasonH brought up this point regarding user specified images with no digest and the possible inconsistencies but we did come into some result in our verbal discussions around this. I'm having a hard time recalling what it was.

If the user specifies a digest, we'll use it, and only fetch the image in the kubelet. If they don't specify a digest, the controller can _attempt_ a lookup as today, and if that fails due to auth we can fallback to fetching from the kubelet and at least populating the digest we fetched in the status. If you care about reproducibility, you need to specify images by digest, that's not really even new.

I suspect the most common case by far will be public images without digest (`golang`, `busybox`, etc.) which means most users won't even see different behavior. Only users who specify private images should see different (newly successful!) behavior.

> Although I do wonder how you plan to ensure consistency between the image that the kubelet runs and the image whose metadata you are fetching? 

The entrypoint will be fetching the metadata (i.e., `command`) from the kubelet that's also just fetched/started the step image in question. If the entrypoint can get this information from the kubelet or the underlying local container runtime, there's _no_ opportunity for inconsistency. If it has to go back to the registry, but at least there's a smaller window of time than if it was fetching from the controller, where there's more time between that fetch and the pod starting.

**Comment by mattmoor** [comment]
> If they don't specify a digest, the controller can attempt a lookup as today

I'd either keep or drop this.  Half measures will lead to inconsistent experiences and feels like an extra moving part worth avoiding.  I don't envy explaining this to users 😉 

> The entrypoint will be fetching the metadata (i.e., command) from the kubelet

Do you have a specific API in mind for this?  Talking to host processes like the kubelet sounds like a privileged action (maybe even worse than what this issue is replacing, and in a user vs. system context feels like a double whammy).

> at least there's a smaller window of time than if it was fetching from the controller

I think you are assuming `imagePullPolicy: Always`, which is NOT the default.  If users aren't specifying a pull policy then the image the kubelet runs could be weeks old (it is technically unbounded).  My primary concern isn't a race, it is the kubelet's horrific stale caching.

**Comment by ImJasonH** [comment]
> I think you are assuming imagePullPolicy: Always, which is NOT the default. If users aren't specifying a pull policy then the image the kubelet runs could be weeks old (it is technically unbounded). My primary concern isn't a race, it is the kubelet's horrific stale caching.

Yep! I definitely was :)

This definitely means we should try to find a way to query the kubelet or underlying runtime for the image's command, and yeah, there might not be a good secure unprivileged way to do that... 🤔

**Comment by mattmoor** [comment]
> Yep! I definitely was :)

Everyone does.  I spent so many years of my life teaching folks about this because everyone thinks it is a registry bug.  "Something something eventual consistency."  If I could change one thing in K8s, it might be to replace `imagePullPolicy` with requiring client-side digest resolution.  `</rant>`

**Comment by vdemeester** [comment]
/remove-lifecycle rotten
This is still something worth exploring, there is even a TEP around this, or at least a [TEP PR](https://github.com/tektoncd/community/pull/310)

**Comment by pritidesai** [comment]
As per the discussion in the [API WG](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.fjd0c3gb5yzo), I am closing the TEP PR. We need to first showcase this in the experimental repo to understand the impact of the proposal/changes before changing the API.
