### ISSUE TITLE
task with params can not upgrade from v1alpha1 to v1beta1

### ISSUE THREAD

**Issue by leo1515416043** [tektoncd/pipeline#3644]
# Expected Behavior
In v0.17.3, v1alpha1 & v1beta1 both work well

# Actual Behavior
In v1alpha1 & v1beta1,  taskrun both failed with REASON:CouldntGetTask

> failed to create task run pod "pr-test-v2-190008343-pt1-cbdbb": Pod "pr-test-v2-190008343-pt1-cbdbb-pod-4kgwv" is invalid: [spec.volumes[12].secret.secretName: Required value, spec.containers[1].image: Required value, spec.containers[2].volumeMounts[0].name: Not found: "ironman-define-secret"]. Maybe missing or invalid Task tekton-pipelines/task-test-v2

# Steps to Reproduce the Problem
#### Task.yaml
![image](https://user-images.githubusercontent.com/48787027/102865826-497f3a00-4471-11eb-9a0a-02880b56fbac.png)

config yaml, such as task.yaml, taskrun.yaml same as https://github.com/tektoncd/pipeline/tree/v0.17.3/config

In config.yaml, I also try remove conversion「conversion.strategy: None」,   also can face with "CouldntGetTask"

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  1.16
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
  ```
  devel     0.17.3
  ```

**Comment by pritidesai** [comment]
Analyzing the error message logged in the description:

> failed to create task run pod "pr-test-v2-190008343-pt1-cbdbb": Pod "pr-test-v2-190008343-pt1-cbdbb-pod-4kgwv" is invalid: [spec.volumes[12].secret.secretName: Required value, spec.containers[1].image: Required value, spec.containers[2].volumeMounts[0].name: Not found: "ironman-define-secret"]. Maybe missing or invalid Task tekton-pipelines/task-test-v2

`failed to create task run pod` is being logged as part of `handlePodCreationError`:

https://github.com/tektoncd/pipeline/blob/ca26ea83aba58aa0313f1a5bb81fbd686a6acb01/pkg/reconciler/taskrun/taskrun.go#L533-L538

The second part of the error says the `Pod <podName> is invalid` because of:

* spec.volumes[12].secret.secretName: Required value
* spec.containers[1].image: Required value
* spec.containers[2].volumeMounts[0].name: Not found: "ironman-define-secret"

Also, it will be great if you can provide us the complete `task.yaml` (if possible) and how this particular task is being utilized in `taskRun` or `pipelineRun`? And check if the task is created in your kubernetes cluster?

Also, this task definition has two `volumeMounts` with the same name `myapp-home-volume`, is that a typo?
