### ISSUE TITLE
Duplicated pods created for single Taskrun

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/pipeline#3656]
# Expected Behavior
One pod for each `Taskrun`
# Actual Behavior
Multiple ones
# Steps to Reproduce the Problem

# Additional Info
Sometimes the issue happen.

In my case, I register a `mutating admission webhook` for `Pod`, I guess it will delay the pod creation, and there must be race condition in reconcile of `taskrun`, see the code snippet:
https://github.com/tektoncd/pipeline/blob/55fdb95816a3b2c47ea6b8ee8789761615de60f1/pkg/reconciler/taskrun/taskrun.go#L380-L384

The first reconcile after a `taskrun` created should be:
`Check tr.Status.PodName  -> Create pod --> update TR`
and in second reconcile, we expect the pod is already created, but seems not.

so that's because `webhook` delay the pod creation,
If my guess is correct I think the issue will be found in many scenario, for example: the `scheduler` is slow or network is not good enough or `kubelet` on some node slow .etc.

Any idea, thanks. 
- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by bkmeneguello** [comment]
I saw this problem recently too. But in my case, I don't have an admission webhook, but a check condition. I think the same applies because the check delays the pod creation. I'm investigating this case but a race condition could explain the problem.

**Comment by vdemeester** [comment]
I wonder if we should update the status of the taskrun to be able to know if we submitted the pod creation, with a given time before we re-try 🤔 

cc @tektoncd/core-maintainers @mattmoor

**Comment by GregDritschler** [comment]
There are a couple of things that can go wrong here:

* The TaskRun status is stale and does not reflect the pod name set on a previous reconcile.
* The pod informer cache is stale and does not contain the newly created pod.

This is similar to the exposures we've discussed with duplicate TaskRuns being created by the pipelinerun reconciler.  When I discussed that problem at an API WG meeting late last year, I said the taskrun reconciler was vulnerable as well though I didn't recall it being reported.  Now it is.

Possible solutions:
* Use predictable pod names.
* Keep pending actions in-memory ("expectations") to avoid repeating them.

**Comment by mattmoor** [comment]
This is a place where we use fixed child resource names to avoid duplication.  I'm guessing that you use generate name today?

**Comment by bkmeneguello** [comment]
I think predictable pod names is the best solution to avoid this kind of concurrence, the synchronization overhead should be minimum when controllers are replicated.

**Comment by GregDritschler** [comment]
I can work on this issue.  It is similar to the duplicate TaskRun issues which are still open so I have done a lot of thinking already on this type of problem.

With respect to using predictable pod names, ideally the Pod would just be given the same name as the TaskRun. However if the TaskRun is retried there may be multiple pods created from the same TaskRun so that won't work.

We could formulate the pod name using the TaskRun name and appending a retry number to it. The problem here is that Tekton limits both TaskRun and Pod names to 63 characters. Although resource names theoretically can be up to 253 characters, I believe they are limited to 63 characters in case they are used in label names and values which are limited to 63 characters.
So appending a retry number to a 63-character TaskRun name could run into problems with the pod name exceeding 63 characters.

I suspect the pod name has to formulated similarly to how it is today, but instead of using a random suffix, use a predictably generated hash of some sort that also factors in retries. The problem here will be dealing with name collisions which may increase the complexity somewhat.

I'm open to other suggestions.

**Comment by GregDritschler** [comment]
I was mistaken in my earlier comment about a cause for this being a stale pod informer cache.  The TaskRun reconciler doesn't use the pod informer cache to find the pod.  It uses the k8 API directly.  Given that, it should always find the pod it previously created (if it's still there).   There was speculation the creation of the pod was delayed by a webhook.  However webhooks run synchronously to the create call.  If the create call returned, the pod is there.

I looked for another explanation for what's going on and noticed that if the pod name is not set, the TaskRun reconciler does a LIST for pods that have the same labels as the TaskRun.  The TaskRun's labels are propagated to the pod when it's created.  However those labels can change causing the pod not to be found.  There was a similar problem found in the PipelineRun reconciler a couple of months ago.

I did some follow-up debugging with @vincent-pli and confirmed that what he's experiencing is due to a label change.  In his case it looks like one of the pod's labels that was inherited from the TaskRun was subsequently changed, causing the mismatch.

I am submitting a PR to fix the problem.  The fix is the same as what we did for the PipelineRun reconciler: to only use the Tekton-controlled label identifying the owning TaskRun name to locate the pod.
