### ISSUE TITLE
v1alpha1 tasks trigger admission webhook error when reloaded w/ v0.22.0

### ISSUE THREAD

**Issue by ghglza** [tektoncd/pipeline#3841]
# Expected Behaviour
re-applying a task resource that has already been created should result in a nop

# Actual Behavior
since upgrading to v0.22.0, re-applying an existing task results in a denial error by the webhook adminssion controller

# Steps to Reproduce the Problem

1. create v1alpha1 Task resource:
```
$ cat <<'EOF' > test.yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: test-task
  spec:
  inputs:
    params:
    - name: image
  steps:
  - name: run
    image: $(inputs.params.image)
    script: |
      echo "Test at $(date -Iseconds)"
EOF
$ kubectl apply -f test.yaml
task.tekton.dev/test-task created
```
2. re-apply existing resource
```
$ kubectl apply -f test.yaml
Error from server (BadRequest): error when applying patch:
{"spec":{"inputs":{"params":[{"name":"image"}]},"steps":[{"image":"$(inputs.params.image)","name":"run","script":"echo \"Test at $(date -Iseconds)\"\n"}]}}
to:
Resource: "tekton.dev/v1alpha1, Resource=tasks", GroupVersionKind: "tekton.dev/v1alpha1, Kind=Task"
Name: "test-task", Namespace: "sre-ci"
for: "test.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: expected exactly one, got both: inputs.params, params
```
# Additional Info
The denial does not happen if the spec.input element is removed

- Kubernetes version:
v1.19.8

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
v0.22.0

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
```
Client version: 0.15.0
Pipeline version: v0.22.0
Triggers version: v0.12.0
```

**Comment by vdemeester** [comment]
@ghglza Thanks for the report. This is definitely not new and should be happening from the first version we shipped v1beta1 to today. `v1alpha1` is converted into `v1beta1` for storage. The problem is with `apply` that merges what is stored with what you want to apply and thus it adds both `params` and `inputs.params`. The workaround here is either using `v1beta1` API instead of `v1alpha1` (mainly because `v1alpha1` will be gone at some point, soon-ish) *or* use `kubectl replace` instead.

**Comment by ghglza** [comment]
Do you mean you don't consider this behavior a bug?
We deploy Tekton tasks with the Flux2 GitOps toolkit (where we don't have control about what kind of kubectl operation equivalent is executed during reconciliation by the kustomize controller), and the error message turned up after upgrading Tekton to v0.22.0 (i.e. it was not emitted by the same setup with Tekton v0.20.0)

**Comment by vdemeester** [comment]
> Do you mean you don't consider this behavior a bug?
> We deploy Tekton tasks with the Flux2 GitOps toolkit (where we don't have control about what kind of kubectl operation equivalent is executed during reconciliation by the kustomize controller), and the error message turned up after upgrading Tekton to v0.22.0 (i.e. it was not emitted by the same setup with Tekton v0.20.0)

Hum, I consider this as an unfortunate bug due to how `kubectl apply` works… That said, if this used to work with `v0.20.0`, then something else is went wrong there, and thus might highlight another bug. @ghglza do you know if it does this for `v0.21.0` ?

> where we don't have control about what kind of kubectl operation equivalent is executed during reconciliation by the kustomize controller

@ghglza Right, but you have control over the `APIVersion` in use right ? If yes, updating your yaml to `v1beta1` would be the best way forward because `v1alpha1` will be gone at some point. The above Task, would become :

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
  spec:
    params:
    - name: image
  steps:
  - name: run
    image: $(params.image)
    script: |
      echo "Test at $(date -Iseconds)"
```

See [Migrating From Tekton `v1alpha1` to Tekton `v1beta1`](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1-to-v1beta1.md) too.

**Comment by ghglza** [comment]
OK, thanks for the heads up!
We'll start to lift our tasks to v1beta1 today.

**Comment by ghglza** [comment]
So after re-testing it turns out that
* the error on re-application was also existent w/ Tekton v0.20.0
* we became aware of it due to upgrading the Flux2 GitOps toolkit, because the older versions of the kustomize operator (though faithfully logging it) did not surface the error message to "kubectl get" operations on its CRs
* upgrading our tasks to v1beta1 was a no-brainer, and made the error message go away also for Flux2 kustomize CRs

That said, IMHO the behavior is a bit confusing to the end user (as it's not really obvious that the Task CRs are API-version-converted for storage).
Also, it occurs to me that kubectl issues a warning when re-applying for core API resources, but doesn't throw an error -- maybe this more forgiving kind of behavior could also implemented for Tekton CRs?

**Comment by vdemeester** [comment]
> That said, IMHO the behavior is a bit confusing to the end user (as it's not really obvious that the Task CRs are API-version-converted for storage).

Yes and no at the same time 😝 . Using the approach of CRD + webhook (admisison controller) + controller, we can have only one version stored (it's a limitation from k8s itself for this approach). Thus, we have to convert all *served* version to a given one. I agree it can be confusing though 😓 .

> Also, it occurs to me that kubectl issues a warning when re-applying for core API resources, but doesn't throw an error -- maybe this more forgiving kind of behavior could also implemented for Tekton CRs?

Do you have an example of such warnings ? Usually it warns when you `apply` something you use `create` to create before (instead of using `apply`) — things like `kubectl create -f myfile.yaml && kubectl apply -f myfile.yaml` should generate a warning. I am not sure how much control we have over those to be honest, but that might be something to look at yes.

**Comment by sbwsg** [comment]
I'm going to remove this one from priority critical urgent given the reason for this behaviour is a somewhat nuanced side-effect of working with k8s CRDs.
