### ISSUE TITLE
Why does a Tekton resource cannot contain a dot?

### ISSUE THREAD

**Issue by goldmann** [tektoncd/pipeline#3891]
I see this validation being enforced on Tekton resources: https://github.com/tektoncd/pipeline/blob/879ba4f65732808a0614d76d5993af0bac736009/pkg/apis/validate/metadata.go#L31-L36 A dot is a a perfectly valid character within the resource name as per [Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/). Why Tekton does not allow for dots in resource names?

Dots are generally very useful, for example in cases where you would like to have versions as part of the name.

**Comment by vdemeester** [comment]
/kind feature

If it's valid for kubernetes, I don't see why we block this indeed. Looking at https://github.com/tektoncd/pipeline/blame/0cb2bf09f1a2ebc30e833d3e64a38b61858be51c/pkg/apis/pipeline/v1alpha1/metadata_validation.go, seems like it's been there since the start of the project (as part of the skeleton).

/cc @tektoncd/core-maintainers

**Comment by ImJasonH** [comment]
It goes back even further, to [Knative Build days](https://github.com/knative/build/blob/master/pkg/apis/build/v1alpha1/metadata_validation.go#L33-L38). Digging even further, this check seems to show up for the first time in https://github.com/knative/build/pull/181, written by a rather untrustworthy looking character named @ImJasonH 🤔 

I agree with @vdemeester that this is probably unnecessary and can be removed so `.`s are allowed.
