### ISSUE TITLE
Allow multiple Tekton installation on a single cluster

### ISSUE THREAD

**Issue by qhua948** [tektoncd/pipeline#4050]
### Feature request

It would be nice to allow multiple Tekton installations on a single cluster without conflicts

### Use case

We have a fleet of managed clusters and we would like to install Tekton on them, to run some custom jobs managed by the team. But at the same time, we also would like customer to have their own copy of Tekton if wish to install it. Tekton should support multiple installations without conflicts, by having features like https://github.com/tektoncd/pipeline/issues/4049.

**Comment by afrittoli** [comment]
Thanks @qhua948 for the feature request. 
It would be possible to run multiple instances of a Tekton Controller - each watching a different namespace (or set of namespaces), and each with its own configurations. 
Admission webhooks themselves are cluster resources, but they support [namespace selectors](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector), so that could work.

CRDs however are cluster objects, and - as far as I know - k8s does not supports any mechanism to install multiple versions of them. Which means that if you have a pre-installed Tekton, your customers would be limited to installing the same version of Tekton, or at least a version of Tekton that has identical CRDs.

@vdemeester FYI

**Comment by qhua948** [comment]
Thanks for the response @afrittoli !

**Comment by qhua948** [comment]
I believe current Tekton only supports watching a single namespace via a controller arg, is this correct?

**Comment by nikhil-thomas** [comment]
That is true. At present, it is all namespaces or a specific namespace. But a patch to make it watch more than one namespace should be simple. I think it has to be added in knative/pkg library.
