### ISSUE TITLE
manual delete TaskRun, its ownerReference PipelineRun remains Running

### ISSUE THREAD

**Issue by leo1515416043** [tektoncd/pipeline#4066]
# Expected Behavior
* pipelinerun status to failed
* pipelinerun event record this situation

# Actual Behavior
pipelinerun remains running

# Steps to Reproduce the Problem

1. manual delete taskrun

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  1.16
  ```

- Tekton Pipeline version: 

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

 ```
 0.17.3
 ```

**Comment by jerop** [comment]
/assign @sbwsg 
/remove-lifecycle stale

thanks @sbwsg!

**Comment by sbwsg** [comment]
Hey @leo1515416043 thanks for the issue report. I'm going to describe what's happening here. For context, I'm running on the latest Tekton Pipelines from source.

What you are seeing is expected behaviour: when an owned TaskRun is deleted mid-execution the PipelineRun reconciler does not know that a deletion happened. Instead the only thing that the PipelineRun reconciler knows is that the TaskRun doesn't exist. This in turn leads to the reconciler attempting to re-create the TaskRun so that it can complete its work.

Now an interesting extra detail related to [some very recent changes in Tekton Pipelines](https://github.com/tektoncd/pipeline/pull/4361) is that a PipelineRun __will__ fail when one of its TaskRuns are deleted. The reason for this is that the names of TaskRuns are now no longer randomized. If a TaskRun is deleted the PipelineRun reconciler will see an update and attempt to re-create the TaskRun. However, if the Pod or the TaskRun are slow to delete then either the TaskRun reconciler or the PipelineRun reconciler will receive an error while trying to re-create those objects. At this point the TaskRun and/or PipelineRun will be placed into a failed state.

I believe this is an intended change in behaviour but I am pinging @afrittoli here for more context around the `kmeta.ChildName` fixes.

**Comment by sbwsg** [comment]
Here's also the PipelineRun I used to test this behaviour:

```yaml
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: test
spec:
  pipelineSpec:
    tasks:
    - name: foo-task
      taskSpec:
        steps:
        - name: waiter
          image: alpine:latest
          script: |
            sleep 10000s
```

So I created this using `kubectl apply -f ./test.yaml` and then opened a new terminal and started watching PipelineRuns with `kubectl get pipelineruns -w`.  Then I deleted the taskrun with `kubectl delete taskrun test-foo-task`.  On a slightly older version of Pipelines I issued `kubectl delete taskrun test-foo-task-<random-string>`.

It might be helpful if there was also more context around _why_ this is an important use-case for your @leo1515416043 .  Is there a specific feature you are trying to implement with Tekton that requires you delete owned TaskRuns rather than their PipelineRuns?
