### ISSUE TITLE
Rename the 'finally' key to 'final' in the specification and while still allowing 'finally' to help the users who already have this key as part of their specification

### ISSUE THREAD

**Issue by Srivaralakshmi** [tektoncd/pipeline#4086]
**Expected behaviour:** 

- The name used to represent the final set of tasks at the end of the pipeline must be represented as `final` in the specification: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#adding-finally-to-the-pipeline
- while the key is renamed from `finally` to `final`, continue to allow the `finally` key to accommodate the users who already have the `finally` key as part of their specification.  

**Actual behaviour:** At present the name used to represent the final set of tasks at the end of the pipeline is represented as `finally` in the specification: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#adding-finally-to-the-pipeline

**Reason for this proposal:**

- The word 'final' is an adjective that is describing the noun 'task', just like the term 'conditional' task (which is deprecated now and is replaced with 'when' expression).
- 'finally' is an adverb and when we use it to describe 'task', it sounds incorrect and weird. 
- The docs mention both terms and switches between: 'final' task and 'finally' task, in multiple places (please see: https://github.com/tektoncd/pipeline/blob/main/docs/pipelines.md#adding-finally-to-the-pipeline). This is very confusing even for a new developer. 
- We can have `final` tasks and not `finally` tasks. We need to use one terminology consistently. Also the terminology must be correct both technically and from the language perspective as well.

**Comment by Srivaralakshmi** [comment]
@nikhil-thomas PTAL at this ^ issue, comment on the issue, and kindly tag others. This will help drive some discussion. Thank you!

**Comment by bobcatfish** [comment]
hey @Srivaralakshmi - thanks for opening this issue.

The motivation for the term "finally" was inspiration from languages like python which have ["try/catch/finally" syntax](https://docs.python.org/3/reference/compound_stmts.html#finally). [This design doc has some more context around the design](https://docs.google.com/document/d/1lxpYQHppiWOxsn4arqbwAFDo4T0-LCqpNa6p-TJdHrw/edit#). What our current syntax is trying to say is:

1. First, run all these tasks (`tasks` section - which actually is a DAG of tasks, you could argue we could have a better name for this as well)
2. Finally, after that's done, whether it succeed or not, run these other tasks (`finally` section)

It sounds like one thing we could certainly do in the short term is to consistently use "finally tasks" in our docs instead of sometimes saying "final tasks".

Beyond that, could you explain a bit more about the problems this confusion is causing? If this is a matter of having to initially understand what 'finally' means, but users are able to use the feature after that, i'm not sure that's enough motivation to change the name of the field. But if we are seeing something like: folks are accidentally  using `final` and then getting bizarre behavior, such as the section being silently ignored, then maybe we need to add some additional verification.

**Comment by bobcatfish** [comment]
@Srivaralakshmi @nikhil-thomas  [I've added this to the next API working group agenda as well to discuss](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.vubvdscv123d)

**Comment by rkratky** [comment]
@bobcatfish,

> Beyond that, could you explain a bit more about the problems this confusion is causing?

Having the term "`finally` tasks" in docs is confusing because it sounds incorrect (it *is* incorrect, unless you know to read 'finally' as an adjective, which is very unintuitive). This makes the user (unless they're already familiar with the history) look for an explanation ("Is it a mistake?", "Is it correct but strange?"). Therefore, the docs would need to provide an explanation, which adds unnecessary complexity (and degrades overall user experience).

Another option would be to  always use a roundabout way of referring to this, such as "tasks in the `finally` section". That would sidestep the problem.

**Comment by afrittoli** [comment]
> @bobcatfish,
> 
> > Beyond that, could you explain a bit more about the problems this confusion is causing?
> 
> Having the term "`finally` tasks" in docs is confusing because it sounds incorrect (it _is_ incorrect, unless you know to read 'finally' as an adjective, which is very unintuitive). This makes the user (unless they're already familiar with the history) look for an explanation ("Is it a mistake?", "Is it correct but strange?"). Therefore, the docs would need to provide an explanation, which adds unnecessary complexity (and degrades overall user experience).
> 
> Another option would be to always use a roundabout way of referring to this, such as "tasks in the `finally` section". That would sidestep the problem.

That sounds like a viable option to me. 
I definitely agree we should be consistent in the documentation - thanks @Srivaralakshmi for reporting the issue.
As long as we make the terminology clear, I think we could also talk about "final tasks" to intend "tasks in the `finally` section".

**Comment by Srivaralakshmi** [comment]
@rkratky and @bobcatfish Thank you very much for the comments and support.

**Comment by Srivaralakshmi** [comment]
@bobcatfish Thanks for the response and also for adding this issue to the API working group agenda. FYI, I do not have access to this document; have sent a request.

**Comment by bobcatfish** [comment]
@Srivaralakshmi to get access to the doc you need to join the tekton-dev mailing list, more info on how to do that at https://github.com/tektoncd/community/blob/main/contact.md#mailing-list 🙏

**Comment by bobcatfish** [comment]
There as some discussion in the API working group today ([notes here](https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.mv8bg2s2jznx)) - seems like the general sentiment is to stick with `finally` tasks for now (and avoid renaming the API field), which https://github.com/tektoncd/pipeline/pull/4090 reflects - hopefully this can be a step forward at least.

**Comment by Srivaralakshmi** [comment]
@bobcatfish Thanks for the update.

**Comment by jerop** [comment]
fixed in https://github.com/tektoncd/pipeline/pull/4090

/close
