### ISSUE TITLE
Suggestion: References of WhenExpressions should be changed to `when` expressions

### ISSUE THREAD

**Issue by Srivaralakshmi** [tektoncd/pipeline#4098]
**Expected Behavior:** References of `WhenExpressions` in the documentation should be changed to `when` expressions.

**Actual Behavior:** The `when` expression resource is referred in the documentation as `WhenExpressions`.

**Reason for the request:**
- Backticks are used to refer to code in the YAML. In the YAML only `when` is mentioned, `whenExpressions` are not mentioned anywhere. When we refer to `when` expressions in the documentation, it is weird to say: `WhenExpressions`. Instead it is easier to use `when` expressions in the documentation.

**Comment by sbwsg** [comment]
I'm not quite sure what you mean by "when expression is a resource", could you clarify a bit?  I think of them as the name of a data structure but don't totally understand why we should hold ourselves to always using the name single-case in our documentation.  The plural of `WhenExpression` is `WhenExpressions` :)  It might help if you could point to specific docs and describe specifically what it is you think is misrepresented or incorrect about the usage.

I'm going to switch this to `kind/documentation` rather than `kind/bug` if that's ok.  The bug label is useful for classifying and aggregating reports of misbehaviour in the execution of Tekton Pipelines and I think this issue is related entirely to the language we're using in our docs?

**Comment by Preeticp** [comment]
@Srivaralakshmi is this what you mean? Expected Behavior: References of `WhenExpressions` in the documentation should be changed to `when` expression/expressions.

**Comment by Srivaralakshmi** [comment]
@sbwsg Thank you very much for the response. I have updated the description and the issue title. Please take a look.

**Comment by sbwsg** [comment]
👍 this looks good to me, thanks for the update!
