### ISSUE TITLE
Add an option to disable per TaskRun/PipelineRun metrics

### ISSUE THREAD

**Issue by zhouhaibing089** [tektoncd/pipeline#4101]
### Feature request

Add an option to disable per TaskRun/PipelineRun metrics

### Use case

We are conducting performance tests on pipeline controllers. While we are creating a huge amount of PipelineRuns, the size of metrics increases dramatically. This blocks metrics collector from scraping these metrics(390k series) and as a result, we are not to visualize some key metrics which are important to identify deviations.

I'm looking for an option so that we can report only the key metrics.

**Comment by bobcatfish** [comment]
Hey @zhouhaibing089 sounds like a reasonable request!

@vdemeester has a proposal around simplifying the metrics (https://github.com/tektoncd/community/pull/466) which may or may not help you; otherwise maybe [the observability configuration](https://github.com/tektoncd/pipeline/blob/main/config/config-observability.yaml) can be extended to specify [which metrics to include/exclude](https://github.com/tektoncd/pipeline/blob/main/docs/metrics.md)?

**Comment by zhouhaibing089** [comment]
@bobcatfish: Thanks! And that TEP describes the exact same issue here!

**Comment by zhouhaibing089** [comment]
Looks like this issue is resolved in https://github.com/tektoncd/pipeline/pull/4201

/close
