### ISSUE TITLE
More informative pipeline run status reporting

### ISSUE THREAD

**Issue by marrober** [tektoncd/pipeline#4350]
### Feature request

At the moment when a pipeline run ends the status will either show 'Succeeded' or 'Failed'. It would be helpful if there was a third option such as 'Partially succeeded' for when tasks have been skipped.

### Use case

I have a number of pipelines that include a 'when' condition on the tasks to control their execution. In the case where a task is skipped due to the when condition the pipeline run still shows as 'Succeeded'. As a Red Hat Solution Architect I demonstrate Tekton to many customers and on seeing this behaviour many customers have stated that the pipeline should not show as Succeeded when a task has been skipped. My defence has always been that the pipeline run has reached a successful conclusion including the dynamic selection of which tasks to run but it's a bit of a thin argument. A more descriptive status to show the true behaviour of the pipeline run would be much better. An example is shown in the attached image in which the last task on the right is greyed out because it did not execute.

![image](https://user-images.githubusercontent.com/55595712/140056987-7438857f-4681-401c-8465-793e4052c1fb.png)

**Comment by afrittoli** [comment]
Thank you for your feature request @marrober.

Tekton does expose a slightly different condition when a `Task` is skipped - the reason will be set to "Completed" instead of "Succeeded" - see https://tekton.dev/docs/pipelines/pipelineruns/#monitoring-execution-status.

It conditional execution is somehow used to capture an error condition, then it's up to the author to make sure that the pipeline will fail. Otherwise conditional execution can be used to skip a `Task` that is not required in certain conditions.

Note that the OpenShift Console is not maintained by the Tekton project, so a feature request to highlight the "Completed" reason needs to be directed to RedHat for that. /cc @vdemeester

**Comment by marrober** [comment]
Thanks for the update - given that this requires a change to the OpenShift Console I will raise the issue there.
