### ISSUE TITLE
Flake - test TestExamples/v1alpha1/taskruns/step-script

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#4433]
As part of the PR #4429, alpha integration tests ran into a failure:

```
test TestExamples/v1alpha1/taskruns/step-script 10m3s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=test\sTestExamples\/v1alpha1\/taskruns\/step\-script$'
    init_test.go:135: Create namespace arendelle-xwdmb to deploy to
    init_test.go:163: Verify SA "default" is created in namespace "arendelle-xwdmb"
    examples_test.go:62: Failed waiting for task run done: timed out waiting for the condition
```

The detailed logs can be found [here](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4429/pull-tekton-pipeline-alpha-integration-tests/1471071891585241088/).

/kind flake

**Comment by abayer** [comment]
This specific flake should be dealt with by #5005, since that removes the `v1alpha1` tests entirely, but I believe this (and other `v1alpha1` flakes, namely #4645, #4427, and #4415) may well continue to be flaky in their `v1beta1` equivalents. In general, I think most, if not all, of the flakes we hit in e2e tests are due to timing issues on clusters created in our test project in GKE, since I've failed to reproduce any of them in repeated runs in a local `kind` setup...

**Comment by pritidesai** [comment]
Pipelines WG - deleted v1alpha1 examples and tests but might happen with v1beta1. Closing this for now since havent seen this in a while. We can reopen if needed!
