### ISSUE TITLE
Timeout can set to 0s but failed during taskrun

### ISSUE THREAD

**Issue by Tomcli** [tektoncd/pipeline#4435]
Since Tekton v0.28+, `activeDeadlineSeconds` is introduced for the pods and it's calculated based on the timeout. Since `activeDeadlineSeconds` must be between 1 and 2147483647s, setting timeout to 0s will cause the following errors
```
failed to create task run pod "pipeline-15bdb-run-b-jv5wt": Pod "pipeline-15bdb-run-b-gxq8z" is invalid: spec.activeDeadlineSeconds: Invalid value: 0: must be between 1 and 2147483647, inclusive. Maybe invalid TaskSpec
```

# Expected Behavior
The webhook should give me an error if I set the timeout to 0s.

# Actual Behavior
I can apply the taskRun without errors but failed when the controller is trying to create the pod.

# Steps to Reproduce the Problem

1. Set any task's timeout to 0s.
2. The taskrun will have the above error.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  v1.21
  ```

- Tekton Pipeline version:
v0.30.0

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by pritidesai** [comment]
thank you @Tomcli for reporting this.

@vdemeester @Tomcli What should be the expected behavior when a timeout is set to `0s`? 

`activeDeadlineSeconds` is not directly set from the API and calculated based on the given timeout using this formula:

```
int64(taskRun.GetTimeout(ctx).Seconds() * 1.5)
```

And setting the timeout to `0s` as `NoTimeout` so it's not reasonable for a `webhook` to throw an error. 

can we leave setting the `activeDeadlineSeconds` in this case?

**Comment by Tomcli** [comment]
Before Tekton 0.28, timeout can be set to 0s and the pod will never timeout. If `activeDeadlineSeconds` is not necessary, we can skip the `activeDeadlineSeconds` if timeout is 0. 

At the moment, since timeout with 0s is broken between Tekton 0.28-0.30, we changed our client code to check timeout cannot be <= 0s because the webhook didn't throw any error.

**Comment by pritidesai** [comment]
thanks @Tomcli 👍 

@Tomcli @vdemeester please take a look at the fix, PR #4450 👀

**Comment by pritidesai** [comment]
@Tomcli if the PR is merged, do you want us to cherry pick this fix in the latest pipeline release (https://github.com/tektoncd/pipeline/releases/tag/v0.31.0)? Please note that v0.32.0 is due on January 13th.

**Comment by Tomcli** [comment]
We don't need to cherry pick, since it's broken since v0.28.0. We can move onto v0.32 if there are no significant changes.
At the moment we are using Tekton v0.30.0.

**Comment by Tomcli** [comment]
thanks @pritidesai for fixing this issue.

**Comment by vdemeester** [comment]
The use of `activeDeadlineSeconds` is *mainly* to mark pipeline's Pod as `Terminating` (for quotas, etc..). Not setting it in some cases will be very confusing as we would end up in cases where pods are terminating and cases where they are not, thus sharing different quotas.

I think the alternative here are:
- Disallow timeout 0 so that we never run into this (it's kind-of breaking current behavior)
- Allow timout 0 and setting `activeDeadlineSeconds` to its max value
- Reverting setting `activeDeadlineSeconds` (but it move back the pipeline's Pod under the nonterminating quota.. which is unexpected for 99% of users and use cases)
- Disallow timeout 0 and have an option/controller flag to allow it with the nonterminating behavior.
