### ISSUE TITLE
Consider removing script mode default flags

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#4444]
Currently, Tekton scripts set the flags `-ex` if no default is specified by users (#1735). This causes scripts to exit immediately if a command fails (`-e`), and print commands before they are executed (`-x`) ([bash docs](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)). These defaults were chosen because `-x` helps with debugging, and it often doesn't make sense to continue executing a script when a command fails (the default behavior is not preferred by many users).

We may want to consider changing these defaults for 2 reasons:
1. The `-x` flag could print secrets to logs
2. Although it is [documented](https://tekton.dev/docs/pipelines/tasks/#running-scripts-within-steps), users may not expect Tekton to use any flags in shell scripts by default. Because the correct flags to use often depend on the user's preferences, we may prefer to default to what the user would expect (no defaults).

This is a backwards incompatible change, so it should be included in our V1 release if we choose to do it.

**Comment by vdemeester** [comment]
I tend to agree with the -x flag as it might also display secrets by default. The -e though I tend to disagree: if we don’t set it the task might succeed where it should have failed. In addition it is very easy to override those flags, with a shebang.

**Comment by imjasonh** [comment]
+1 to removing `-x` and keeping `-e`. 👍

**Comment by sbwsg** [comment]
Still some discussion to be had around `-e` I think.

/reopen

**Comment by vdemeester** [comment]
@lbernick @sbwsg any reason for not having `-e` by default ?
I am *kind-of* hoping we set sane default (see "writing robust scripts" in https://bertvv.github.io/cheat-sheets/Bash.html or other article around this).

```
  set -o errexit   # abort on nonzero exitstatus
  set -o nounset   # abort on unbound variable
  set -o pipefail  # don't hide errors within pipes
```

**Comment by sbwsg** [comment]
From my pov it's less about opinion-driven questions of "sane defaults" and more about letting admins and platforms select what defaults fit their users and use-cases best.

We allow overriding the shell images that scripts run in, so perhaps we should also support the default script preamble being overridden too. Either way that strikes me as unrelated to the core motivation behind this issue and the discussion can happen elsewhere.

/close

**Comment by dibyom** [comment]
So, in general I think sane defaults are a good idea but enforcing them might be deviation from one would expect from a shell by default i.e. most shells would not have `set -e` by default. 

There are some use cases where users may rely on the default shell behavior  e.g. not failing early if the linting fails. Users can obviously get around this in Tekton today by adding a `set +e` to their lint step - but this is a difference from how most users would expect their shells to behave.

I think if we were to reimplement this from scratch, I'd vote for a no default flags approach. But given that we already have `set -e` and changing it would be a breaking change, I wonder if we could go with Scott's approach of having a flag to let cluster operators opt-in/out of the shell defaults. 

The main risk I see is tasks that have scripts that do not explicitly specify flags may behave differently in different Tekton installations. The workaround for this would be to ensure that script mode users are explicit about the flags they use. For the catalog tasks at least, we could enforce this by checking for this via Catlin

What do you think @vdemeester @abayer @imjasonh ?

**Comment by abayer** [comment]
I think removing the default `-x` was absolutely a good idea, and I definitely wish that we hadn't specified a default `-e` in the first place, but like you said, removing it now would be a breaking change. I waffle on whether we should remove it or not - having a feature flag to control whether the default is `-e` or not seems like the right way to go. I'd suggest we add that flag, defaulting to "yes, scripts get `-e`", with a deprecation notice that we'll be flipping that default to "no, scripts do _not_ get `-e`" in nine months, then a couple releases later, removing the flag entirely.

**Comment by imjasonh** [comment]
The reason for adding `-e` in the first place was to prevent folks from doing something like this:

```
script: |
  cat foo.txt
  echo foo.txt exists yay
```

...having seen lots of folks try to do a similar thing in GCB, which doesn't have script mode, and doesn't set any flags by default.

For comparison, GitHub Actions has a similar feature, where you can:

```
run: |
  cat foo.txt
  echo foo.txt exists yay
```

...and if the first line fails, the whole step fails, and the second line is never executed. I think this is a pretty good indication this is how folks expect a script to work, regardless of the semantics of shell flags.

I don't feel very strongly, but I don't think there's enough evidence suggested to overcome the inertia of having `-e` set by default. As far as I know there haven't been any bugs or issues or questions about it, and it's documented fairly well (we could always document it better!). If the opposition to it is mainly speculative or ideological, and not rooted in reported user confusion, then I think we should keep it as it is.

**Comment by dibyom** [comment]
The GH actions example makes sense.  The original reason for filing this was based on feedback from a GCB user trying this out :) I agree that there isn't enough evidence for making a breaking change but I do think that we should allow cluster operators/Tekton providers to allow the choice of the flags they set.

(Another piece of feedback that we got on the documenting it better front was that script mode could log out the flags its with so that users are aware of any default flags)

**Comment by imjasonh** [comment]
I'd definitely be interested in more such feedback, if you can share it.

I don't have a problem in theory with there being some feature flag to change the default script preamble, but I do worry about inconsistencies between some operators' installations and "vanilla" upstream Tekton, such that catalog tasks aren't guaranteed to work, or may work but have subtly different behavior.

**Comment by dibyom** [comment]
yeah my (not great) solution for catalog compatibility was to audit script mode tasks in the catalog and explicitly add them in  (and probably enforce this via catlin)

**Comment by dibyom** [comment]
> This probably doesn't scale if another platform decides they want to have some other different default preamble too.

I'm not sure I follow. The flag proposed is to control whether the `defaultScriptPreamble` is either`"#!/bin/sh\nset -e\n` or `"#!/bin/sh\n`.  The `defaultScriptPreamble` only takes effect if the script does not already contain a preamble, so it is possible to write tasks that work across all Tekton installations by simply adding a preamble in the task script. (My suggestion was that we could even enforce this for the catalog via catlin)

[Cloud Build script mode ](https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts#using_the_script_field) uses a default script preamble that does not use `set -e` and I'd like to have a Tekton installation that matches that behavior

**Comment by imjasonh** [comment]
> I'm not sure I follow. The flag proposed is to control whether the defaultScriptPreamble is either"#!/bin/sh\nset -e\n or "#!/bin/sh\n. 

My point was that `defaultScriptPreamble` would be a string, not a bool, so there could be any number of `defaultScriptPreamble`s configured for any number of Tekton platforms, so in order to know whether a catalog task will be compatible is to ensure it explicitly sets the preamble and doesn't get the default. Rather than encourage a lint check to maintain compatibility, what if we... just didn't introduce the incompatibility.

Task portability across Tekton platforms shouldn't depend on catlin's checks; I may not use the Tekton catalog or hub at all, and still want to have assurance that tasks that I defined a year ago will work on GCP-Tekton or Openshift Pipelines or SomeOtherTekton. If the API spec were still being maintained, I'd suggest documenting the expectation of the default script preamble there.

Compatibility with other non-Tekton APIs like GCB isn't something that should concern Tekton, any more than Tekton's script behavior being compatible with GitHub Actions or Travis or CircleCI. If GCB wants to have different behavior for a field that happens to be named `script`, and rely on Tekton to execute it, it's incumbent on them to carry the maintenance burden, not on Tekton. In translating the GCB `steps` into Tektonisms, can't you just prepend the preamble you want? (I swear I had code that did this at one point...)

**Comment by pritidesai** [comment]
Pipelines WG - @dibyom to close this after summarizing the discussion!
