### ISSUE TITLE
DinD sidecar: Docker daemon fails to start

### ISSUE THREAD

**Issue by HildaHay** [tektoncd/pipeline#4448]
# Expected Behavior

I'm trying to build and push a Docker image to a private repository, using a task with a DinD sidecar. It should successfully build the image and then push it to the repo.

# Actual Behavior

The task fails with the error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`. Initially, the pipeline executed correctly. After a few days, it began failing intermittently. Now, a few days later, it fails every time.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.21.0
Pipeline version: v0.31.0
Triggers version: v0.18.0
Dashboard version: v0.23.0
```

**Comment by sbwsg** [comment]
Hey @HildaHay thanks for the issue report. I think maybe the most concrete next steps I can offer here are to suggest creating a plain `Pod` with the containers in them configured similarly to the DinD setup you're using in your Task/TaskRun. If the issue persists in this setup then I think the problem is likely outside the control of Tekton, and if not then hopefully we'll be able to compare the working Pod with the one Tekton generates and come to some conclusions about where the issue might be.
