### ISSUE TITLE
How to make a pod to have QoS guaranteed?

### ISSUE THREAD

**Issue by ileixe** [tektoncd/pipeline#4533]
### Feature request

I made a `Task`  with specified resources (same requests/limit) and expected the pod would have guaranteed QoS, but as default init-containers injected by Tekton itself like `place-tools`, `step-init` have no resources parameters, the pod had Burstable QoS.

I'd like to have a way to make my Pod guaranteed. I think it may be possible to have such feature using LimitRange but it may be nicer and more intuitive to have the feature in Tekton.

### Use case

We have several tasks which requires high cpu/memory resources. We don't want to make them be killed as it also takes a long time to finish.

**Comment by lbernick** [comment]
Related to #2933: the lack of default resource requests/limits for init containers also affects pod creation when there are resourcequotas present in the namespace.

**Comment by lbernick** [comment]
Thanks for filing @ileixe! I think we don't want to support this feature right now unfortunately. The reason is that providing a guaranteed QoS for Tekton pods would require us to choose one set of resource requirements to serve as both the request and limit for our init containers. Setting the limit too low could result in (for example) a pod being OOMkilled, and setting it too high could cause performance/scheduling problems. In either case, the user would have no ability to modify the init container configuration. I'm also hesitant to make this configurable, because users shouldn't have to understand the internal details of Tekton init containers.

To address the issue I linked above, I'm planning on adding some requests/limits to our init containers (just not request = limit). I think we should see how that works before considering supporting this feature. It's possible that our init containers use so little resources that we don't need to worry about the problems I described, but it's hard to know right now.

I'm open to any suggestions you may have here!

**Comment by lbernick** [comment]
/unassign

I'm not actively working on this right now. However, this could be addressed by #4552, which adds default values for resource requests for init containers. Because there are drawbacks to that PR, one approach would be to add default values from a configmap, and allow the user to modify the configmap if there are any issues with the resource requests. This would also allow users to get a guaranteed qos.
