### ISSUE TITLE
TEP-0058: Graceful Termination - Promotions and Deprecation

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#4611]
In [TEP-0058: Graceful Termination](https://github.com/tektoncd/community/blob/main/teps/0058-graceful-pipeline-run-termination.md), we deprecated `PipelineRunCancelled` and added:
- `StoppedRunFinally` - To "stop" (i.e. let the tasks complete, then execute finally tasks) a Pipeline
- `CancelledRunFinally` - To "cancel" (i.e. interrupt any executing non finally tasks, then execute finally tasks)
- `Cancelled` - Same as today's `PipelineRunCancelled` - i.e. interrupt any executing tasks without running finally tasks

The above was released in [v0.25](https://github.com/tektoncd/pipeline/releases/tag/v0.25.0) in June 2021. 

The new fields are still in [alpha](https://github.com/tektoncd/pipeline/blob/302895b5a1ca45c02a85a9822201643c159fe02c/docs/install.md#alpha-features), so this issue tracks promoting them to beta. This issue also tracks deprecation and removal of `PipelineRunCancelled`.

**Comment by jerop** [comment]
@tektoncd/core-maintainers thoughts on promoting the new fields for graceful termination to beta? they were released in [v0.25](https://github.com/tektoncd/pipeline/releases/tag/v0.25.0) so they've been in use for 8 months so far

**Comment by pritidesai** [comment]
yup definitely 👍

**Comment by jerop** [comment]
discussed in API WG on 02-28-2022: general agreement to promote graceful termination to beta

**Comment by jerop** [comment]
thank you @vinamra28 for volunteering to help us with this 😀 

/assign @vinamra28

**Comment by vinamra28** [comment]
@jerop @pritidesai I guess removal of `PipelineRunCancelled` status won't be a good idea atm because old + current releases of CLI are still pointing to this status and removal of this would break previous versions of CLI, i.e., a user using an older version of CLI (specifically, N, N-1 and N-2) wouldn't be able to cancel their `PipelineRun` if they install latest Pipelines on their cluster. They'll have to force upgrade their CLI to latest in order to cancel their pipelines. My thought would be:
- Promote graceful termination from alpha to stable
- Notify the dependent tools(such as CLI, dashboard, etc) and users about the removal of `PipelineRunCancelled` status and give them time frame so that they can migrate
- After that given time frame remove `PipelineRunCancelled` support
Any thoughts?

**Comment by vinamra28** [comment]
created an [issue in CLI](https://github.com/tektoncd/cli/issues/1553) to track this

**Comment by lbernick** [comment]
/reopen

I think we still need to remove PipelineRunCancelledDeprecated
