### ISSUE TITLE
Promote Remote Resolution to beta

### ISSUE THREAD

**Issue by ghost** [tektoncd/pipeline#4710]
### Feature request

Remote resolution is currently behind the alpha feature gate in Tekton Pipelines. This issue is intended to track the work required to promote resolution into beta, removing the feature gate.

### Use case

Platforms and users would like to access Tekton resources in locations other than OCI registries or the cluster their taskruns and pipelineruns execute in.

### Criteria for Promotion

- [ ] Poll Pipeline maintainers for their preferred direction with resolution: integrate with pipelines + add out-of-box resolvers, keep entirely separate, go a different direction entirely.
- [ ] Once ^ is done, document the rest of the criteria for promotion here.

**Comment by sbwsg** [comment]
This is a Work-in-Progress comment describing some of the changes that would be expected if we move remote resolution to a feature of pipelines rather than an external project.

Currently Tekton Resolution maintains a "core" reconciler whose responsibility is to monitor _all_ `ResolutionRequests` and mark them Succeeded after a resolver successfully patches in the content of a pipeline/task. This core reconciler also performs book-keeping like initializing the ResolutionRequest's status and enforcing global timeouts so that a resolution request doesn't run forever.

Here is approximately the order of operations today for a `ResolutionRequest`:

```mermaid
sequenceDiagram
    Tekton Pipelines->>ResolutionRequest: CREATE resolution request for git resource
    ResolutionRequest-->>Tekton Resolution: WATCH triggers reconcile of Resolution's "core" reconciler
    Tekton Resolution->>ResolutionRequest: UPDATE with initial status
    ResolutionRequest-->>GitResolver: WATCH triggers reconcile of GitResolver
    GitResolver->>Git Repo: Clone & get file contents
    GitResolver->>ResolutionRequest: PATCH with contents of file from git
    ResolutionRequest-->>Tekton Resolution: WATCH triggers reconcile of Resolution's "core" reconciler
    Tekton Resolution->>ResolutionRequest: UPDATE with Succeeded status
    ResolutionRequest-->>Tekton Pipelines: WATCH triggers reconcile of pipeline w/ yaml from file
```

In a world where Tekton Pipelines merges remote resolution directly into its codebase, this flow would be simplified quite a bit:

```mermaid
  sequenceDiagram
    Tekton Pipelines->>ResolutionRequest: CREATE resolution request for git resource with initial status
    ResolutionRequest-->>GitResolver: WATCH triggers reconcile of GitResolver
    GitResolver->>Git Repo: Clone & get file contents
    GitResolver->>ResolutionRequest: UPDATE with contents of file from git + Succeeded status
    ResolutionRequest-->>Tekton Pipelines: WATCH triggers reconcile of pipeline w/ yaml from file
```

**Comment by vdemeester** [comment]
Note: we also need to support Remote Resolution for `Task` specs.

**Comment by lbernick** [comment]
Potential improvement for remote resolution: If you try to use remote resolution without both the resolution project and the correct resolver installed, your pipelinerun will just hang until it times out. I'm not sure if it's possible for the pipelinerun/taskrun reconcilers to know if you have resolution installed, or for the resolution reconciler to know if you have the correct resolvers installed, but if so it would be helpful to return an error in these cases instead.

**Comment by chitrangpatel** [comment]
> Potential improvement for remote resolution: If you try to use remote resolution without both the resolution project and the correct resolver installed, your pipelinerun will just hang until it times out. I'm not sure if it's possible for the pipelinerun/taskrun reconcilers to know if you have resolution installed, or for the resolution reconciler to know if you have the correct resolvers installed, but if so it would be helpful to return an error in these cases instead.

At the API WG call we discussed the possibility of integrating tekton resolution into pipeline. I dont think anyone at the WG expressed ideas against it. If anything, the team wanted to merge the two projects. Since many team members were away this week, the decision was not finalized (I still need to send out an email to the maintainers of `pipeline`). But, if we do take that route and merge the two projects, we might not need to worry about this?

**Comment by lbernick** [comment]
> > Potential improvement for remote resolution: If you try to use remote resolution without both the resolution project and the correct resolver installed, your pipelinerun will just hang until it times out. I'm not sure if it's possible for the pipelinerun/taskrun reconcilers to know if you have resolution installed, or for the resolution reconciler to know if you have the correct resolvers installed, but if so it would be helpful to return an error in these cases instead.
> 
> At the API WG call we discussed the possibility of integrating tekton resolution into pipeline. I dont think anyone at the WG expressed ideas against it. If anything, the team wanted to merge the two projects. Since many team members were away this week, the decision was not finalized (I still need to send out an email to the maintainers of `pipeline`). But, if we do take that route and merge the two projects, we might not need to worry about this?

This would definitely solve the problem of the user needing to install the resolution project separately, but it would still be nice to return an error if they are trying to use a resolver they don't have installed.

**Comment by vdemeester** [comment]
> At the API WG call we discussed the possibility of integrating tekton resolution into pipeline. I dont think anyone at the WG expressed ideas against it. If anything, the team wanted to merge the two projects. Since many team members were away this week, the decision was not finalized (I still need to send out an email to the maintainers of `pipeline`). But, if we do take that route and merge the two projects, we might not need to worry about this?

I think this is not about where the code lives but how the api/controller behave. Today, if you submit a `PipelineRun` (or `TaskRun`) with a non-existent resolver (`resolver: foo-is-bar`), it will hang out for the pipelinerun timeout (so by default 1h).. Although it *could* make sense as, maybe the resolver will be available in that time, I don't think we handle that case today. So having a very small timeout for the resolver to answer and timeout otherwise would make sense yes. And this is indepedent of where the code lives 👼🏼

**Comment by abayer** [comment]
Ok, another thing Resolution needs - unit tests. The reconciler has none, so while I've verified that a `PipelineRun` will fail if the `ResolutionRequest` fails, I can't actually verify that the `ResolutionRequest` will fail!

**Comment by chitrangpatel** [comment]
I'm summarizing the action items here:

### Criteria for Promotion
* [ ]  Poll Pipeline maintainers for their preferred direction with resolution: integrate with pipelines + add out-of-box resolvers, keep entirely separate, go a different direction entirely.
* [ ]  Unit tests for Resolution. This is important before merging the two projects so that the resolution codebase is not under-tested.
* [ ]  Somehow Inform the `pipelinerun/taskrun reconcilers` that the resolution project (after merging into pipelines, this is irrelevant) or the resolvers are installed.
* [ ] Prioritize and tackle [Issues](https://github.com/tektoncd/resolution/issues) in the resolution project. Note that it makes sense to go after some of those after integrating `resolution` into `pipeline`. Once integrated, those issues can be transferred to the `pipeline` repo.
* [ ] `Custom tasks` : Dogfooding.
* [ ] Collect feedback on usage from the users and solve hidden bugs over <?> extended
 time

**Comment by vdemeester** [comment]
> What about resolvers? They seem custom and can be created according to use cases. Should they be integrated into pipelines as well?

Some should probably (cluster task / pipeline, maybe the git resolver), but most might be better off living outside indeed.

> Somehow Inform the pipelinerun/taskrun reconcilers that the resolution project (after merging into pipelines, this is irrelevant) or the resolvers are installed (see https://github.com/tektoncd/pipeline/issues/4710#issuecomment-1128618378).

I don't think it's about "informing" but just about "erroring" out properly in case we are trying to use a resolver that doesn't exists. We might even want to do this in the admission controller.

> * `Custom tasks` : Dogfooding.

Do you mean "Remote resolution" here instead of Custom Task ?

**Comment by chitrangpatel** [comment]
> > What about resolvers? They seem custom and can be created according to use cases. Should they be integrated into pipelines as well?
> 
> Some should probably (cluster task / pipeline, maybe the git resolver), but most might be better off living outside indeed.
> 
I agree. 
> > Somehow Inform the pipelinerun/taskrun reconcilers that the resolution project (after merging into pipelines, this is irrelevant) or the resolvers are installed (see [#4710 (comment)](https://github.com/tektoncd/pipeline/issues/4710#issuecomment-1128618378)).
> 
> I don't think it's about "informing" but just about "erroring" out properly in case we are trying to use a resolver that doesn't exists. We might even want to do this in the admission controller.
> 
> > * `Custom tasks` : Dogfooding.
> 
> Do you mean "Remote resolution" here instead of Custom Task ?

Yes, I meant remote resolution.

**Comment by abayer** [comment]
@jerop and I chatted about the resolvers question on Friday - I'd advocate for moving the existing git and bundle resolvers into Pipeline, along with an eventual catalog resolver, since those all seem pretty fundamental. But additional resolvers going forward (like the GitHub-specific one I intend to write eventually, inspired by https://github.com/tektoncd/resolution/issues/42) should, IMO, be outside the Pipeline repo.

That does bring up another matter relating to the catalog - we do need a way to provide catalogs of custom tasks and resolvers in the catalog. But that's not relevant to Remote Resolution going to beta. =)

**Comment by vdemeester** [comment]
Added this to the v1 project as I would really want to have this in beta at least so that we can deprecate `taskref.bundle` and rely on remote resolver for oci bundle.

**Comment by lcarva** [comment]
Since there's agreement in deprecating `taskRun.spec.taskRef.bundle` and `pipelineRun.spec.pipelineRef.bundle`, should we add the "bundle" resolver to the list of out-of-box resolvers?

**Comment by afrittoli** [comment]
I'm rather late to the discussion here, but I still wanted to mention that something that I think we should have in remote resolution is support for bundles, i.e. a way for a parent resource to use "relative references" for children, as long as they belong to the same bundle.

That was one of the most requested changes to the OCI bundles feature that we have today.
The only place where we have this feature today is in-cluster resources - a `Pipeline` may reference to `Tasks` without specifying where the `Tasks` come from, it's a relative reference which implies "the same place where the `Pipeline` comes from i.e. the cluster.

This is something we can add after the beta as well, as I don't expect it would really require changes to the API surface, but I wanted to add it here to start gathering feedback about it.

**Comment by abayer** [comment]
Interesting - that'll need new syntax for "this `Task` needs to be resolved, so here's where to find it based on its name/type/version (for the Hub) and the `Pipeline`'s resolution parameters".

**Comment by vdemeester** [comment]
Could it be something the resolver support itself ? For example, a `Pipeline` in a bundle could use the `bundle` resolver that would make the bundle resolver *resolving* the `Pipeline` to also resolve the `Task` from the same `bundle`, in case the `bundle` parameter is missing, or is using a special syntax ? We could even envision that the resolver, when seen "normal" `TaskRef` could list all the `bundle` layers (aka resources), find the *in-the-bundle* referenced `Task` and mutate the `Pipeline` to use the `bundle` resolver instead.

In a gist, I think it is a feature on the resolvers themselves, and not necessary on "tekton resolution".

**Comment by abayer** [comment]
So this is a bunch of interesting questions!

I'm pretty sure (I'm going to add e2e tests for this today) that if you've got a `resolver` reference for a `PipelineTask` inside a `Pipeline` that gets resolved remotely, it'll work just fine. So what's "missing" is automatically resolving `Task`s without them needing to have an explicit resolver - automatically detecting when we've got an unresolved `Task` inside a resolved `Pipeline` and trying to resolve that `Task` using the same method as the `Pipeline`.

It gets a bit more complex for resolvers other than `bundles` - there, if we already know the OCI bundle containing both the `Pipeline` and the `Task`, as well as the name of the `Task`, we've already got the information we need. So doing something like Vincent's talking about where we first try to resolve `some-task` within `bundle-pipeline` inside the same bundle that the `Pipeline` came from should be doable implicitly, same with the `cluster` resolver (assuming the `Task` is in the same namespace as the `Pipeline`).

The `hub` and `git` resolvers don't seem to have such a simple trick, though - `hub` needs a version for the `Task`, not just the name, and `git` needs to know the path to the resource in the repo. But I don't think that should hold up implementing this behavior for `bundles` and `cluster` - @afrittoli, could you open an issue for this?

**Comment by abayer** [comment]
(and down the road, it may make sense for a `PipelineRun` to be able to say "here are the default org/repo (or URL for the anonymous clone approach) and revision for all `Pipeline`s and `Task`s within this `PipelineRun` which are marked as to be resolved by the `git` resolver", so that all that needs to be specified on the `pipelineRef` and the `PipelineTask`s would be the `pathInRepo` for the individual `Task`)

**Comment by abayer** [comment]
Also, I keep thinking that it may make sense to eventually add real fields (with relevant structs) to `ResolverRef` for the built-in resolvers, so that you can just do 
```
pipelineRef:
  git:
    org: foo
    repo: bar
    revision: main
    pathInRepo: a/b/c.yaml
```

Rather than the more elaborate generic params approach of
```
pipelineRef:
  resolver: git
  params:
  - name: org
    value: foo
  - name: repo
     value: bar
  - name: revision
     value: main
  - name: pathInRepo
    value: a/b/c.yaml
```

We could only support the `git: ...` syntax for built-in resolvers, but for those, we'd be able to do admission control-time validation, a simpler syntax, `PipelineRun`-wide defaults, etc.

I'm gonna open an issue for this. =)
