### ISSUE TITLE
 add functionality that cancels the TaskRun when the pod encounters an error such as InvalidImageName

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/pipeline#4890]
### Feature request
Add functionality to cancel the taskrun when the pod encounters an error that maybe can  not be fixed like InvalidImageName

### Use case

When the taskrun related pod  is pending for some image error, we should let users choose if they want to cancel the taskrun  or not. For example,  when the pod is pending for InvalidImageName the user may want to cancel the taskrun.

related discussion: https://github.com/tektoncd/pipeline/pull/4846#discussion_r877065970

**Comment by yuzp1996** [comment]
related issue: https://github.com/tektoncd/pipeline/pull/4618

**Comment by imjasonh** [comment]
I don't think it should be possible to create a TaskRun with an invalid image name, since we parse and lookup the requested image in order to resolve the entrypoint.

I suppose it's possible that if the image is specified by digest and the command is set, we might not do the lookup (I'm not sure, I'd have to check), and that in that case if the specified image name is invalid, we'd let it proceed and create the Pod, but in general I think the answer is to validate and fail early in that case instead of letting the Pod run until the image name can be corrected.
