### ISSUE TITLE
Unable to run task with step named "init"

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/pipeline#5099]
```
Pipeline version: v0.32.4
Triggers version: v0.19.0
```
After update(0.28? -> 0.32.4) when I try to run task with step named "init", my TaskRun fails with:
```
failed to create task run pod "lib-operator-database-0ftdo7-init": Pod "lib-operator-database-0ftdo7-init-pod" is invalid: spec.initContainers[1].name: Duplicate value: "step-init". Maybe missing or invalid Task platform/init-pipeline
```
I'd expect to be free in selection pipeline/task/step names, they should not be limited to not interfere with reserved words(may be internal steps could be named with some obfuscation - not "init" but "init-{{ somehash }}")

**Comment by afrittoli** [comment]
@vdemeester ^^^

**Comment by vdemeester** [comment]
@dbazhal can you share the `Task` definition ? (even redacted). This would not happen with more recent versions as the init container is not using `init` anymore, but it's just reporting the problem to another name.
I do agree we should make sure internal container do not interfere with any task step though.

/kind bug
/assign

**Comment by dbazhal** [comment]
/remove-lifecycle stale
/lifecycle frozen
sounds like an opportunity?)

**Comment by ericzzzzzzz** [comment]
The problem should be fixed by this change https://github.com/tektoncd/pipeline/pull/4826/files#diff-82b3e87876a8c03277b96958e0bbae05eda555b2196a54b02115a3268095fe31R419  The naming selections should be free for steps with tekton version >= v0.36.0, as when constructing task containers, tekton always prepends 'step' to the user-defined step name. And it's been a year since the last reply, probably it's safe to close the issue? @dibyom

**Comment by dibyom** [comment]
yup, thanks for looking into this @ericzzzzzzz 

/close
