### ISSUE TITLE
Critical CVE in go-restful CVE-2022-1996

### ISSUE THREAD

**Issue by roelvdberg** [tektoncd/pipeline#5114]
Authorization Bypass Through User-Controlled Key in GitHub repository emicklei/go-restful prior to v3.8.0.

Our scanners found [CVE-2022-1996](https://nvd.nist.gov/vuln/detail/CVE-2022-1996), this is an authorization issue with the go-restful module.
What is the impact of this CVE on ArgoCD and can it be fixed?

The images containing the CVE are:
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter

> Retrieval of a user record occurs in the system based on some key value that is under user control. The key would typically identify a user-related record stored in the system and would be used to lookup that record for presentation to the user. It is likely that an attacker would have to be an authenticated user in the system. However, the authorization process would not properly check the data access operation to ensure that the authenticated user performing the operation has sufficient entitlements to perform the requested data access, hence bypassing any other authorization checks present in the system. For example, attackers can look at places where user specific data is retrieved (e.g. search screens) and determine whether the key for the item being looked up is controllable externally. The key may be a hidden field in the HTML form field, might be passed as a URL parameter or as an unencrypted cookie variable, then in each of these cases it will be possible to tamper with the key value. One manifestation of this weakness is when a system uses sequential or otherwise easily-guessable session IDs that would allow one user to easily switch to another user’s session and read/modify their data.
https://avd.aquasec.com/nvd/2022/cve-2022-1996/

**Comment by imjasonh** [comment]
I believe this package is only depended on at development-time, and not at runtime. It seems to be used via kubernetes code generation.

```
$ go mod why ./cmd/controller github.com/emicklei/go-restful
github.com/tektoncd/pipeline/hack/spec-gen
k8s.io/kube-openapi/pkg/common
github.com/emicklei/go-restful
```

As such, I believe the vulnerability doesn't affect users of Tekton. I also don't believe the vulnerability affects Tekton's CI usage, since code is expected to be generated by developers, and is only checked by CI. The CI environment's configuration isn't under user control until it's been code reviewed by 2+ Tekton maintainers.

That being said, we should track whatever dependencies need to be updated so we don't depend on a vulnerable version of the package at all, so we can be totally sure we're unaffected.
