### ISSUE TITLE
TEP-0114: Custom Tasks Beta - Support `v1beta1.CustomRun`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5153]
In [TEP-0114: Custom Tasks Beta][tep-0114], we proposed migrating `Custom Tasks` and `Runs` to beta. 

Moving `v1alpha1.Run` to `v1beta1.CustomRun` is a required API change in [TEP-0114: Custom Tasks Beta][tep-0114]. This issue tracks this API change.

[tep-0114]: https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md

**Comment by XinruZhang** [comment]
Putting a note here as a reminder: all the references about `v1alpha1.Run` should be migrated to `v1beta1.CustomRun`, for example: https://github.com/tektoncd/pipeline/blob/f1b68123b2de6c5fe05b0db3a98ca77b56e8a91f/pkg/apis/pipeline/v1alpha1/run_types.go#L101-L107

Thanks for @lbernick 's input!

**Comment by pritidesai** [comment]
Pipeline WG - Blockers:

- What should go in RunSpec?
- How to support v1alpha1 Run along with v1beta1 CustomRun?

/cc @ScrapCodes

**Comment by vdemeester** [comment]
On the second question, I would ask a question to the question : do we even want to support both ? `v1alpha1.Run` is alpha, we can pretty much do whatever. As already mentionned during a WG, if we give a timeline when `tektoncd/pipeline` will start creating `v1beta1.CustomRun` instead of `v1alpha1.Run`, announce it, it should give enough time for current `CustomTask` project to update to handle `v1beta1.CustomRun` (in addition to `v1alpha1.Run` or not — but that's on those project, not `tektoncd/pipeline` to support both APIs, or not).
