### ISSUE TITLE
Produce `Results` from `PipelineTasks` fanned out in a `Matrix`

### ISSUE THREAD

**Issue by jerop** [tektoncd/pipeline#5266]
In [TEP-0090: Matrix](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md), we introduced `Matrix` to support fanning out a `PipelineTask` with different combinations of `Parameters`.

This issue tracks the work to produce `Results` from `PipelineTasks` fanned out in a `Matrix`, which was a non-goal in [TEP-0090](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#non-goals). This work was scoped out as we waited for [TEP-0075: Object Parameters and Results](https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md) and [TEP-0076: Array Results](https://github.com/tektoncd/community/blob/main/teps/0076-array-result-types.md) to land. See [TEP-0090: Matrix - Results](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#results-from-fanned-out-pipelinetasks) for further details.

The design work is ongoing in https://github.com/tektoncd/community/pull/753.

**Comment by Tomcli** [comment]
The use case we have is hyperparameter turning for machine learning where we need to aggregate all the results from all the tasks and find/compute the desire result. We probably will not use the Tekton native functionality because in Kubeflow we have hundreds of loop/matrixed tasks. So Kubeflow Pipelines use the metadata service to store each task result into Kubeflow's database in this case instead of passing hundreds of results into one task in the pod spec.

**Comment by jerop** [comment]
@EmmaMunley all the use cases for `Matrix` in [TEP-0090](https://github.com/tektoncd/community/blob/main/teps/0090-matrix.md#use-cases) apply to the need for `Results` from fanned out `PipelineTasks`

Just looking at the first use case from TEP-0090, the [Kaniko Task](https://github.com/tektoncd/catalog/tree/main/task/kaniko/0.5) produces a `Result` named "image-digest" -- how do get those `Results` when 3 TaskRuns were created from the `PipelineTask`?

**Comment by jerop** [comment]
There were prior discussions about this issue in https://github.com/tektoncd/community/pull/753 but closed the PR because I didn't have the capacity to see it through, maybe that'd be a good starting point @EmmaMunley

**Comment by pritidesai** [comment]
We have discovered multiple concerns and some suggestions during designing an access to a result from an individual instance of fanned out tasks. We decided to descope the existing proposal so they no longer are applicable. I am highlighting them here so that we do not loose them when revisit them next time.

Concerns:

https://github.com/tektoncd/community/pull/1047#discussion_r1280838037
https://github.com/tektoncd/community/pull/1047#discussion_r1280843470

Suggestions:

https://github.com/tektoncd/community/pull/1047#discussion_r1280844246
https://github.com/tektoncd/community/pull/1047#discussion_r1281042106

We have an approval from the community to go ahead and support such use case:

![Screenshot 2023-08-07 at 11 01 14 AM](https://github.com/tektoncd/pipeline/assets/206285/23ee3842-316f-4186-ab0f-0b5958e6b457)

**With Matrix:**

![Screenshot 2023-08-07 at 11 01 24 AM](https://github.com/tektoncd/pipeline/assets/206285/59ca4ab5-1017-48ab-8920-f21afb28a100)

**Comment by EmmaMunley** [comment]
#7167 closes this issue
/close

**Comment by jerop** [comment]
Thank you @EmmaMunley 🎉 

/close
