### ISSUE TITLE
Cannot delete a `PipelineRun` because of unknown field "resourceRef" 

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/pipeline#5317]
# Expected Behavior

`PipelineRuns` can be deleted

# Actual Behavior

```shell
$ tkn pr delete request-pr-docs-reviewer-wjfgm -n tekton-ci
Are you sure you want to delete PipelineRun(s) "request-pr-docs-reviewer-wjfgm" (y/n): y
Error: failed to delete PipelineRun "request-pr-docs-reviewer-wjfgm": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "resourceRef"
```

# Steps to Reproduce the Problem

1. The `PipelineRun` exists in the dogfooding cluster for now
2. The full yaml: https://gist.github.com/d32565f45c977953e9ee4f97fe439999

It's likely that the `PipelineRun` was executed on an older version of Tekton than the one I'm trying to delete it with.

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12-gke.2200", GitCommit:"6c11aec6ce32cf0d66a2631eed2eb49dd65c89f8", GitTreeState:"clean", BuildDate:"2022-05-20T09:29:14Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Client version: 0.25.0
Chains version: v0.8.0
Pipeline version: v0.37.1
Triggers version: v0.20.2
Dashboard version: v0.28.0
```

**Comment by afrittoli** [comment]
I wonder if we really need to run the webhook on deletion, or if we could skip it entirely there? 
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-rules

**Comment by abayer** [comment]
That should actually be dealt with by https://github.com/tektoncd/pipeline/commit/d91ce06c326cee7645a33e469e2fb21a814f21f3, which will be in v0.39.

**Comment by afrittoli** [comment]
Oh, interesting... I wonder why not run the validation on delete instead of skipping in the code based on the API.

**Comment by afrittoli** [comment]
Fixed by https://github.com/tektoncd/pipeline/pull/5210, but I think we may need to cherry-pick?

**Comment by abayer** [comment]
I'm not 100% sure #5210 does fix this particular one, since it feels like we'd have to get through the decoding to get to the skip-if-deleting logic...

**Comment by abayer** [comment]
And yeah, I think skipping validation for deletion feels more right to me.

**Comment by abayer** [comment]
Looks like https://github.com/tektoncd/pipeline/blob/1b080e3fd15ad98f7bb708296fefa875d69157a8/cmd/webhook/main.go#L105 is relevant?

**Comment by abayer** [comment]
related: #297

**Comment by vdemeester** [comment]
I don't skipping the validation fixes this though. Mainly because the error happens "prior" to the validation. `decoding request failed: cannot decode incoming old object: json: unknown field "resourceRef"` is a "json" decoding (unmarshalling right ?) error, which happens *before* actually getting into the admission controller code.

> Oh, interesting... I wonder why not run the validation on delete instead of skipping in the code based on the API.

Yeah, I think we never really looked into it. We use to validate on delete (which sounds a bit weird), but I agree that not even "registering" to validate on delete would be better than skipping it in code.

**Comment by mrobson** [comment]
Another example here related to the same root issue.

serviceAccountNames was deprecated and then removed.

If you upgrade to 0.37+ and did not remove it from your PipelineRun, you can no longer delete that old PipelineRun due to this issue.

`admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "serviceAccountNames"`

**Comment by vdemeester** [comment]
@imjasonh so, I don't think `knative/pkg` allows us to say we do not want to have the webhook registered for the `DELETE` operation. So this means we need to propose some changes upstream for this.
