### ISSUE TITLE
Redundant `md.backup` file by `update-reference-docs.sh`

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5417]
# Expected Behavior
The `./hack/update-reference-docs.sh` script should have deleted the `pipeline.md.backup` file once the script is done.
# Actual Behavior
There is a redundant `pipeline.md.backup` file generated.

# Steps to Reproduce the Problem

1. Currently occurred in `go1.19 darwin/arm64` and `go1.19 linux/amd64` when running `./hack/update-reference-docs.sh`

Related PR: https://github.com/tektoncd/pipeline/pull/5324

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.13-gke.900", GitCommit:"8f8dd9d389916c66dd26704a96f1ab4c5776f9df", GitTreeState:"clean", BuildDate:"2022-06-06T09:24:36Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:
```
Client version: 0.24.0
Pipeline version: devel
```

Looping in @vsinghai for visibility.

**Comment by abayer** [comment]
This file is being generated as a result of https://github.com/tektoncd/pipeline/commit/8381d0d9d83326724ab260dc7ab36632afb1451f

This was done to make the `sed` call work on Macs. I have `gsed` aliased to `sed` on my Mac, so I didn't hit whatever the problem was on Macs myself when setting this up. I'm not sure if/how one would call `sed` to not create a backup file, because `sed` has always been a mystery to me. =)

**Comment by dibyom** [comment]
maybe we just rm  the .backup file once we are done?

**Comment by dibyom** [comment]
or just add it to the .gitignore :)

**Comment by abayer** [comment]
heehee. =)

**Comment by vsinghai** [comment]
I believe this issue can be closed now, thanks @JeromeJu!

**Comment by abayer** [comment]
Yup, closing.
