### ISSUE TITLE
Unable to list pipeline and pipeline runs

### ISSUE THREAD

**Issue by iabughosh** [tektoncd/pipeline#5512]
# Expected Behavior
To list actual pipeline, pipeline runs and to show pipeline run logs

# Actual Behavior
Unable to find pipeline and pipeline runs, k8s responds with an error.

> Error: the server could not find the requested resource (get pipelineruns.tekton.dev hello-goodbye-run)

# Steps to Reproduce the Problem

1. Following tekton [getting started tutorial](https://tekton.dev/docs/getting-started/)
2. execute command `tkn pipelinerun logs hello-goodbye-run -f -n default' after creating pipeline and pipeline run`
3. Getting this error `Error: the server could not find the requested resource (get pipelineruns.tekton.dev hello-goodbye-run)`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

> 
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

tkn version :

> Client version: 2020-04-01T10:57:38Z
> Pipeline version: unknown

kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}' output :
`v0.39.0`

OS infromation : 

> NAME="Pop!_OS"
> VERSION="22.04 LTS"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 22.04 LTS"
> VERSION_ID="22.04"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=jammy
> UBUNTU_CODENAME=jammy
> LOGO=distributor-logo-pop-os

**Comment by ernestang98** [comment]
Just encountered this error myself. 

This is my version of Ubuntu that I am trying to run tkn on

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04

Try uninstall and re-installing tkn

Install tkn via:

curl -LO https://github.com/tektoncd/cli/releases/download/v0.27.0/tektoncd-cli-0.27.0_Linux-64bit.deb
sudo dpkg -i tektoncd-cli-0.27.0_Linux-64bit.deb

Instead of:

sudo apt update;sudo apt install -y gnupg
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA
echo "deb http://ppa.launchpad.net/tektoncd/cli/ubuntu jammy main"|sudo tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list
sudo apt update && sudo apt install -y tektoncd-cli

The first time i tried installing tkn was using apt, and I encountered the very same error. Somehow, removing it and installing it via the deb package seemed to work for me. Lmk if it is the correct fix for you!

**Comment by kimiyasharifi** [comment]
@ernestang98

thanks this answer work for me

**Comment by vieenodp** [comment]
Installed tekton , using kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml 
Then installed git-clone and kaniko. Created one task and pipeline;
I get following errors , how kubectl shows the task and pipeline properly.  
root@kind:~/tekton-ci/base# tkn t list
Failed to list tasks from default namespace 
Error: the server could not find the requested resource (get tasks.tekton.dev)
