### ISSUE TITLE
Support timeout in Pipeline

### ISSUE THREAD

**Issue by egaudet-casa** [tektoncd/pipeline#5600]
### Feature request

Provide a way to configure an individual Pipeline's default timeout.

### Use case

In order to support different Pipelines with different default timeouts and not have to resort to a single global value.  PipelineRun can override it, but the Pipeline designer should be able to provide a default.

An example is an easy way to "start" a Pipeline through a UI like Openshift Pipelines where you need a higher timeout than the global default. Even if the UI provided input, knowing the per-pipeline override and inputting it each time is not a good UX.

**Comment by aleskandro** [comment]
It'd be great to have the default PipelineRun timeout set to a smarter value than the [default one from the config](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/pipelinerun_defaults.go#L39-L45): for instance, one can calculate the sum of the longest path's task timeouts. 
It would be an upper bound ignoring the `when` clauses, and other concerns will need to be addressed, but it would provide a better UX IMO.

The timeout field in the Pipeline seems a baseline to support the use case above, but since Tasks and TaskRuns already have a Timeout field, a user could expect them to drive the PipelineRun timeout.
