### ISSUE TITLE
Integration tests for upgrading API versions

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5627]
Tekton already has integration tests that check that a newer version of Tekton Pipelines can be installed on a cluster with existing Tekton CRDs. Improving these tests is tracked in https://github.com/tektoncd/pipeline/issues/5193.

We would also like to add integration tests that ensure users can upgrade API versions and that webhook conversion is working properly. (We already have conversion unit tests but conversion integration tests are also helpful.) These tests can use the Go client to create a v1beta1 version of a CRD and request the v1 version of it and compare them, and vice versa. They can run during CI or as periodic tests (the way we run existing upgrade tests).

cc @afrittoli

**Comment by afrittoli** [comment]
Thank you @lbernick - this is really useful.
Some more we had in the past with API changes (but not API version changes) are not being able to update or delete an existing resource after an upgrade because of webhook validation changes.
If the `v1` and `v1beta` webhook behaviour is not in sync, this could cause problems with resources that may become stuck in a bad state which can only be solved by temporarily bypassing the webhook. I'm not sure yet how to best test for this, but I wanted to at least mention the issue.

**Comment by JeromeJu** [comment]
Wondering if we should only add the tests converting v1 to v1beta1 once the v1 is changed to the storage version?

**Comment by lbernick** [comment]
Since users will be able to request both versions of the CRD as soon as they are served, it probably makes sense to add these tests as soon as they are served rather than waiting for the storage version to change. Clients have no way of knowing what the storage version is (AFAIK-- users can look at the CRD definitions but I don't think you can specify it in the client?), so I don't think it makes sense for these tests to rely on what the storage version is somehow.

**Comment by JeromeJu** [comment]
Thanks Lee, updated in the latest commit in #5579
