### ISSUE TITLE
Per Feature Feature Flags

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#5632]
### Feature request

[TEP-033](https://github.com/tektoncd/community/blob/main/teps/0033-tekton-feature-gates.md) proposed an `enable-api-fields` flag for features that require an API field. This allows us to group and enable/disable all "alpha"/"beta" features together.

An alternative approach is having a way to enable/disable each feature by via its own flag (such as the approach taken by [Kubernetes feature gates](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/feature-gates.md))

This issue is for tracking experimentation for per feature feature gates.

### Use case

1. A user would like to enable a specific alpha feature but not any other alpha features

**Comment by dibyom** [comment]
One though I just had - per TEP-033, fields that are behind an alpha/beta flag can be gradually transitioned from alpha to beta to GA. For features that are not controlled by a field, TEP-033 says they should have their own flag. But I do not think it is possible to move them gradually from alpha to beta to GA and instead they must either be enabled or disabled within a particular API version

**Comment by Yongxuanzhang** [comment]
comment for tracking this issue

**Comment by Yongxuanzhang** [comment]
I encounter this issue when implementing trusted resources in https://github.com/tektoncd/pipeline/pull/5581 
We have a feature flag `ResourceVerificationMode` to let users choose from skip, enforce and warn. So if it is set to skip the feature will not be enabled. 
This is an alpha feature and it may not be ideal to let users enable 2 flags (ResourceVerificationMode and enable-api-fields).

**Comment by dibyom** [comment]
@chuangw6 also mentioned the same thing for his ConfigSource status field proposal

**Comment by chuangw6** [comment]
> We have a feature flag `ResourceVerificationMode` to let users choose from skip, enforce and warn. So if it is set to skip the feature will not be enabled.

Thanks @dibyom. This is a good idea.
https://github.com/tektoncd/pipeline/pull/5670 is the implementation that adds a dedicated feature flag to control the `provenance` field in taskrun/pipelinerun status.

**Comment by afrittoli** [comment]
To give extra background, the reason we decided to have a single flag instead of per-feature ones is the amount of testing that that would require, because while features are (often) clearly separated from one another at the API level, they may be more intertwined in the controller code - so enabling one feature out of 10 may behave differently from enabling all 10. 

The alternative to feature flags (whether per feature or just one) would be to create `v2alphaN` APIs and `v2betaN` APIs.
Multiple features would be included in each alpha and beta version, similar to the way features are grouped under one flag today.

About k8s feature flags, I may be wrong but I think they mainly relate to back-end behaviour, even though there is no clear distinction documented like for Tekton.

If we decide to have feature-specific flags for all features, we shall document the test strategy. I believe each feature should then come with a dedicated set of e2e tests (like today) to be executed in an environment with only that feature enabled. 
We could replace the current alpha test with an env where all features in alpha state are enabled.

**Comment by dibyom** [comment]
> To give extra background, the reason we decided to have a single flag instead of per-feature ones is the amount of testing that that would require, because while features are (often) clearly separated from one another at the API level, they may be more intertwined in the controller code - so enabling one feature out of 10 may behave differently from enabling all 10.

I agree, the testing story is complicated but I don't think that by itself should be why we should only have a single flag. The most common use case for alpha features is to try out a single alpha feature, not all of them altogether. 

Feature flags implementations being intertwined is not great either - wherever possible a feature flag should only control the behavior of that specific feature and nothing else. I agree this can be tricky - K8s checks for this sort of thing in their [Production Readiness Reviews](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/feature-gates.md#lifecycle) - we could do something similar and have some guidelines to specifically check for this when adding a new feature gate.

From a testing standpoint I think a reasonable option is to test will all feature flags on and all of them off (like we do today). We can document this and users who turn on only a subset of the flags can be responsible for their own testing.

> The alternative to feature flags (whether per feature or just one) would be to create v2alphaN APIs and v2betaN APIs.
Multiple features would be included in each alpha and beta version, similar to the way features are grouped under one flag today.

In theory yes, but I think the complexity involved in maintaining N active API versions is far greater than just having feature flags (e.g. there can only be one api version that is stored so that version has to be able to represent info from all N API versions)

> About k8s feature flags, I may be wrong but I think they mainly relate to back-end behaviour, even though there is no clear distinction documented like for Tekton.

I think many of the feature gates are for backend features but there also user facing ones such as the PodSecurity one that gates the new PodSecurityAdmission feature which replaces PodSecurityPolicies

> If we decide to have feature-specific flags for all features, we shall document the test strategy. I believe each feature should then come with a dedicated set of e2e tests (like today) to be executed in an environment with only that feature enabled.

💯 . I'm not sure if it is realistic to test every combination of flags but we can definitely clearly state what we test and users who use a different subset of flags can be responsible for their own testing. That being said, I do think we should do our best to make sure a feature gate is only scoped to that particular feature.

> We could replace the current alpha test with an env where all features in alpha state are enabled.

Agreed!

**Comment by lbernick** [comment]
I wanted to share [this doc](https://docs.google.com/document/d/1roVAHyF7eWZAccmCKw7MXYUNgx4BCDSXF2IMS8h10oY/edit?resourcekey=0-x6Tw2qz1SpCIPhbec6Qa2A#) with some thoughts from a k8s maintainer on some of the issues they've run into w/ per-feature flags. A lot of it is related to rollbacks which I think we've been less concerned about than k8s has. To make rollbacks easier, they drop unsupported fields rather than rejecting CRDs containing them, as we do. I still think we should implement per-feature flags, but this doc could help us understand what issues we might run into.

The issues are basically:
- adding version validation in implementation in addition to apiserver operations (this has caused problems for us as well with "enable-api-fields", see https://github.com/tektoncd/pipeline/issues/6616)
- concerns about rolling back from a more stable implementation of a feature to a less stable implementation of a feature
- different versions of k8s or values of feature flags between apiserver and node (not relevant for us)
- minimal feedback on alpha features

**Comment by JeromeJu** [comment]
Looks like we can also close this with the completion of https://github.com/tektoncd/pipeline/pull/7090 at v0.53.0 milestone.
