### ISSUE TITLE
Add validation for JSON annotations stored in v1 CRDs

### ISSUE THREAD

**Issue by JeromeJu** [tektoncd/pipeline#5805]
This is brought up in the api WG and we would like to have validations of the annotations serialized for `resources` to be valid when converting down from `v1` to `v1beta1`. The validations need to make sure that the controller doesn't panic if it attempts to deserialize invalid JSON from annotations.

The goal of this issue is to make sure the conversion would not cause any error. Can be closed after it is being tested with invalid annotations cases.

_Follow up issue of https://github.com/tektoncd/pipeline/issues/5785_

**Comment by lbernick** [comment]
If the annotations contain invalid JSON, conversion will [return an error](https://github.com/tektoncd/pipeline/blob/83af16733e00b7572d2156e73b8266c71766a43e/pkg/apis/version/conversion.go#L47-L50) rather than panicking, so I don't think there's any remaining work here, feel free to reopen if needed.
