### ISSUE TITLE
Allow cluster operator to configure default resolver

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#5907]
### Feature request

Allow cluster operators to configure a default resolver via a configmap. I would imagine default params could be configured in the resolver configmap itself rather than the tekton remote resolution configmap (e.g. how the [git resolver](https://github.com/tektoncd/pipeline/blob/main/docs/git-resolver.md#options) allows specifying a default URL).

### Use case

All of a company's Tasks and Pipelines are stored in the same git repo and they don't want to have to specify this for every TaskRun and PipelineRun.

**Comment by QuanZhang-William** [comment]
In the API WG we discussed the option to add the configuration as a new feature flag `default-resolver-type` in the [resolver/config-feature-flag.yaml](https://github.com/tektoncd/pipeline/blob/main/config/resolvers/config-feature-flags.yaml) file. 

The main issue I noticed in the approach is that the `ConfigMap` is in the `tekton-pipelines-resolvers` ns instead of `tekton-pipelines`. Here is a [simplified code](https://github.com/tektoncd/pipeline/compare/main...QuanZhang-William:pipeline:new-config-map) (I have made sure that RBAC is working properly, aka, I don't think it is failing due to authorization issue) and it gives the following error when starting Webhook and Controllers:

`{"severity":"fatal","timestamp":"2023-03-02T22:25:17.834Z","logger":"tekton-pipelines-webhook","caller":"sharedmain/main.go:285","message":"Failed to start configuration manager","commit":"b3d12c6-dirty","error":"configmap \"resolvers-feature-flags\" not found","stacktrace":"knative.dev/pkg/injection/sharedmain.MainWithConfig\n\tknative.dev/pkg@v0.0.0-20230117181655-247510c00e9d/injection/sharedmain/main.go:285\nknative.dev/pkg/injection/sharedmain.MainWithContext\n\tknative.dev/pkg@v0.0.0-20230117181655-247510c00e9d/injection/sharedmain/main.go:210\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/webhook/main.go:262\nruntime.main\n\truntime/proc.go:250"}`

With some investigation, The error is caused by that Knative allows to [register the ConfigMap Watcher to watch a single namespace](https://github.com/knative/pkg/blob/b558677ab03404ed118ba3e179a7438fe2d8509a/configmap/informer/informed_watcher.go#L207) when starting the [SharedMain](https://github.com/knative/pkg/blob/8d1efe19e694809d8e891bceb0e00b1975f97ab4/injection/sharedmain/main.go#L284), and it is defaulted to `tekton-pipelines` namespace defined by the env. It's not clear to me how to make it to watch `ConfigMap` from multiple ns when starting the Webhook (Happy to learn if you know!).

****
Alternatives are: 
1) to configure the value in the [config-defaults.yaml](https://github.com/tektoncd/pipeline/blob/main/config/config-defaults.yaml) 
2) or use a new dedicated Config Map for this FR like [config-trusted-resources.yaml](https://github.com/tektoncd/pipeline/blob/main/config/config-trusted-resources.yaml)

They are in the `tekton-pipelines` ns, which can help make the implementation a lot neater, and we don't need add an extra config dependency to `tekton-pipelines-resolvers` ns for controllers & webhook. I think this option makes sense because the FR is more like a "default value" instead of "feature flag"...


WDYT @lbernick @dibyom @abayer @vdemeester

**Comment by abayer** [comment]
Ah, yeah, I hit that problem with `ConfigMap` watching. In retrospect, thanks to this and some other issues, I really, really wish I hadn't put the resolvers in a separate namespace. Ah well.

I do think we should put the configuration of a default resolver in `tekton-pipelines`, not `tekton-pipelines-resolvers` - but I can't entirely justify that feeling. I guess I just feel like a default resolver for Pipelines usage is something that should be configured on Pipelines, not on the resolvers...

**Comment by afrittoli** [comment]
> Ah, yeah, I hit that problem with `ConfigMap` watching. In retrospect, thanks to this and some other issues, I really, really wish I hadn't put the resolvers in a separate namespace. Ah well.
> 
> I do think we should put the configuration of a default resolver in `tekton-pipelines`, not `tekton-pipelines-resolvers` - but I can't entirely justify that feeling. I guess I just feel like a default resolver for Pipelines usage is something that should be configured on Pipelines, not on the resolvers...

I tend to agree, that feels like a pipeline configuration as opposed to resolver configuration.

**Comment by lbernick** [comment]
> Ah, yeah, I hit that problem with `ConfigMap` watching. In retrospect, thanks to this and some other issues, I really, really wish I hadn't put the resolvers in a separate namespace. Ah well.

Some users are requesting we put them back into the same namespace (https://github.com/tektoncd/pipeline/issues/5607 and https://github.com/tektoncd/pipeline/issues/5931)-- is that an option?

**Comment by QuanZhang-William** [comment]
> > Ah, yeah, I hit that problem with `ConfigMap` watching. In retrospect, thanks to this and some other issues, I really, really wish I hadn't put the resolvers in a separate namespace. Ah well.
> 
> Some users are requesting we put them back into the same namespace (#5607 and #5931 )-- is that an option?

This is something worth investigation, while I don't think this specific FR should not necessarily be "blocked" by it? 

I agree with the point that this is more like a pipeline default configuration, and putting to the [config-defaults.yaml](https://github.com/tektoncd/pipeline/blob/main/config/config-defaults.yaml) makes more sense to me.

**Comment by QuanZhang-William** [comment]
This feature request is completed, should we close this issue?

TEPs:
- https://github.com/tektoncd/community/pull/972
- https://github.com/tektoncd/community/pull/990

Implementation PRs:
- https://github.com/tektoncd/pipeline/pull/6339
- https://github.com/tektoncd/pipeline/pull/6317

**Comment by jwitrick** [comment]
Please revisit this ... It should not be too difficult to split them. This is still BREAKING when using Kustomize.
