### ISSUE TITLE
can't select workspace in tekton-dashbord while Creating PipelineRun

### ISSUE THREAD

**Issue by Faraaaaaaaaaaaa** [tektoncd/pipeline#6144]
# Expected Behavior

All my pipelines work's with workspace -> secret. 
Need to type workspace name and select secret as i do in openshift  while creating  pipelinerun.
![image](https://user-images.githubusercontent.com/81243209/218104844-e802e297-eacf-4851-9261-ff8931c318a8.png)
or when creating pipelinerun by yaml:
![image](https://user-images.githubusercontent.com/81243209/218105578-e7618b90-8ad8-4cea-853b-80afa4e77e9e.png)

# Actual Behavior
NO place in tekton-dashbord to select or type workspace->secret
![image](https://user-images.githubusercontent.com/81243209/218105734-2d60e1e9-c440-48de-bb89-b4eec53e358f.png)
![image](https://user-images.githubusercontent.com/81243209/218105805-beacf447-bde8-43ac-9e23-24f9bc641d44.png)

# Steps to Reproduce the Problem

1. Install tekton-dashbord
2.  Pipelineruns -> Create
3. Select Pipeline and other thing's but workspace

# Additional Info

- Kubernetes version:

OpenShift version
4.11.0-0.okd-2022-10-28-153352
Kubernetes version
v1.24.0-2566+5157800f2a3bc3-dirty

```
(paste your output here)
```

- Tekton Pipeline version:

$ tkn version
Client version: 0.26.1
Pipeline version: v20230208-d7961fc543
Triggers version: v0.22.0
Dashboard version: v0.32.0
Operator version: v0.64.0

```
(paste your output here)
```

**Comment by Faraaaaaaaaaaaa** [comment]
PipelineRun tkn/always-to-alpha-run-1676039021477 doesn't bind Pipeline tkn/always-to-alpha's Workspaces correctly: pipeline requires workspace with name "tkn" be provided by pipelinerun

**Comment by AlanGreene** [comment]
Hi @Faraaaaaaaaaaaa, thanks for raising this. It's more of a feature request than a bug so removing that label.
/remove-kind bug

This is already being tracked in https://github.com/tektoncd/dashboard/issues/1283 (in the Dashboard repo). For now there's no UI for selecting workspace config but you can switch to YAML mode by clicking the button in the top right of the window and enter any advanced config (including workspaces) not currently available in the UI.

Closing this issue since it's not related to the Pipeline project and already tracked in the Dashboard repo.

/close
