### ISSUE TITLE
`incomplete` tasks should not be part of `skippedTasks`

### ISSUE THREAD

**Issue by pritidesai** [tektoncd/pipeline#6387]
# Expected Behavior

The release [pipeline](https://github.com/tektoncd/pipeline/blob/main/tekton/release-pipeline.yaml#L107) failed to publish an image. The failure status of a pipelineRun must surface the task failures (which is being tracked in #6383) and the rest of the `pipelineTasks` which were not executed because of this failure are counted as incomplete and not part of skipped tasks. `publish-to-bucket`, `publish-to-bucket-latest`, and `report-bucket` must not be in the list of `skippedTasks`.

# Actual Behavior

As discussed in this [comment](https://github.com/tektoncd/pipeline/issues/6383#issuecomment-1474135669), the child tasks of a failed parent task are listed as skipped tasks. 

```
"skippedTasks": [
    {
      "name": "publish-to-bucket",
      "reason": "PipelineRun was stopping"
    },
    {
      "name": "publish-to-bucket-latest",
      "reason": "PipelineRun was stopping",
      "whenExpressions": [
        {
          "input": "true",
          "operator": "in",
          "values": [
            "true"
          ]
        }
      ]
    },
    {
      "name": "report-bucket",
      "reason": "PipelineRun was stopping"
    }
  ],
```

# Additional Info

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
tkn --context dogfooding version
Client version: 0.29.1
Chains version: v0.14.0
Pipeline version: v0.44.0
Triggers version: v0.22.1
Dashboard version: v0.32.0
```

This issue could also be fixed by fixing #6383 but tracking it as a separate issue just in case.

**Comment by Yongxuanzhang** [comment]
It would be great if we could have an example so I can make sure this issue is also fixed

**Comment by afrittoli** [comment]
Everything that is not executed at the end of a `PipelineRun` is considered skipped today.

We could introduce a better granularity in the reasons why a specific task was not executed, for instance:
- skipped because of a when expression
- not executed because a parent task was skipped
- not executed because a parent task did not produce a result it depends on
- not executed because of failure of an unrelated task (so the pipeline stopped)
- not executed because of failure of timeout
- not executed because of cancellation

I would avoid the term incomplete for `TaskRuns`. 
The only cases where we do not let a `TaskRun` complete (i.e. we interrupt it during execution) are timeout and hard cancel.
Perhaps we could reserve "skipped" for Tasks skipped directly or indirectly because of a `when` expression, and use "not executed" for the rest?
