### ISSUE TITLE
Latest build of git-init container image is rather old and has a high vulnerability

### ISSUE THREAD

**Issue by superlazyname** [tektoncd/pipeline#6415]
I was looking for a place to pull the latest git-init image from, I had a hard time finding it, but on a whim I decided to try and poke around in a repository that was linked in release.yaml, and that led me here:

https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com/tektoncd/pipeline/cmd/git-init

Why was the last build date for this February 17th 2023? Is this container repository dead? If not, what is its release cadence? Even if there isn't a set cadence for releasing the pipelines, it might be a good idea to just rebuild anyway to base the images on a newer / safer version of the base image and to pull newer Go dependencies.

The latest build of git-init in this repository has a High vulnerability in a Go dependency, but looking at the details of the CVE maybe this is not a massive threat, I am not an expert on this though. There have been quite a few vulnerabilities reported in Go rather recently.

I also found a Docker Hub profile here, https://hub.docker.com/u/tekton but it's even older (4 years old, and images have a ton of rather scary looking vulnerabilities), if you own this you may want to take it down, a bunch of people I knew thought it was the official source for Tekton images and that it was up to date / maintained.

I was thinking that maybe it would be a good idea to just build this image for myself, but I wasn't able to find any Dockerfiles or build instructions, is there a guide for this somewhere?

Also, where is git-init in release.yaml? This is something I am a bit curious about, because I know it got installed, but I'm not sure how it got into the server, there's no mention of it in that yaml file.

Thanks,

**Comment by afrittoli** [comment]
> I was looking for a place to pull the latest git-init image from, I had a hard time finding it, but on a whim I decided to try and poke around in a repository that was linked in release.yaml, and that led me here:
> 
> https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com/tektoncd/pipeline/cmd/git-init
> 
> Why was the last build date for this February 17th 2023? 

Hello @superlazyname, the reason the image has not been released in March is that `git-init` was part of the git `PipelineResources` which after a very long deprecation period has been finally removed in the March release - see the [release notes](https://github.com/tektoncd/pipeline/releases/tag/v0.46.0).

The image is also used in the `git-clone` task in the catalog, and because of that we plan for now to migrate the `git-init` image code into the tekton catalog org, so that it may be maintained along with the task where it's used. This has happened yet though.

> Is this container repository dead? If not, what is its release cadence? 

Tekton Pipeline releases happen on a monthly basis. LTS releases quarterly. See  https://github.com/tektoncd/pipeline/blob/main/releases.md

> Even if there isn't a set cadence for releasing the pipelines, it might be a good idea to just rebuild anyway to base the images on a newer / safer version of the base image and to pull newer Go dependencies.
> 
> The latest build of git-init in this repository has a High vulnerability in a Go dependency, but looking at the details of the CVE maybe this is not a massive threat, I am not an expert on this though. There have been quite a few vulnerabilities reported in Go rather recently.

Thanks for reporting this. If you'd like to share more details with us perhaps you could use the tekton vulnerability team mailing tekton-vmt[at]googlegroups.com so we can address the issue asap - see details at https://github.com/tektoncd/pipeline/security/policy. 

> 
> I also found a Docker Hub profile here, https://hub.docker.com/u/tekton but it's even older (4 years old, and images have a ton of rather scary looking vulnerabilities), if you own this you may want to take it down, a bunch of people I knew thought it was the official source for Tekton images and that it was up to date / maintained.

Thanks for reporting this too. I was not aware of this docker profile, it's not maintained by the Tekton community.
I'll try to find out more about it.

> 
> I was thinking that maybe it would be a good idea to just build this image for myself, but I wasn't able to find any Dockerfiles or build instructions, is there a guide for this somewhere?

To use Tekton we use `ko`, which does not require a `Dockerfile`. 
If you want you could try `ko build` to build the image directly.
We shall resume building the image once it moved to its new home, but we could make a new release to fix the vulnerability if needed,

> 
> Also, where is git-init in release.yaml? This is something I am a bit curious about, because I know it got installed, but I'm not sure how it got into the server, there's no mention of it in that yaml file.

The `git-init` image is used by the git `PipelineResource` and by the `git-clone` task. If you used either of those, it will be cached by your k8s container runtime.  `git-init` is not used by any long-running service, only as part of tasks.

> 
> Thanks,

**Comment by superlazyname** [comment]
Thanks for the very helpful reply! That answered a lot of my questions.

> which after a very long deprecation period has been finally removed in the March release

Can you link me to documentation about this? I am not sure what to use as a replacement, or if I should make my own.

> perhaps you could use the tekton vulnerability team mailing tekton-vmt[at]googlegroups.com so we can address the issue asap

I can do this, but it's not a vulnerability specific to the task, just a vulnerability in a Go dependency that the task includes. I'm not saying I have an exploit against that task specifically. 

If it would help, sure, I can email the particular CVE in the Go dependency to the team so they can look at it.

**Comment by wlynch** [comment]
I don't know if regularly rebuilding [previous LTS releases](https://github.com/tektoncd/pipeline/blob/v0.46.0/releases.md#release) is currently part of the current release process, but we probably should. This would at least ensure we're picking up new Go related CVEs as they are fixed.  I'll follow up on this!

**Comment by afrittoli** [comment]
> I don't know if regularly rebuilding [previous LTS releases](https://github.com/tektoncd/pipeline/blob/v0.46.0/releases.md#release) is currently part of the current release process, but we probably should. This would at least ensure we're picking up new Go related CVEs as they are fixed. I'll follow up on this!

We started discussing in slack about having a regular cadence for patch releases,  it's something we should do, not only for Tekton fixes but to pick up security patches as well. Since most dependencies are pinned though, we could:
- run dependabot against the LTS branches
- make sure we merge PRs before the scheduled patch release
- define the roles that include this kind of work

/cc @vdemeester @pritidesai

**Comment by superlazyname** [comment]
Bump

Any updates?

**Comment by vdemeester** [comment]
We should get https://github.com/tektoncd-catalog/git-clone/pull/3 merged so that we can depend on this one instead 👼🏼 
But https://console.cloud.google.com/gcr/images/tekton-releases/global/github.com/tektoncd/pipeline/cmd/git-init should be considered as a deprecated image.
