### ISSUE TITLE
Add a table of comparisons from Tekton to other solutions to the README

### ISSUE THREAD

**Issue by RXminuS** [tektoncd/pipeline#644]
Maybe an obnoxious question, but I just can't see a lot of differentiation with Argo CI/CD...a project that is already adopted for things like Kubeflow. I'm all for different projects to attack the same problem with different priorities, but in this case it seems like creating yarn after npm had already adopted all of its features.

Maybe good to outline a clear focus and how that differs from existing tools?

**Comment by bobcatfish** [comment]
Hey @RXminuS ! It's a good question :D The main distinction is that Argo itself is more general purpose, and with Tekton Pipelines we are aiming specifically and only for CI/CD use cases. We might have more direct overlap with Argo CI or CD, but we've been in contact with some of the Argo folks, and hopefully in the long run we can collaborate.

> Maybe good to outline a clear focus and how that differs from existing tools?

If you are interested [we created this spreadsheet a while ago](https://docs.google.com/spreadsheets/d/1ejHvL-GEC0CTXi4WpQ6mA2D4fAChGrlQkLOfqS9cKBk/edit#gid=1786197146) which compares some of the Tekton Pipeline goals with existing CI/CD tools (though it compares Argo, not Argo CI or CD).  (note this is shared with members of https://groups.google.com/forum/#!forum/knative-dev - since we used to be part of knative! - you'll have to join the group to see the doc)

If this kind of thing is useful, maybe we can port it to markdown in the repo :D

**Comment by RXminuS** [comment]
Thanks for the answer, again it was hard to phrase the question without coming across hostile but your response is super clear and kind :-)

I'll have a look at the document. Personally I really like it when projects put similar solutions front and center and highlight the differences as well as similarities.

Vue is a classic example and I think that could be useful here too. https://vuejs.org/v2/guide/comparison.html

**Comment by dlorenc** [comment]
Awesome, retitled this issue to make the goal of adding a comparison clear.

**Comment by bobcatfish** [comment]
I feel like given that we haven't done anything with this at all in so long, maybe it's reasonable to close for now?

**Comment by dcherman** [comment]
@bobcatfish I still feel like this would be useful, but at a minimum, can you port the spreadsheet that you mentioned in https://github.com/tektoncd/pipeline/issues/644#issuecomment-475032948 to markdown before closing?  Don't know about others, but I requested access to that Google Group like a year ago and never got it, so was never able to read it.

**Comment by bobcatfish** [comment]
Sounds good @dcherman , we can do that!

btw you should be able to join the google group at https://github.com/tektoncd/community/blob/master/contact.md#mailing-list (https://groups.google.com/forum/#!forum/tekton-dev) without anyone needing to approve your membership 🤔

**Comment by dcherman** [comment]
@bobcatfish Ya, was able to join the Tekton mailing list without approval, but I think that spreadsheet is owned by knative-dev which seems to require approval to join (https://groups.google.com/g/knative-dev).

That said, I might've asked for access to the spreadsheet directly versus joining the Google group.  It's been quite a while since I did that, so I can't remember :)
