### ISSUE TITLE
Security concerns about using SPIRE for non-falsifiable provenance.

### ISSUE THREAD

**Issue by jagathprakash** [tektoncd/pipeline#6559]
### Feature request
Non-falsifiable provenance - In non-falsifiable provenance it should not be possible for any workload or user to be able to change the provenance of a build. 
TEP-0089 explores how we can achieve this using SPIRE.
SPIRE has a server and a set of agents, one for each node in the cluster. Workloads communicate with SPIRE through the SPIRE agents to get cryptographic identity keys. These keys can be used for signing the provenance. The communication between SPIRE agent and the workload is through a workload api which uses Unix Data sockets. This raises the following securing concerns.
1.  UDS is implemented through hostpath volumes.
2. Hostpaths could be hidden through spiffe-csi drivers (which in turn use hostpaths to communicate with the kubelet), but these spiffe-csi driver containers will have to be run in privileged mode.

Both of the above are not in the "restricted" mode of [Pod Security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

But according to this [slack discussion thread](https://spiffe.slack.com/archives/CBNCC2V17/p1681827980132159), hostpaths should be ok under certain conditions.

This issue is being opened to document the discussions and later would be added to TEP-0089.

**Comment by bobcatfish** [comment]
In order to evaluate how this impacts our SPIRE work and TEP-0089 I think it would be useful to understand a few things:
- What exactly is the attack vector / vulnerability opened up by the use of hostPath for SPIRE communication?
- How does that attack vector compare to the ones that we are trying to plug with our use of SPIRE?
- How have other users of SPIRE evaluated this issue?

If the solution is still more secure overall with SPIRE (and hostPath use) than it was without it, it seems to me like it's still worth adding support to Tekton.

My understanding of the standards at https://kubernetes.io/docs/concepts/security/pod-security-standards/ is that they are intended to be useful starting points, but we need more information to make a decision, and I think we need to be specific about what the actual expected consequences are to deviating from it.

**Comment by dibyom** [comment]
> Both of the above are not in the "restricted" mode of [Pod Security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

From https://kubernetes.io/docs/concepts/security/pod-security-standards/

> The Privileged policy is purposely-open, and entirely unrestricted. This type of policy is typically aimed at system- and infrastructure-level workloads managed by privileged, trusted users.

To me, the CSI daemonset qualifies as an infra workload managed my trusted users. The actual Tekton workloads can still run with the restricted pod security standard.

**Comment by jagathprakash** [comment]
Attack vectors for hostpath.
----------------------------
1. Hostpath can be exploited if the we mount sensitive directories from the underlying node into the container. 
2. Say if we mount /var/logs we could potentially use a symlink attack to download sensitive secrets.
Hostpath vulnerabilities are well researched and most can be avoided.
When we have to deploy a Task pod the task pod will have a hostpath volume. This means an user workload has access to hostpath or a dir in the underlying node.

To prevent hostPath based attacks, the spiffe.csi driver has been developed. This needs (as all csi drivers) needs a bidirectional mount. As such this has to run in privileged mode. The following securityContext has to be used for the csi driver.

        securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
            privileged: true

The attack vector here is that the csi driver has the same privilege as root and it could access the underlying node.
But with the csi plugin no workloads have hostpath volumes mounted which means none of them have unlimited access to directories of a node.
The csi plugin by itself will have a hostpath volume mounted. But as @dibyom has noted the csi driver can be considered as part of the control plane. 
The threat surface is significantly reduced by using the spiffe.csi driver.

**Comment by chuangw6** [comment]
cc @wlynch

**Comment by wlynch** [comment]
I'm hesitant to recommend anything that requires privilege. It opens up risk for [escalation attacks](https://bishopfox.com/blog/kubernetes-pod-privilege-escalation) and can prevent users from using other security features like sandboxing.

I'm curious if there are alternative configurations of Spire that we can use that wouldn't require privilege. A few ideas @jagathprakash and I were discussing last week that I think would be worth exploring:

1. Using Spire [x509 SVIDs](https://spiffe.io/docs/latest/spire-about/spire-concepts/#node-attestation) tied to the Task Pod rather than a daemonset.
    
    AFAICT the [`k8s_psat` Node Attestor](https://github.com/spiffe/spire/blob/v1.6.3/doc/plugin_server_nodeattestor_k8s_psat.md) goes through the typical OIDC flow using the Pod JWT, but it ties the spiffe node id to the k8s node UID, even though it verifies all of the Pod claims including Pod name/UID. If we don't care about container-specific claims and only Pod-level identity (which I believe is the case for results), this could probably serve as a suitable replacement instead of a Workload SVID.

2. Run a pod-local agent + local socket.

    Use 1, but also pair it with a pod agent that can issue Workload SVIDs local to the Pod without privilege.

3. Talk to daemonset over TCP, authenticate using Pod JWT.

    @jagathprakash pointed out that the SPIFFE spec shows support for a [TCP based Workload API](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_Endpoint.md#4-locating-the-endpoint), although AFAICT this is not implemented in the Spire agent. Using this + the Pod JWT would let us authenticate requests for the Pod, even for a daemonset agent. We would need to figure out TLS for this (which hopefully could be bootstrapped by the Tekton control plane for Tekton managed pods), and same restrictions as 1 where this could only be bound to the Pod identity.

I'll caveat all of these with I'm not a spiffe/spire expert, so I don't have a strong sense of how feasible / how much work these would take, but I think there's promise to these that I'd like to explore before we introduce a privileged component.

**Comment by jagathprakash** [comment]
A solution discussed in our offline meeting which would avoid the use of both hostpath and privileged container is to add the spire agent in both the pipelines controller pod as well as the taskrun pods.
Since the spire agent is in the same pod as the workloads, we could use an empty dir instead of a hostpath for the workload api.

Some issues with this approach.
1. We could end up with multiple spire agents on a single node. Does Spire handle this?
2. The service account which runs spire agent needs "get" access of pods, nodes and node/proxy. This is to validate the node and the pods running on it. There are 2 service accounts here, one is the pipelines-controller sa and the other is a sa defined for the taskrun. The pipelines-controller sa is a control plane sa and should be ok, while the sa for task run is for the data plane. Is it ok to get access for nodes, pods and node proxy for this user define sa?

cc @pxp928 @lumjjb

**Comment by lumjjb** [comment]
I am very much on team "deprivilege" but in this situation. I think that we've hit practical minimum... I believe that it is not possible to achieve what we want today without components that require privilege (with today's hardware capabilities). 

Let me elaborate a bit more:
- The idea behind this capability is to remove reliance on trust on the k8s control plane. This means we need an independent mechanism for authentication of system workloads.
- Privilege provides the capabilities for being able to observe and introspect the primary workload orchestrator (kernel / enclaves) and talk to hardware devices like TPMs, hardware sandbox facilities without relying on the control plane. Considering today's state of the world, this is unlikely without privilege.
>Desired state of the world: a world where we have a much more granular linux capabilities this may be possible - but not the case in the near future. Otherwise, likely a [capability based kernel is required](https://en.wikipedia.org/wiki/Capsicum_(Unix)), which will likely not be mainstream linux in the near future. 

The solution that I think seems like a great balance in terms of having only the agents and the CSI driver (~300 LOC) having privilege is (imo) likely the best middle ground. The alternative solutions propose degrade the workload identity security guarantees such that it is unlikely that there will be much value add to having it installed (little guarantees on attestation of node agent since it cyclicly depends on control plane trust + more risk of of workload identity spoofing). 

I think the added attack surface is not significantly different from what's used by k8s, and if the goal is to have something of a much smaller size (feature scope) perform this identity/auditing capability on the workloads, it is a win (to me of course :)). 

As an aside, I had a chat with the SPIRE SIG around the TCP workload API which is not implemented, but even if it is implementable, the privilege implications are the same (and potentially more intrusive).

**Comment by evan2645** [comment]
👋 hey folks, sorry about barging in here, just wanted to raise my hand to help however I can. For what it's worth, I think @lumjjb is looking at the right trade-offs. SPIRE is generally considered to be an infra-level component that requires elevated permissions in order to provide the guarantees it provides... and those guarantees transcend k8s. I feel @dibyom's comment about this is par for the course.

As @lumjjb mentioned, there are some paths forward to sidestep these problems - specifically, a k8s namespace-scoped SPIRE deployment and TCP-based attestation, but both paths have worse trade-offs for this use case. The former significantly weakens the SPIRE threat model and all trust will be placed back on k8s. At that point, all SPIRE provides is rotating certs, and the strength of attestation is lost. The latter will absolutely require root (or a root ~equivalent capability) on SPIRE Agent.

My impression is that the majority of folks running SPIRE in locked-down k8s clusters use the CSI driver (which is itself very very small) and carve policy exceptions for SPIRE-specific infra.

**Comment by pxp928** [comment]
> We could end up with multiple spire agents on a single node. Does Spire handle this?

Based on the discussion this would be a very wasteful operation and result in very poor scaling.

**Comment by wlynch** [comment]
Chatted with @lumjjb - I'm convinced. 🙂 

The missing piece for me was there are likely cases where users would not want to bootstrap off the k8s_psat and instead go directly to underlying node tokens / TPMs as well as want to bypass the k8s control plane and run the node attester out of band as a secondary check/balance.
To support sandboxed environments we would need the cluster provider to provide Spire support on the host and expose that into the cluster.

I think there's still value in a mode where we use Pod JWT <-> x509 SVID exchange (@lumjjb also mentioned other mechanisms like CertificateSigningRequests might also work) if you're okay with placing more trust on k8s, since this would let us have some trust around tampering of results within a cluster assuming a well-behaved control plane.
It's a trade-off of whether you consider k8s as part of your trust boundary and compatibility to run in environments where privilege is not allowed / Spire is not available. That said, I think we're good to go with proceeding with CSI support.

Thanks everyone!
