### ISSUE TITLE
ValidateParamArrayIndex for taskSpec should check beta flag.

### ISSUE THREAD

**Issue by Yongxuanzhang** [tektoncd/pipeline#6607]
# Expected Behavior
https://github.com/tektoncd/pipeline/blob/a0fb7849913c91911d897a4f4fba46f921e7bfdf/pkg/apis/pipeline/v1/task_validation.go#L611-L615 
should check beta flag instead of alpha flag. 

Thanks @dibyom for catching this bug. 
# Actual Behavior
taskSpec's ValidateParamArrayIndex checks alpha flag.

# Additional Info
Array indexing (Tep 76) is promoted by https://github.com/tektoncd/pipeline/pull/6103, yet the feature flag check for taskSpec's ValidateParamArrayIndex is not updated. The resulting consequence is that the validation is skipped for taskSpec when this feature is used and the api feature flag is set to `beta`

- Kubernetes version:

  **Output of `kubectl version`:**

```
(paste your output here)
```

- Tekton Pipeline version:

Version since v0.46

**Comment by lbernick** [comment]
This is a bit more complicated; see https://github.com/tektoncd/pipeline/issues/6616 for more detail.

Here's what I think the logic should look like:
- If a task uses indexing into array params, we should validate in the webhook that "enable-api-fields" is set to a value that permits using this feature
- If we cannot validate in the webhook since the task is e.g. stored in git, we should validate in the reconciler that "enable-api-fields" is set to a value that permits using this feature before converting the task to v1beta1 (or honestly we could skip this validation)
- if the task's array param indexes are out of bounds based on the params provided, we should validate this in the reconciler, separately from the value of "enable-api-fields"

**Comment by dibyom** [comment]
> If we cannot validate in the webhook since the task is e.g. stored in git, we should validate in the reconciler that "enable-api-fields" is set to a value that permits using this feature before converting the task to v1beta1 (or honestly we could skip this validation)

wouldn't skipping the validation result in referenced pipelines and in cluster pipelines being validated differently?
