### ISSUE TITLE
Cannot use images from private/secure registries

### ISSUE THREAD

**Issue by elfner** [tektoncd/pipeline#6689]
Hi - this is likely not a bug, rather my just not knowing how, but I couldn't find the answer elsewhere.

We are running Tekton through the Redhat Pipelines operator (1.8.2) on Openshift 4.10.39 (Kubernetes Version: v1.23.12+7566c4d), which uses Tekton Pipelines: v0.37.5
We have the need to use custom images from our Artifactory instance in tasks.  I couldn't get it to load those images, so tried to take Artifactory out of the problem space and simply pull from the internal Openshift registry, but received a similar error.

The error message pulling the image is: 

> Failed to pull image "default-route-openshift-image-registry.apps.cluster.fqdn/openshift/pipeline-tools:latest": rpc error: code = Unknown desc = pinging container registry default-route-openshift-image-registry.apps.cluster.fqdn: Get "https://default-route-openshift-image-registry.apps.cluster.fqdn/v2/": x509: certificate signed by unknown authority

I tried the solution mentioned at https://github.com/tektoncd/pipeline/issues/1171, but the operator overrides any attempted changes to the deployment.

Appreciate any insight.  Thank you.

**Comment by alexezio** [comment]
Hi @elfner 
Currently, the solution for insecure registries in Pipeline involves mounting the certificate through a ConfigMap and envrionment(SSL_CERT_FILE). 
Additionally, the Tekton Operator project also provides support for this feature. You can refer to this pull request for more information: https://github.com/tektoncd/operator/pull/246. 

Since you are using the Red Hat-provided Pipeline Operator, I cannot guarantee its compatibility with this feature. I recommend reaching out to the relevant individuals in the OpenShift community for assistance and clarification on this matter.

**Comment by elfner** [comment]
Thank you.  In the meantime, I was able to get it to work.
It all boiled down to defining the service account correctly to reference the secret with the **.dockerconfigjson**.
Before it just referenced:
```
secrets:
  - name: xxx
```
but it needed to reference it as:
```
imagePullSecrets:
  - name: xxx
```

**Comment by alexezio** [comment]
You can use a podTemplate to set the corresponding serviceAccountName, and then associate the imagePullSecrets with the serviceAccountName in the configuration to achieve your desired outcome.
