### ISSUE TITLE
Missing coverage of stored resources in upgrade tests

### ISSUE THREAD

**Issue by lbernick** [tektoncd/pipeline#6868]
# Expected Behavior

Upgrade tests cover scenarios where Tekton CRDs exist on the cluster prior to upgrading the Pipelines version, as described [in their comments](https://github.com/tektoncd/pipeline/blob/95863061aa91033ca5562d7778bf3e364e0b51d8/test/e2e-tests-upgrade.sh#L21-L25).

# Actual Behavior

Upgrade tests install the older pipeline server, upgrade to the newer server, run tests, clean up the environment, and repeat this process. 

The function apply_resources, which was responsible for this functionality, was renamed in https://github.com/tektoncd/pipeline/pull/1351, breaking the upgrade tests, and the defunct function call was removed in https://github.com/tektoncd/pipeline/pull/6723.

**Comment by JeromeJu** [comment]
During the work of https://github.com/tektoncd/pipeline/pull/6855, and by comparing how the upgrade test scenario 2 is introduced in https://github.com/tektoncd/pipeline/pull/1162, we could find it is problematic in the way of the following: when we are trying to create taskRuns and pipelineRuns resources in the same namespace:
- the examples test we have today are flaky, which could lead to red herring of our upgrade test if we restore the exact scenario ii - possible workaround is to select a subset of stable enough examples to be created
- duplicate resources name are apparent in the examples i.e. sensitive-recipe-storage ConfigMap resource has been used in https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/mapping-workspaces.yaml and https://github.com/tektoncd/pipeline/blob/main/examples/v1/pipelineruns/workspaces.yaml

Regarding the resources we choose, we would have the following options instead of restoring the scenario ii of the upgrade test back to its earlier stage when it's been created:
- [ ] choose a list of 'stable' examples as resources to be created
- [ ] choose a list of resources that does not have duplicate naming

**Comment by lbernick** [comment]
@JeromeJu that's a great point about not wanting to run all our integration tests to avoid flakiness.
One thing we could try would be to create a simple pipeline and simple task, upgrade the pipelines version, and then create a simple pipelinerun and taskrun using the pipeline and task that existed before the upgrade and verify that they run successfully.
