### ISSUE TITLE
Add checksum of on-cluster resources to Provenance.RefSource

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#6928]
### Feature request

In the `SLSA v1.0 predicate`, we capture the `uri and digest` of remote `tasks` and `pipelines`. However, if the `task/pipeline` was defined locally and submitted to the cluster then the `SLSA` provenance does not have a way to take a note of it in the provenance. In the `Tekton Chains WG` meeting, we reached an agreement that we should store the `checksum` of the spec of the on-cluster resource in the provenance.

Currently, we already produce and store the `sha256 checksum` in `Provenance.RefSource` if the reference `task/pipeline` used a `Cluster` resolver. However, we don't do this if the `task/pipeline` was referenced using just a `Name`, even though they are both effectively doing the same thing. 

This feature request attempts to compute the `sha256 checksum` of the on-cluster resources that are referenced by `Name` and add it to `Provenance.RefSource`.

### Use case

The checksum of the referenced on-cluster `pipeline/task` will be available in the provenance. If the users re-run the `pipeline/task`, using the same resources then the checksum should match with what was inserted in the provenance. This will allow verification of resources used for the build.

**Comment by chitrangpatel** [comment]
cc @wlynch @lcarva @chuangw6

**Comment by chuangw6** [comment]
SGTM. This was missing previously since on-cluster resources referenced by name instead of by resolver syntax are not resolved by remote cluster watcher (via resolution request). As you mentioned, "they are both effectively doing the same thing.". So adding them for consistency makes sense. 

So IIUC it would be just returning the checksum here right? (Same for task level)
https://github.com/tektoncd/pipeline/blob/3b9b351ba953681bfe8c67d25e5f4fd3bca0e20a/pkg/reconciler/pipelinerun/resources/pipelineref.go#L91-L107

**Comment by chitrangpatel** [comment]
> SGTM. This was missing previously since on-cluster resources referenced by name instead of by resolver syntax are not resolved by remote cluster resolver (via resolution request). As you mentioned, "they are both effectively doing the same thing.". So adding them for consistency makes sense.
> 
> So IIUC it would be just returning the checksum here right? (Same for task level)
> 
> https://github.com/tektoncd/pipeline/blob/3b9b351ba953681bfe8c67d25e5f4fd3bca0e20a/pkg/reconciler/pipelinerun/resources/pipelineref.go#L91-L107

Yes, that's correct.

**Comment by wlynch** [comment]
I'd sync with @Yongxuanzhang here - this should be very similar, if not identical to the checksum used for [trusted resources](https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md).

**Comment by chitrangpatel** [comment]
> I'd sync with @Yongxuanzhang here - this should be very similar, if not identical to the checksum used for [trusted resources](https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md).

This is what the `Cluster Resolver` [does](https://github.com/tektoncd/pipeline/blob/3b9b351ba953681bfe8c67d25e5f4fd3bca0e20a/pkg/resolution/resolver/cluster/resolver.go#L212-L223). I was hoping to replicate this here. @Yongxuanzhang Is this the checksum we also perform with `trusted resources`?

**Comment by Yongxuanzhang** [comment]
I think what @chitrangpatel proposed is to record this for the resources ref via local resolver, the link in @chuangw6's comment, it should be a simple replication of cluster resolver. No relationship with trusted resources.

**Comment by chitrangpatel** [comment]
> I'd sync with @Yongxuanzhang here - this should be very similar, if not identical to the checksum used for [trusted resources](https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md).

In trusted resources, we are also producing a `sha256` checksum of the `task/pipeline`. See https://github.com/tektoncd/pipeline/blob/0b95e49b707798ce2b19d29f31bd1ae82bebe3ee/pkg/trustedresources/verify.go#L240-L247

I will try to use approach this throughout.

**Comment by chuangw6** [comment]
> I'd sync with @Yongxuanzhang here - this should be very similar, if not identical to the checksum used for [trusted resources](https://github.com/tektoncd/pipeline/blob/main/docs/trusted-resources.md).

+1 to yongxuan. It seems like the checksum we computed here has nothing to do with trusted resources b/c trusted resource checks the signature (computed by author) against [the checksum it computes internally](https://github.com/tektoncd/pipeline/blob/0b95e49b707798ce2b19d29f31bd1ae82bebe3ee/pkg/trustedresources/verify.go#L240-L247) and see if it matches. Only thing in provenance.refSource that matters to trusted resources is the uri.


@wlynch I barely remember in https://github.com/tektoncd/pipeline/pull/5687 there is a specific reason why we only do the checksum of the spec part instead of the whole object for in-cluster resources. Do you remember why? Is it for downstream Chains verification in future or something else?

**Comment by chitrangpatel** [comment]
Following discussion on slack, I've opened a new issue to synchronize the checksum computation between trusted resources and cluster resolver. Issue https://github.com/tektoncd/pipeline/issues/6958

See details in there.

**Comment by Yongxuanzhang** [comment]
Thanks! I'm not opposed this, as long as it is the correct way for provenance!

**Comment by vdemeester** [comment]
/remove-lifecycle stale
@chitrangpatel what's the status on this issue ? I see #6958 is closed, so wondering about that 😛

**Comment by chitrangpatel** [comment]
Can be closed! Thanks for the ping :)
