### ISSUE TITLE
Make StepActions secure by default ?

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/pipeline#7497]
Today, we allow `param` substitution directly in the `scripts`. For inlined-steps, we cannot change that behaviour because of v1 API compatibility reasons. 

However, `StepActions` are an alpha feature. We can try to make them secure by default before they reach `beta`.

The proposal here to NOT allow `param` substitutions in `scripts` in `StepActions`. Users would need to add the params as `env` variables and use the `env vars` in scripts. In turn, we would not need to enable sharing of `step` results in `scripts` as well and take the `sketchy` approach of modifying the user's script.

This reduces the chances of `shell attacks`.

Alternatively:

The reason for not doing this would be `consistency` with `inlined-steps`. We could do this by default in `tekton/v2` (?)
Here we can call this out and provide best practices via documentation.

WDYT ??

cc @wlynch @vdemeester @afrittoli

**Comment by vdemeester** [comment]
I "think" I would vote for consistency (and documentation).

**Comment by chitrangpatel** [comment]
> I "think" I would vote for consistency (and documentation).

Good point. I added this point for context in the original message.

**Comment by wlynch** [comment]
My concern is largely in line with the motivation of https://github.com/tektoncd/community/blob/main/teps/0146-parameters-in-script.md

I understand we don't want to remove the existing behavior because v1 compatibility, but StepActions give us an opportunity to move users in the right direction and make this change in a non-breaking way. I don't see v1 leaving any time soon - waiting on a v2 doesn't seem pragmatic if we know this is problematic behavior.

**Comment by chitrangpatel** [comment]
@wlynch do you think that based on https://github.com/tektoncd/community/blob/main/teps/0146-parameters-in-script.md, we should take the same approach for both? 

There, instead of not allowing params in scripts, I think it is suggesting that users use a suffix `.env` like: `$(params.foo.env)`. The controller would then replace it with an env variable `${PARAMS_FOO}` for the user. 

Why have two different approaches between `inlined-steps` vs `step-actions` I wonder.

**Comment by vdemeester** [comment]
@chitrangpatel that doesn't necessary work, `${PARAMS_FOO}` works with bash (and most `sh` derivative), but a `script` can be anything —python, ruby, goscript, …) — and for those `${PARAMS_FOO}` is not going to work.

**Comment by chitrangpatel** [comment]
> @chitrangpatel that doesn't necessary work, `${PARAMS_FOO}` works with bash (and most `sh` derivative), but a `script` can be anything —python, ruby, goscript, …) — and for those `${PARAMS_FOO}` is not going to work.

Agreed. I think the [TEP](https://github.com/tektoncd/community/blob/main/teps/0146-parameters-in-script.md
) goes into more details about how it can enable this for any script (not just bash). I'm definitely not capturing all the nuances here. 

My main point here was that we should try and take the same approach for `inlined-steps` and `step-actions`, whatever that is.

**Comment by vdemeester** [comment]
Another point/question: `StepAction` is shipped and usuable in 0.54 am I right ? With the parameter substitutions, etc.. as it works on `Task` today — so we would break early adopters if we were to change that by default. I would rather treat this "security threat" the same for everything, aka `Task`, `StepAction`, … We should making sure we update the [TEP](https://github.com/tektoncd/community/blob/main/teps/0146-parameters-in-script.md) to also take into account `StepAction`, and treat all at the same time (consistency again).

**Comment by wlynch** [comment]
> @wlynch do you think that based on https://github.com/tektoncd/community/blob/main/teps/0146-parameters-in-script.md, we should take the same approach for both, inlined-steps and step-actions?

Should? Yes - if we were to do this over again today I think this is what I'd advocate for.
That said, I'm skeptical that we can do this for existing inlined steps given that this has been the existing behavior for years - this would be a significant breaking change. I don't think we can make a breaking change here even for security reasons without significant disruption to users.

The less invasive approach here would be to leave the existing behavior as-is, and add a check for [catlin](https://github.com/tektoncd/catlin/tree/main) to discourage use of it (similar to the [scorecards dangerous workflow check](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow)).

This probably needs to be broken down into 2 questions:

1. What do we want the behavior to be long term, ignoring current usage/compatibility?
2. What can we do today given the existing v1 behavior?

For 1 it sounds like we want to disallow the behavior for script blocks everywhere.
For 2 my preference would be to keep inline behavior for compatibility as is w/ catlin check, don't allow this for step actions since we know that's where we want to move towards, and look to remove the behavior in inline steps if/when there's a v2.
