### ISSUE TITLE
Support WhenExpression for StepAction

### ISSUE THREAD

**Issue by uqix** [tektoncd/pipeline#7623]
### Feature request

https://github.com/tektoncd/community/blob/main/teps/0142-enable-step-reusability.md#conditional-execution-of-steps

>  However, StepActions are generally written more generically and guarding whether to execute the next Step based on a previous Step will be required. This is something we can pursue in the future.

### Use case

To reduce pod overhead, we want to rewrite our Pipelines by `StepAction`, and `when` is the only remaining blocker here.

**Comment by ericzzzzzzz** [comment]
https://github.com/tektoncd/pipeline/issues/7415 is still open,  I think we might not include CEL in stepAction at the moment

**Comment by chitrangpatel** [comment]
> #7415 is still open, I think we might not include CEL in stepAction at the moment

I think we should for consistency with PipelineTasks. That issue is tracking its progress to beta. The idea would be that when those are implemented, they would be implemented alike for StepActions and Tasks. 

I think the way to think about this is that the filtering mechanism should be consistent across them both. But what (fields) you can filter on is different. e.g. You should be able to use `in` operator in `WhenExpressions` for both cases but clearly there are certain fields like `Task.Status` (for example) that makes no sense for `StepActions`.

**Comment by ericzzzzzzz** [comment]
Thanks for the clarification .
