### ISSUE TITLE
Timeout not working on Pipeline run

### ISSUE THREAD

**Issue by ritesh-makerble** [tektoncd/pipeline#7793]
When I checked pipelinerun I found TaskRunTimeOut 
![image](https://github.com/tektoncd/pipeline/assets/156639182/a02c9d61-2cda-43f2-bd05-0e6f04df91ea)
 I also checked the manifest of this pipeline run and I have specified timeout to 3hrs 
![image](https://github.com/tektoncd/pipeline/assets/156639182/e62d348d-5e72-4a13-a25d-25e5186545b6)

**Comment by ritesh-makerble** [comment]
@AlanGreene Can you help me with this?

**Comment by vdemeester** [comment]
👋🏼 @ritesh-makerble , thanks for the issue. According to the [doc](https://tekton.dev/docs/pipelines/pipelineruns/#configuring-a-failure-timeout) (and the code), this is expected.

> - `tasks`: specifies the timeout for the cumulative time taken by non-`finally` Tasks specified in `pipeline.spec.tasks`.
To specify a timeout for an individual Task, use `pipeline.spec.tasks[].timeout`.
When `timeouts.tasks` has elapsed, any running child TaskRuns will be canceled, finally Tasks will run if `timeouts.finally` is specified,
and the PipelineRun will fail.

Each `Task` will have a the default 1h timeout (or what is configured in the `config-defaults` configmap) if not specified otherwise. `timeouts.tasks` is for "all" `Task` to execute (not for "each").

There is a bunch of issues about this (that kind-of show it can be confusing):
- https://github.com/tektoncd/pipeline/issues/6520
- https://github.com/tektoncd/pipeline/issues/6137

**Comment by ritesh-makerble** [comment]
@vdemeester In my issue, you can see I have specified timouts.task to `3h`. But my pipeline run fails after 1 hr with an Error TaskRunTimeOut even though the timeout.pipeline is `4h`.

**Comment by vdemeester** [comment]
Yes, my guess is that there is a Task that timed out at 1h, making the pipelinerun fail. With what you specified, all task need to complete in 3h, but each task has its own 1h timeout. So if one task takes more than 1h it will timeout.
