### ISSUE TITLE
Current API allows users to place escalating information into PipelineResource

### ISSUE THREAD

**Issue by pmorie** [tektoncd/pipeline#941]
Currently, we allow users to put escalating information (tokens, basic auth pw) into the `PipelineResource` API resource; we should avoid this:

- Cluster administrators expect secret information to be confined to the `Secret` resource and write RBAC policies accordingly
- If you have read access to the `PipelineResource` API resource, you can potentially learn secret information by reading the collection

# Expected Behavior

I would expect that I would not be allowed to store secret information outside the `Secret` resource, and that it would be a validation error to store an API token or basic auth password directly in a `PipelineResource`. 

# Actual Behavior

I must store secret info in `PipelineResource`. If I try to put escalating info directly into a `PipelineResource` instead of in a secret, it should be rejected by validation.

# Steps to Reproduce the Problem

1. Make a `PipelineResource` that represents a cluster; store the API token directly in the `Param` instead of using a `SecretParam`
2. Anyone with read access to `PipelineResource` in my ns (or with a cluster role binding that grants them access) can now learn my token or basic auth PW

# Additional Info

**Comment by sbose78** [comment]
We should have only the owner of the `secret` and the `builder`-ish service account to have access to that secret ?

**Comment by pmorie** [comment]
> We should have only the owner of the secret and the builder-ish service account to have access to that secret ?

Good question. By builder-ish service account, I think you mean the SA specified in the PipelineRun or TaskRun, right? I *think* based on some initial investigation (still learning the codebase in this repo) that the SA specified in the `PipelineRun` must have access to the referenced secrets - but that's for you as the person who specifies which SA to use to sort out for yourself.

**Comment by bobcatfish** [comment]
I was also finding it strange that we have some secrets included directly in `PipelineResources` 🤔 Does it help @pmorie if we use `ServiceAccounts` for these and give `PipelineResources` access to those instead?

I'm guessing no since you still get access via the secret being mounted in the container that executes the `PipelineResource` :S

I'm not sure how to avoid this though if a `PipelineResource` needs to access the secret in order to do its thing (e.g. pulling down data from github). Any ideas?

**Comment by afrittoli** [comment]
One initial bit that should be easy to implement here is the validation, to disallow entering secrets directly as a parameter instead of a secret parameter.  This would only help people to make a better choice when defining their resources. This helps at least for to prevent secret leaks to people with read access to the namespace and no read-access to the secret, as long as the RBAC setup of the cluster is done properly.

For someone is able to define/execute a Task though, there's no easy way to prevent exposing secrets. Most CI systems suffer from similar type of issues. If we had a setup where a PR can define a new Task and execute this task as part of pre-merge CI, anyone with the ability to submit a PR would be able to expose secrets. Which is why we have things like `ok-to-test` in prow.  

So my take on this is that, apart from enhancing the validation, it would be super useful to draft a design document with the security use cases that we want to address, discuss it with the consumers of Tekton and agree on what kind of security features we need to prioritize / implement.

**Comment by houshengbo** [comment]
@pmorie Since the yaml file of the PipelineResource can be manually written, we are technically unable to prevent people from writing anything into it, including sensitive information. It is their freedom to define the names of the fields, and specify the value. If we still want to protect the sensitive information defined accidentally or intentionally in PipelineResource, we better have more strict access control to the PipelineResource, like who can access and how the fields are accessed.

PipelineResource cannot work by itself. We need to either be used/implemented it in TaskRun or PipelineRun. My suggestion is that we define/formalize where the authentication happens and where escalating information is used. For example, TaskRun and PipelineRun are the only resources, where authentication is conducted. BTW, @bobcatfish I used serviceAccount in TaskRun or PipelineRun to access my docker with the credentials, and it seemed to work fine with me. Let's say escalating information is only accessed and used in TaskRun or PipelineRun. It won't work if it is defined elsewhere. We cannot stop users from writing anything into the pipelineresource, but we can define whether it work or not. If PipelineResource does not support to use escalating information to access other services. There is no point to define it there.

How to do auth with the credentials? Well, we can define something like, only serviceAccount is accepted. In this case, users are directed to create the serviceAccount with their credentials well encapsulated.
 
Just share my two cents. Welcome any comments.

**Comment by pmorie** [comment]
> One initial bit that should be easy to implement here is the validation, to disallow entering secrets directly as a parameter instead of a secret parameter. This would only help people to make a better choice when defining their resources. This helps at least for to prevent secret leaks to people with read access to the namespace and no read-access to the secret, as long as the RBAC setup of the cluster is done properly.

Yep, this is my motivating concern. It would be a bad outcome if we were to provide an API that did not dissuade users from putting secret information into non-secret resources. It's fine for resources to require secret information - the most important thing is that secret information should be stored in the secrets resource, rather than in another resource.

**Comment by skaegi** [comment]
I wonder if borrowing the container env approach and using valueFrom with a secretKeyRef might be a reasonable approach here - https://github.com/tektoncd/pipeline/issues/1197
