### ISSUE TITLE
Proposal: Tekton objects should be self descriptive using annotations instead of insider info (container name prefix...)

### ISSUE THREAD

**Issue by joseblas** [tektoncd/pipeline#961]
# Expected Behavior
Tekton Step names shouldn't have any constrains but length.
# Actual Behavior
Currently Tekton sidecars is based on steps names, and this makes Tekton step names not flexible.

# Proposal
 When a Pod is created should have an annotation with all the Tekton containers within. Something like Istio does:
`sidecar.istio.io/status: '{"version":"299b0fe3441985f893a8b9fcca72a53989f22ef3d7b53148499683a078e54915","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'`

**Comment by vdemeester** [comment]
This is related to [that change](https://github.com/tektoncd/pipeline/pull/818) and https://github.com/tektoncd/pipeline/pull/936. We should try to make sure our object are as self descriptive as they can be *and* use annotation more instead of having to rely on *insider* information (aka the containername prefix, …)

**Comment by vtereso** [comment]
It's terms of processing, it requires less memory to filter the steps out of the pod using a prefix rather than having to compare against all annotations in a map (although either is fine). However, one question is why all containers within the task pod are not steps? A task in this manner would be most descriptive this way imo.

**Comment by joseblas** [comment]
For instance, Istio adds sidecars containers in pods; when Tekton containers are finished the pod is finished unless a sidecar container is still running. That container has to be killed. Up to now, the code was based on prefix on step names. The goal of this thread is to provide an alternative design.

**Comment by joseblas** [comment]
Hi @vdemeester @bobcatfish,
   this was open last week and no feedback since. I guess this proposal could be used in our implementation and close this issue, or discuss it in our weekly  meeting

**Comment by joseblas** [comment]
implemented in https://github.com/tektoncd/pipeline/pull/936

**Comment by bobcatfish** [comment]
Sorry for the lack of discussion in the issue @joseblas ! I had a pretty big backlog of issues to get through and didn't get a chance to get back to this one :(

In our working group meeting last week we discussed https://github.com/tektoncd/pipeline/issues/1027 which seems like it might accomplish what you are looking for by making it so that container names are included in statuses as well as step names? (It isn't using annotations like you described here tho)

Please re-open this issue if #1027 doesn't address what you wanted - I took a look at #936 and I'm not 100% sure it addresses this issue, but I might be missing something!
