### ISSUE TITLE
The default TaskRun timeout is too short.

### ISSUE THREAD

**Issue by abayer** [tektoncd/pipeline#979]
# Expected Behavior

A user shouldn't have their `TaskRun`s killed in 10 minutes if they haven't specified a larger `PipelineRun` timeout.

# Actual Behavior

The `TaskRun`s do get killed.

# Steps to Reproduce the Problem

1. Kinda obvious, really. =)

# Additional Info

We should bump this up to something more reasonable. Also relates to #978.

**Comment by vdemeester** [comment]
@abayer I feel there is two things we could do :

- Bump the timeout to something more reasonable (as a default), like 25min or sthg
- Make it possible to configure the default Pipeline timeout on the controller side

**Comment by abayer** [comment]
@vdemeester The latter would be fantastic.

**Comment by houshengbo** [comment]
@vdemeester @bobcatfish @abayer 

First, I'd like to increase the internal default timeout to 60 mins. Is that OK so far?
Then, since the timeout is not limited to taskrun only, I am thinking of creating a new YAML of a new ConfigMap under config dir, e.g. config-default.yaml for the configuration of a configurable timeout key called: defaultTimeoutMinutes.
If defaultTimeoutMinutes is not set, we fall back to the system internal timeout 60 mins. If it is set, we will use defaultTimeoutMinutes as the default timeout across all the tekton resources, if timeout is needed, but not specified.

How does it sound??

**Comment by abayer** [comment]
Sounds reasonable to me!

**Comment by bobcatfish** [comment]
Makes sense!

**Comment by houshengbo** [comment]
OK, I will implement as described.
